/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.AssignLargeTraderRequestCreate;
import com.apexfintechsolutions.ascendsdk.operations.AccountsAssignLargeTrader;
import com.apexfintechsolutions.ascendsdk.utils.Options;
import com.apexfintechsolutions.ascendsdk.utils.RetryConfig;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class AccountsAssignLargeTraderRequestBuilder {

  private String legalNaturalPersonId;
  private AssignLargeTraderRequestCreate assignLargeTraderRequestCreate;
  private Optional<RetryConfig> retryConfig = Optional.empty();
  private final SDKConfiguration sdkConfiguration;

  public AccountsAssignLargeTraderRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public AccountsAssignLargeTraderRequestBuilder legalNaturalPersonId(String legalNaturalPersonId) {
    Utils.checkNotNull(legalNaturalPersonId, "legalNaturalPersonId");
    this.legalNaturalPersonId = legalNaturalPersonId;
    return this;
  }

  public AccountsAssignLargeTraderRequestBuilder assignLargeTraderRequestCreate(
      AssignLargeTraderRequestCreate assignLargeTraderRequestCreate) {
    Utils.checkNotNull(assignLargeTraderRequestCreate, "assignLargeTraderRequestCreate");
    this.assignLargeTraderRequestCreate = assignLargeTraderRequestCreate;
    return this;
  }

  public AccountsAssignLargeTraderRequestBuilder retryConfig(RetryConfig retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = Optional.of(retryConfig);
    return this;
  }

  public AccountsAssignLargeTraderRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = retryConfig;
    return this;
  }

  private AccountsAssignLargeTraderRequest buildRequest() {

    AccountsAssignLargeTraderRequest request =
        new AccountsAssignLargeTraderRequest(legalNaturalPersonId, assignLargeTraderRequestCreate);

    return request;
  }

  public AccountsAssignLargeTraderResponse call() throws Exception {
    Optional<Options> options = Optional.of(Options.builder().retryConfig(retryConfig).build());

    RequestOperation<AccountsAssignLargeTraderRequest, AccountsAssignLargeTraderResponse>
        operation = new AccountsAssignLargeTrader.Sync(sdkConfiguration, options);
    AccountsAssignLargeTraderRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
