/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.ReplacePartyRequestCreate;
import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;

public class AccountsReplacePartyRequest {

  /** The account id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
  private String accountId;

  /** The party id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=party_id")
  private String partyId;

  @SpeakeasyMetadata("request:mediaType=application/json")
  private ReplacePartyRequestCreate replacePartyRequestCreate;

  @JsonCreator
  public AccountsReplacePartyRequest(
      String accountId, String partyId, ReplacePartyRequestCreate replacePartyRequestCreate) {
    Utils.checkNotNull(accountId, "accountId");
    Utils.checkNotNull(partyId, "partyId");
    Utils.checkNotNull(replacePartyRequestCreate, "replacePartyRequestCreate");
    this.accountId = accountId;
    this.partyId = partyId;
    this.replacePartyRequestCreate = replacePartyRequestCreate;
  }

  /** The account id. */
  @JsonIgnore
  public String accountId() {
    return accountId;
  }

  /** The party id. */
  @JsonIgnore
  public String partyId() {
    return partyId;
  }

  @JsonIgnore
  public ReplacePartyRequestCreate replacePartyRequestCreate() {
    return replacePartyRequestCreate;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The account id. */
  public AccountsReplacePartyRequest withAccountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  /** The party id. */
  public AccountsReplacePartyRequest withPartyId(String partyId) {
    Utils.checkNotNull(partyId, "partyId");
    this.partyId = partyId;
    return this;
  }

  public AccountsReplacePartyRequest withReplacePartyRequestCreate(
      ReplacePartyRequestCreate replacePartyRequestCreate) {
    Utils.checkNotNull(replacePartyRequestCreate, "replacePartyRequestCreate");
    this.replacePartyRequestCreate = replacePartyRequestCreate;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountsReplacePartyRequest other = (AccountsReplacePartyRequest) o;
    return Objects.deepEquals(this.accountId, other.accountId)
        && Objects.deepEquals(this.partyId, other.partyId)
        && Objects.deepEquals(this.replacePartyRequestCreate, other.replacePartyRequestCreate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, partyId, replacePartyRequestCreate);
  }

  @Override
  public String toString() {
    return Utils.toString(
        AccountsReplacePartyRequest.class,
        "accountId",
        accountId,
        "partyId",
        partyId,
        "replacePartyRequestCreate",
        replacePartyRequestCreate);
  }

  public static final class Builder {

    private String accountId;

    private String partyId;

    private ReplacePartyRequestCreate replacePartyRequestCreate;

    private Builder() {
      // force use of static builder() method
    }

    /** The account id. */
    public Builder accountId(String accountId) {
      Utils.checkNotNull(accountId, "accountId");
      this.accountId = accountId;
      return this;
    }

    /** The party id. */
    public Builder partyId(String partyId) {
      Utils.checkNotNull(partyId, "partyId");
      this.partyId = partyId;
      return this;
    }

    public Builder replacePartyRequestCreate(ReplacePartyRequestCreate replacePartyRequestCreate) {
      Utils.checkNotNull(replacePartyRequestCreate, "replacePartyRequestCreate");
      this.replacePartyRequestCreate = replacePartyRequestCreate;
      return this;
    }

    public AccountsReplacePartyRequest build() {
      return new AccountsReplacePartyRequest(accountId, partyId, replacePartyRequestCreate);
    }
  }
}
