/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.EndRestrictionRequestCreate;
import com.apexfintechsolutions.ascendsdk.operations.AccountsEndRestriction;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class AccountsEndRestrictionRequestBuilder {

  private String accountId;
  private String restrictionId;
  private EndRestrictionRequestCreate endRestrictionRequestCreate;
  private final SDKConfiguration sdkConfiguration;

  public AccountsEndRestrictionRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public AccountsEndRestrictionRequestBuilder accountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public AccountsEndRestrictionRequestBuilder restrictionId(String restrictionId) {
    Utils.checkNotNull(restrictionId, "restrictionId");
    this.restrictionId = restrictionId;
    return this;
  }

  public AccountsEndRestrictionRequestBuilder endRestrictionRequestCreate(
      EndRestrictionRequestCreate endRestrictionRequestCreate) {
    Utils.checkNotNull(endRestrictionRequestCreate, "endRestrictionRequestCreate");
    this.endRestrictionRequestCreate = endRestrictionRequestCreate;
    return this;
  }

  private AccountsEndRestrictionRequest buildRequest() {

    AccountsEndRestrictionRequest request =
        new AccountsEndRestrictionRequest(accountId, restrictionId, endRestrictionRequestCreate);

    return request;
  }

  public AccountsEndRestrictionResponse call() throws Exception {

    RequestOperation<AccountsEndRestrictionRequest, AccountsEndRestrictionResponse> operation =
        new AccountsEndRestriction.Sync(sdkConfiguration);
    AccountsEndRestrictionRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
