/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.AchDepositScheduleCreate;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class AchDepositSchedulesCreateAchDepositScheduleRequestBuilder {

  private String accountId;
  private AchDepositScheduleCreate achDepositScheduleCreate;
  private final SDKMethodInterfaces.MethodCallAchDepositSchedulesCreateAchDepositSchedule sdk;

  public AchDepositSchedulesCreateAchDepositScheduleRequestBuilder(
      SDKMethodInterfaces.MethodCallAchDepositSchedulesCreateAchDepositSchedule sdk) {
    this.sdk = sdk;
  }

  public AchDepositSchedulesCreateAchDepositScheduleRequestBuilder accountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public AchDepositSchedulesCreateAchDepositScheduleRequestBuilder achDepositScheduleCreate(
      AchDepositScheduleCreate achDepositScheduleCreate) {
    Utils.checkNotNull(achDepositScheduleCreate, "achDepositScheduleCreate");
    this.achDepositScheduleCreate = achDepositScheduleCreate;
    return this;
  }

  public AchDepositSchedulesCreateAchDepositScheduleResponse call() throws Exception {

    return sdk.createAchDepositSchedule(accountId, achDepositScheduleCreate);
  }
}
