/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.AchWithdrawalScheduleCreate;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequestBuilder {

  private String accountId;
  private AchWithdrawalScheduleCreate achWithdrawalScheduleCreate;
  private final SDKMethodInterfaces.MethodCallAchWithdrawalSchedulesCreateAchWithdrawalSchedule sdk;

  public AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequestBuilder(
      SDKMethodInterfaces.MethodCallAchWithdrawalSchedulesCreateAchWithdrawalSchedule sdk) {
    this.sdk = sdk;
  }

  public AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequestBuilder accountId(
      String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequestBuilder
      achWithdrawalScheduleCreate(AchWithdrawalScheduleCreate achWithdrawalScheduleCreate) {
    Utils.checkNotNull(achWithdrawalScheduleCreate, "achWithdrawalScheduleCreate");
    this.achWithdrawalScheduleCreate = achWithdrawalScheduleCreate;
    return this;
  }

  public AchWithdrawalSchedulesCreateAchWithdrawalScheduleResponse call() throws Exception {

    return sdk.createAchWithdrawalSchedule(accountId, achWithdrawalScheduleCreate);
  }
}
