/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.operations.AssetsGetAssetCorrespondent;
import com.apexfintechsolutions.ascendsdk.utils.Options;
import com.apexfintechsolutions.ascendsdk.utils.RetryConfig;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class AssetsGetAssetCorrespondentRequestBuilder {

  private String correspondentId;
  private String assetId;
  private Optional<RetryConfig> retryConfig = Optional.empty();
  private final SDKConfiguration sdkConfiguration;

  public AssetsGetAssetCorrespondentRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public AssetsGetAssetCorrespondentRequestBuilder correspondentId(String correspondentId) {
    Utils.checkNotNull(correspondentId, "correspondentId");
    this.correspondentId = correspondentId;
    return this;
  }

  public AssetsGetAssetCorrespondentRequestBuilder assetId(String assetId) {
    Utils.checkNotNull(assetId, "assetId");
    this.assetId = assetId;
    return this;
  }

  public AssetsGetAssetCorrespondentRequestBuilder retryConfig(RetryConfig retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = Optional.of(retryConfig);
    return this;
  }

  public AssetsGetAssetCorrespondentRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = retryConfig;
    return this;
  }

  private AssetsGetAssetCorrespondentRequest buildRequest() {

    AssetsGetAssetCorrespondentRequest request =
        new AssetsGetAssetCorrespondentRequest(correspondentId, assetId);

    return request;
  }

  public AssetsGetAssetCorrespondentResponse call() throws Exception {
    Optional<Options> options = Optional.of(Options.builder().retryConfig(retryConfig).build());

    RequestOperation<AssetsGetAssetCorrespondentRequest, AssetsGetAssetCorrespondentResponse>
        operation = new AssetsGetAssetCorrespondent.Sync(sdkConfiguration, options);
    AssetsGetAssetCorrespondentRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
