/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;
import java.util.Optional;

public class BankRelationshipsListBankRelationshipsRequest {

  /** The account id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
  private String accountId;

  /**
   * The maximum number of bank relationships to return. The service may return fewer than this
   * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
   * 1000; values above 1000 will be coerced to 1000.
   */
  @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
  private Optional<Integer> pageSize;

  /**
   * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
   * the subsequent page. When paginating, all other parameters provided to `ListBankRelationships`
   * must match the call that provided the page token.
   */
  @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")
  private Optional<String> pageToken;

  /**
   * The state of bank relationships to filter by. Unspecified returns relationships of all states.
   */
  @SpeakeasyMetadata("queryParam:style=form,explode=true,name=state")
  private Optional<? extends State> state;

  @JsonCreator
  public BankRelationshipsListBankRelationshipsRequest(
      String accountId,
      Optional<Integer> pageSize,
      Optional<String> pageToken,
      Optional<? extends State> state) {
    Utils.checkNotNull(accountId, "accountId");
    Utils.checkNotNull(pageSize, "pageSize");
    Utils.checkNotNull(pageToken, "pageToken");
    Utils.checkNotNull(state, "state");
    this.accountId = accountId;
    this.pageSize = pageSize;
    this.pageToken = pageToken;
    this.state = state;
  }

  public BankRelationshipsListBankRelationshipsRequest(String accountId) {
    this(accountId, Optional.empty(), Optional.empty(), Optional.empty());
  }

  /** The account id. */
  @JsonIgnore
  public String accountId() {
    return accountId;
  }

  /**
   * The maximum number of bank relationships to return. The service may return fewer than this
   * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
   * 1000; values above 1000 will be coerced to 1000.
   */
  @JsonIgnore
  public Optional<Integer> pageSize() {
    return pageSize;
  }

  /**
   * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
   * the subsequent page. When paginating, all other parameters provided to `ListBankRelationships`
   * must match the call that provided the page token.
   */
  @JsonIgnore
  public Optional<String> pageToken() {
    return pageToken;
  }

  /**
   * The state of bank relationships to filter by. Unspecified returns relationships of all states.
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<State> state() {
    return (Optional<State>) state;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The account id. */
  public BankRelationshipsListBankRelationshipsRequest withAccountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  /**
   * The maximum number of bank relationships to return. The service may return fewer than this
   * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
   * 1000; values above 1000 will be coerced to 1000.
   */
  public BankRelationshipsListBankRelationshipsRequest withPageSize(int pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = Optional.ofNullable(pageSize);
    return this;
  }

  /**
   * The maximum number of bank relationships to return. The service may return fewer than this
   * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
   * 1000; values above 1000 will be coerced to 1000.
   */
  public BankRelationshipsListBankRelationshipsRequest withPageSize(Optional<Integer> pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = pageSize;
    return this;
  }

  /**
   * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
   * the subsequent page. When paginating, all other parameters provided to `ListBankRelationships`
   * must match the call that provided the page token.
   */
  public BankRelationshipsListBankRelationshipsRequest withPageToken(String pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = Optional.ofNullable(pageToken);
    return this;
  }

  /**
   * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
   * the subsequent page. When paginating, all other parameters provided to `ListBankRelationships`
   * must match the call that provided the page token.
   */
  public BankRelationshipsListBankRelationshipsRequest withPageToken(Optional<String> pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = pageToken;
    return this;
  }

  /**
   * The state of bank relationships to filter by. Unspecified returns relationships of all states.
   */
  public BankRelationshipsListBankRelationshipsRequest withState(State state) {
    Utils.checkNotNull(state, "state");
    this.state = Optional.ofNullable(state);
    return this;
  }

  /**
   * The state of bank relationships to filter by. Unspecified returns relationships of all states.
   */
  public BankRelationshipsListBankRelationshipsRequest withState(Optional<? extends State> state) {
    Utils.checkNotNull(state, "state");
    this.state = state;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankRelationshipsListBankRelationshipsRequest other =
        (BankRelationshipsListBankRelationshipsRequest) o;
    return Objects.deepEquals(this.accountId, other.accountId)
        && Objects.deepEquals(this.pageSize, other.pageSize)
        && Objects.deepEquals(this.pageToken, other.pageToken)
        && Objects.deepEquals(this.state, other.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, pageSize, pageToken, state);
  }

  @Override
  public String toString() {
    return Utils.toString(
        BankRelationshipsListBankRelationshipsRequest.class,
        "accountId",
        accountId,
        "pageSize",
        pageSize,
        "pageToken",
        pageToken,
        "state",
        state);
  }

  public static final class Builder {

    private String accountId;

    private Optional<Integer> pageSize = Optional.empty();

    private Optional<String> pageToken = Optional.empty();

    private Optional<? extends State> state = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** The account id. */
    public Builder accountId(String accountId) {
      Utils.checkNotNull(accountId, "accountId");
      this.accountId = accountId;
      return this;
    }

    /**
     * The maximum number of bank relationships to return. The service may return fewer than this
     * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
     * 1000; values above 1000 will be coerced to 1000.
     */
    public Builder pageSize(int pageSize) {
      Utils.checkNotNull(pageSize, "pageSize");
      this.pageSize = Optional.ofNullable(pageSize);
      return this;
    }

    /**
     * The maximum number of bank relationships to return. The service may return fewer than this
     * value. If unspecified, at most 50 bank relationships will be returned. The maximum value is
     * 1000; values above 1000 will be coerced to 1000.
     */
    public Builder pageSize(Optional<Integer> pageSize) {
      Utils.checkNotNull(pageSize, "pageSize");
      this.pageSize = pageSize;
      return this;
    }

    /**
     * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
     * the subsequent page. When paginating, all other parameters provided to
     * `ListBankRelationships` must match the call that provided the page token.
     */
    public Builder pageToken(String pageToken) {
      Utils.checkNotNull(pageToken, "pageToken");
      this.pageToken = Optional.ofNullable(pageToken);
      return this;
    }

    /**
     * A page token, received from a previous `ListBankRelationships` call. Provide this to retrieve
     * the subsequent page. When paginating, all other parameters provided to
     * `ListBankRelationships` must match the call that provided the page token.
     */
    public Builder pageToken(Optional<String> pageToken) {
      Utils.checkNotNull(pageToken, "pageToken");
      this.pageToken = pageToken;
      return this;
    }

    /**
     * The state of bank relationships to filter by. Unspecified returns relationships of all
     * states.
     */
    public Builder state(State state) {
      Utils.checkNotNull(state, "state");
      this.state = Optional.ofNullable(state);
      return this;
    }

    /**
     * The state of bank relationships to filter by. Unspecified returns relationships of all
     * states.
     */
    public Builder state(Optional<? extends State> state) {
      Utils.checkNotNull(state, "state");
      this.state = state;
      return this;
    }

    public BankRelationshipsListBankRelationshipsRequest build() {
      return new BankRelationshipsListBankRelationshipsRequest(
          accountId, pageSize, pageToken, state);
    }
  }
}
