/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.Execution;
import com.apexfintechsolutions.ascendsdk.models.components.Status;
import com.apexfintechsolutions.ascendsdk.utils.Response;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class BookingCreateExecutionResponse implements Response {

  /** HTTP response content type for this operation */
  private String contentType;

  /** HTTP response status code for this operation */
  private int statusCode;

  /** Raw HTTP response; suitable for custom response parsing */
  private HttpResponse<InputStream> rawResponse;

  /** OK */
  private Optional<? extends Execution> execution;

  /**
   * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
   * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
   */
  private Optional<? extends Status> status;

  @JsonCreator
  public BookingCreateExecutionResponse(
      String contentType,
      int statusCode,
      HttpResponse<InputStream> rawResponse,
      Optional<? extends Execution> execution,
      Optional<? extends Status> status) {
    Utils.checkNotNull(contentType, "contentType");
    Utils.checkNotNull(statusCode, "statusCode");
    Utils.checkNotNull(rawResponse, "rawResponse");
    Utils.checkNotNull(execution, "execution");
    Utils.checkNotNull(status, "status");
    this.contentType = contentType;
    this.statusCode = statusCode;
    this.rawResponse = rawResponse;
    this.execution = execution;
    this.status = status;
  }

  public BookingCreateExecutionResponse(
      String contentType, int statusCode, HttpResponse<InputStream> rawResponse) {
    this(contentType, statusCode, rawResponse, Optional.empty(), Optional.empty());
  }

  /** HTTP response content type for this operation */
  @JsonIgnore
  public String contentType() {
    return contentType;
  }

  /** HTTP response status code for this operation */
  @JsonIgnore
  public int statusCode() {
    return statusCode;
  }

  /** Raw HTTP response; suitable for custom response parsing */
  @JsonIgnore
  public HttpResponse<InputStream> rawResponse() {
    return rawResponse;
  }

  /** OK */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<Execution> execution() {
    return (Optional<Execution>) execution;
  }

  /**
   * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
   * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<Status> status() {
    return (Optional<Status>) status;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** HTTP response content type for this operation */
  public BookingCreateExecutionResponse withContentType(String contentType) {
    Utils.checkNotNull(contentType, "contentType");
    this.contentType = contentType;
    return this;
  }

  /** HTTP response status code for this operation */
  public BookingCreateExecutionResponse withStatusCode(int statusCode) {
    Utils.checkNotNull(statusCode, "statusCode");
    this.statusCode = statusCode;
    return this;
  }

  /** Raw HTTP response; suitable for custom response parsing */
  public BookingCreateExecutionResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
    Utils.checkNotNull(rawResponse, "rawResponse");
    this.rawResponse = rawResponse;
    return this;
  }

  /** OK */
  public BookingCreateExecutionResponse withExecution(Execution execution) {
    Utils.checkNotNull(execution, "execution");
    this.execution = Optional.ofNullable(execution);
    return this;
  }

  /** OK */
  public BookingCreateExecutionResponse withExecution(Optional<? extends Execution> execution) {
    Utils.checkNotNull(execution, "execution");
    this.execution = execution;
    return this;
  }

  /**
   * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
   * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
   */
  public BookingCreateExecutionResponse withStatus(Status status) {
    Utils.checkNotNull(status, "status");
    this.status = Optional.ofNullable(status);
    return this;
  }

  /**
   * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
   * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
   */
  public BookingCreateExecutionResponse withStatus(Optional<? extends Status> status) {
    Utils.checkNotNull(status, "status");
    this.status = status;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingCreateExecutionResponse other = (BookingCreateExecutionResponse) o;
    return Objects.deepEquals(this.contentType, other.contentType)
        && Objects.deepEquals(this.statusCode, other.statusCode)
        && Objects.deepEquals(this.rawResponse, other.rawResponse)
        && Objects.deepEquals(this.execution, other.execution)
        && Objects.deepEquals(this.status, other.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, statusCode, rawResponse, execution, status);
  }

  @Override
  public String toString() {
    return Utils.toString(
        BookingCreateExecutionResponse.class,
        "contentType",
        contentType,
        "statusCode",
        statusCode,
        "rawResponse",
        rawResponse,
        "execution",
        execution,
        "status",
        status);
  }

  public static final class Builder {

    private String contentType;

    private Integer statusCode;

    private HttpResponse<InputStream> rawResponse;

    private Optional<? extends Execution> execution = Optional.empty();

    private Optional<? extends Status> status = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** HTTP response content type for this operation */
    public Builder contentType(String contentType) {
      Utils.checkNotNull(contentType, "contentType");
      this.contentType = contentType;
      return this;
    }

    /** HTTP response status code for this operation */
    public Builder statusCode(int statusCode) {
      Utils.checkNotNull(statusCode, "statusCode");
      this.statusCode = statusCode;
      return this;
    }

    /** Raw HTTP response; suitable for custom response parsing */
    public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
      Utils.checkNotNull(rawResponse, "rawResponse");
      this.rawResponse = rawResponse;
      return this;
    }

    /** OK */
    public Builder execution(Execution execution) {
      Utils.checkNotNull(execution, "execution");
      this.execution = Optional.ofNullable(execution);
      return this;
    }

    /** OK */
    public Builder execution(Optional<? extends Execution> execution) {
      Utils.checkNotNull(execution, "execution");
      this.execution = execution;
      return this;
    }

    /**
     * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
     * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
     */
    public Builder status(Status status) {
      Utils.checkNotNull(status, "status");
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * FAILED_PRECONDITION: The operation was rejected because the system is not in a state required
     * for the operation's processing. INVALID_ARGUMENT: The request is not valid.
     */
    public Builder status(Optional<? extends Status> status) {
      Utils.checkNotNull(status, "status");
      this.status = status;
      return this;
    }

    public BookingCreateExecutionResponse build() {
      return new BookingCreateExecutionResponse(
          contentType, statusCode, rawResponse, execution, status);
    }
  }
}
