/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.RebookTradeAllocationRequestCreate;
import com.apexfintechsolutions.ascendsdk.operations.BookingRebookTradeAllocation;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class BookingRebookTradeAllocationRequestBuilder {

  private String accountId;
  private String tradeAllocationId;
  private RebookTradeAllocationRequestCreate rebookTradeAllocationRequestCreate;
  private final SDKConfiguration sdkConfiguration;

  public BookingRebookTradeAllocationRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public BookingRebookTradeAllocationRequestBuilder accountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public BookingRebookTradeAllocationRequestBuilder tradeAllocationId(String tradeAllocationId) {
    Utils.checkNotNull(tradeAllocationId, "tradeAllocationId");
    this.tradeAllocationId = tradeAllocationId;
    return this;
  }

  public BookingRebookTradeAllocationRequestBuilder rebookTradeAllocationRequestCreate(
      RebookTradeAllocationRequestCreate rebookTradeAllocationRequestCreate) {
    Utils.checkNotNull(rebookTradeAllocationRequestCreate, "rebookTradeAllocationRequestCreate");
    this.rebookTradeAllocationRequestCreate = rebookTradeAllocationRequestCreate;
    return this;
  }

  private BookingRebookTradeAllocationRequest buildRequest() {

    BookingRebookTradeAllocationRequest request =
        new BookingRebookTradeAllocationRequest(
            accountId, tradeAllocationId, rebookTradeAllocationRequestCreate);

    return request;
  }

  public BookingRebookTradeAllocationResponse call() throws Exception {

    RequestOperation<BookingRebookTradeAllocationRequest, BookingRebookTradeAllocationResponse>
        operation = new BookingRebookTradeAllocation.Sync(sdkConfiguration);
    BookingRebookTradeAllocationRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
