/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.operations.CashJournalsGetCashJournal;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class CashJournalsGetCashJournalRequestBuilder {

  private String cashJournalId;
  private final SDKConfiguration sdkConfiguration;

  public CashJournalsGetCashJournalRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public CashJournalsGetCashJournalRequestBuilder cashJournalId(String cashJournalId) {
    Utils.checkNotNull(cashJournalId, "cashJournalId");
    this.cashJournalId = cashJournalId;
    return this;
  }

  private CashJournalsGetCashJournalRequest buildRequest() {

    CashJournalsGetCashJournalRequest request =
        new CashJournalsGetCashJournalRequest(cashJournalId);

    return request;
  }

  public CashJournalsGetCashJournalResponse call() throws Exception {

    RequestOperation<CashJournalsGetCashJournalRequest, CashJournalsGetCashJournalResponse>
        operation = new CashJournalsGetCashJournal.Sync(sdkConfiguration);
    CashJournalsGetCashJournalRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
