/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.ForceApproveCashJournalRequestCreate;
import com.apexfintechsolutions.ascendsdk.operations.CashJournalsForceApproveCashJournal;
import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class CashJournalsForceApproveCashJournalRequestBuilder {

  private String cashJournalId;
  private ForceApproveCashJournalRequestCreate forceApproveCashJournalRequestCreate;
  private final SDKConfiguration sdkConfiguration;

  public CashJournalsForceApproveCashJournalRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public CashJournalsForceApproveCashJournalRequestBuilder cashJournalId(String cashJournalId) {
    Utils.checkNotNull(cashJournalId, "cashJournalId");
    this.cashJournalId = cashJournalId;
    return this;
  }

  public CashJournalsForceApproveCashJournalRequestBuilder forceApproveCashJournalRequestCreate(
      ForceApproveCashJournalRequestCreate forceApproveCashJournalRequestCreate) {
    Utils.checkNotNull(
        forceApproveCashJournalRequestCreate, "forceApproveCashJournalRequestCreate");
    this.forceApproveCashJournalRequestCreate = forceApproveCashJournalRequestCreate;
    return this;
  }

  private CashJournalsForceApproveCashJournalRequest buildRequest() {

    CashJournalsForceApproveCashJournalRequest request =
        new CashJournalsForceApproveCashJournalRequest(
            cashJournalId, forceApproveCashJournalRequestCreate);

    return request;
  }

  public CashJournalsForceApproveCashJournalResponse call() throws Exception {

    RequestOperation<
            CashJournalsForceApproveCashJournalRequest, CashJournalsForceApproveCashJournalResponse>
        operation = new CashJournalsForceApproveCashJournal.Sync(sdkConfiguration);
    CashJournalsForceApproveCashJournalRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
