/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.ForceRejectCashJournalRequestCreate;
import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;

public class CashJournalsForceRejectCashJournalRequest {
  /** The cashJournal id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=cashJournal_id")
  private String cashJournalId;

  @SpeakeasyMetadata("request:mediaType=application/json")
  private ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate;

  @JsonCreator
  public CashJournalsForceRejectCashJournalRequest(
      String cashJournalId,
      ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate) {
    Utils.checkNotNull(cashJournalId, "cashJournalId");
    Utils.checkNotNull(forceRejectCashJournalRequestCreate, "forceRejectCashJournalRequestCreate");
    this.cashJournalId = cashJournalId;
    this.forceRejectCashJournalRequestCreate = forceRejectCashJournalRequestCreate;
  }

  /** The cashJournal id. */
  @JsonIgnore
  public String cashJournalId() {
    return cashJournalId;
  }

  @JsonIgnore
  public ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate() {
    return forceRejectCashJournalRequestCreate;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** The cashJournal id. */
  public CashJournalsForceRejectCashJournalRequest withCashJournalId(String cashJournalId) {
    Utils.checkNotNull(cashJournalId, "cashJournalId");
    this.cashJournalId = cashJournalId;
    return this;
  }

  public CashJournalsForceRejectCashJournalRequest withForceRejectCashJournalRequestCreate(
      ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate) {
    Utils.checkNotNull(forceRejectCashJournalRequestCreate, "forceRejectCashJournalRequestCreate");
    this.forceRejectCashJournalRequestCreate = forceRejectCashJournalRequestCreate;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashJournalsForceRejectCashJournalRequest other = (CashJournalsForceRejectCashJournalRequest) o;
    return Utils.enhancedDeepEquals(this.cashJournalId, other.cashJournalId)
        && Utils.enhancedDeepEquals(
            this.forceRejectCashJournalRequestCreate, other.forceRejectCashJournalRequestCreate);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(cashJournalId, forceRejectCashJournalRequestCreate);
  }

  @Override
  public String toString() {
    return Utils.toString(
        CashJournalsForceRejectCashJournalRequest.class,
        "cashJournalId",
        cashJournalId,
        "forceRejectCashJournalRequestCreate",
        forceRejectCashJournalRequestCreate);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private String cashJournalId;

    private ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate;

    private Builder() {
      // force use of static builder() method
    }

    /** The cashJournal id. */
    public Builder cashJournalId(String cashJournalId) {
      Utils.checkNotNull(cashJournalId, "cashJournalId");
      this.cashJournalId = cashJournalId;
      return this;
    }

    public Builder forceRejectCashJournalRequestCreate(
        ForceRejectCashJournalRequestCreate forceRejectCashJournalRequestCreate) {
      Utils.checkNotNull(
          forceRejectCashJournalRequestCreate, "forceRejectCashJournalRequestCreate");
      this.forceRejectCashJournalRequestCreate = forceRejectCashJournalRequestCreate;
      return this;
    }

    public CashJournalsForceRejectCashJournalRequest build() {

      return new CashJournalsForceRejectCashJournalRequest(
          cashJournalId, forceRejectCashJournalRequestCreate);
    }
  }
}
