/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.utils.Utils;

public class FeesGetFeeRequestBuilder {

  private String accountId;
  private String feeId;
  private final SDKMethodInterfaces.MethodCallFeesGetFee sdk;

  public FeesGetFeeRequestBuilder(SDKMethodInterfaces.MethodCallFeesGetFee sdk) {
    this.sdk = sdk;
  }

  public FeesGetFeeRequestBuilder accountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public FeesGetFeeRequestBuilder feeId(String feeId) {
    Utils.checkNotNull(feeId, "feeId");
    this.feeId = feeId;
    return this;
  }

  public FeesGetFeeResponse call() throws Exception {

    return sdk.getFee(accountId, feeId);
  }
}
