/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class InvestorCommunicationServiceListDocumentsRequestBuilder {

  private Optional<Integer> pageSize = Optional.empty();
  private Optional<String> pageToken = Optional.empty();
  private Optional<String> filter = Optional.empty();
  private final SDKMethodInterfaces.MethodCallInvestorCommunicationServiceListDocuments sdk;

  public InvestorCommunicationServiceListDocumentsRequestBuilder(
      SDKMethodInterfaces.MethodCallInvestorCommunicationServiceListDocuments sdk) {
    this.sdk = sdk;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder pageSize(int pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = Optional.of(pageSize);
    return this;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder pageSize(
      Optional<Integer> pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = pageSize;
    return this;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder pageToken(String pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = Optional.of(pageToken);
    return this;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder pageToken(
      Optional<String> pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = pageToken;
    return this;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder filter(String filter) {
    Utils.checkNotNull(filter, "filter");
    this.filter = Optional.of(filter);
    return this;
  }

  public InvestorCommunicationServiceListDocumentsRequestBuilder filter(Optional<String> filter) {
    Utils.checkNotNull(filter, "filter");
    this.filter = filter;
    return this;
  }

  public InvestorCommunicationServiceListDocumentsResponse call() throws Exception {

    return sdk.listDocuments(pageSize, pageToken, filter);
  }
}
