/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.CancelOrderRequestCreate;
import com.apexfintechsolutions.ascendsdk.operations.OrderServiceCancelOrder;
import com.apexfintechsolutions.ascendsdk.utils.Options;
import com.apexfintechsolutions.ascendsdk.utils.RetryConfig;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class OrderServiceCancelOrderRequestBuilder {

  private String accountId;
  private String orderId;
  private CancelOrderRequestCreate cancelOrderRequestCreate;
  private Optional<RetryConfig> retryConfig = Optional.empty();
  private final SDKConfiguration sdkConfiguration;

  public OrderServiceCancelOrderRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public OrderServiceCancelOrderRequestBuilder accountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public OrderServiceCancelOrderRequestBuilder orderId(String orderId) {
    Utils.checkNotNull(orderId, "orderId");
    this.orderId = orderId;
    return this;
  }

  public OrderServiceCancelOrderRequestBuilder cancelOrderRequestCreate(
      CancelOrderRequestCreate cancelOrderRequestCreate) {
    Utils.checkNotNull(cancelOrderRequestCreate, "cancelOrderRequestCreate");
    this.cancelOrderRequestCreate = cancelOrderRequestCreate;
    return this;
  }

  public OrderServiceCancelOrderRequestBuilder retryConfig(RetryConfig retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = Optional.of(retryConfig);
    return this;
  }

  public OrderServiceCancelOrderRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = retryConfig;
    return this;
  }

  private OrderServiceCancelOrderRequest buildRequest() {

    OrderServiceCancelOrderRequest request =
        new OrderServiceCancelOrderRequest(accountId, orderId, cancelOrderRequestCreate);

    return request;
  }

  public OrderServiceCancelOrderResponse call() throws Exception {
    Optional<Options> options = Optional.of(Options.builder().retryConfig(retryConfig).build());

    RequestOperation<OrderServiceCancelOrderRequest, OrderServiceCancelOrderResponse> operation =
        new OrderServiceCancelOrder.Sync(sdkConfiguration, options);
    OrderServiceCancelOrderRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
