/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.RetrieveFixedIncomeMarksRequestCreate;
import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;

public class OrderPriceServiceRetrieveFixedIncomeMarksRequest {
  /** The correspondent id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=correspondent_id")
  private String correspondentId;

  @SpeakeasyMetadata("request:mediaType=application/json")
  private RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate;

  @JsonCreator
  public OrderPriceServiceRetrieveFixedIncomeMarksRequest(
      String correspondentId,
      RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate) {
    Utils.checkNotNull(correspondentId, "correspondentId");
    Utils.checkNotNull(
        retrieveFixedIncomeMarksRequestCreate, "retrieveFixedIncomeMarksRequestCreate");
    this.correspondentId = correspondentId;
    this.retrieveFixedIncomeMarksRequestCreate = retrieveFixedIncomeMarksRequestCreate;
  }

  /** The correspondent id. */
  @JsonIgnore
  public String correspondentId() {
    return correspondentId;
  }

  @JsonIgnore
  public RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate() {
    return retrieveFixedIncomeMarksRequestCreate;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** The correspondent id. */
  public OrderPriceServiceRetrieveFixedIncomeMarksRequest withCorrespondentId(
      String correspondentId) {
    Utils.checkNotNull(correspondentId, "correspondentId");
    this.correspondentId = correspondentId;
    return this;
  }

  public OrderPriceServiceRetrieveFixedIncomeMarksRequest withRetrieveFixedIncomeMarksRequestCreate(
      RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate) {
    Utils.checkNotNull(
        retrieveFixedIncomeMarksRequestCreate, "retrieveFixedIncomeMarksRequestCreate");
    this.retrieveFixedIncomeMarksRequestCreate = retrieveFixedIncomeMarksRequestCreate;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderPriceServiceRetrieveFixedIncomeMarksRequest other =
        (OrderPriceServiceRetrieveFixedIncomeMarksRequest) o;
    return Utils.enhancedDeepEquals(this.correspondentId, other.correspondentId)
        && Utils.enhancedDeepEquals(
            this.retrieveFixedIncomeMarksRequestCreate,
            other.retrieveFixedIncomeMarksRequestCreate);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(correspondentId, retrieveFixedIncomeMarksRequestCreate);
  }

  @Override
  public String toString() {
    return Utils.toString(
        OrderPriceServiceRetrieveFixedIncomeMarksRequest.class,
        "correspondentId",
        correspondentId,
        "retrieveFixedIncomeMarksRequestCreate",
        retrieveFixedIncomeMarksRequestCreate);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private String correspondentId;

    private RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate;

    private Builder() {
      // force use of static builder() method
    }

    /** The correspondent id. */
    public Builder correspondentId(String correspondentId) {
      Utils.checkNotNull(correspondentId, "correspondentId");
      this.correspondentId = correspondentId;
      return this;
    }

    public Builder retrieveFixedIncomeMarksRequestCreate(
        RetrieveFixedIncomeMarksRequestCreate retrieveFixedIncomeMarksRequestCreate) {
      Utils.checkNotNull(
          retrieveFixedIncomeMarksRequestCreate, "retrieveFixedIncomeMarksRequestCreate");
      this.retrieveFixedIncomeMarksRequestCreate = retrieveFixedIncomeMarksRequestCreate;
      return this;
    }

    public OrderPriceServiceRetrieveFixedIncomeMarksRequest build() {

      return new OrderPriceServiceRetrieveFixedIncomeMarksRequest(
          correspondentId, retrieveFixedIncomeMarksRequestCreate);
    }
  }
}
