/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.models.components.PositionJournalCreate;
import com.apexfintechsolutions.ascendsdk.operations.PositionJournalsCreatePositionJournal;
import com.apexfintechsolutions.ascendsdk.utils.Options;
import com.apexfintechsolutions.ascendsdk.utils.RetryConfig;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class PositionJournalsCreatePositionJournalRequestBuilder {

  private PositionJournalCreate request;
  private Optional<RetryConfig> retryConfig = Optional.empty();
  private final SDKConfiguration sdkConfiguration;

  public PositionJournalsCreatePositionJournalRequestBuilder(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public PositionJournalsCreatePositionJournalRequestBuilder request(
      PositionJournalCreate request) {
    Utils.checkNotNull(request, "request");
    this.request = request;
    return this;
  }

  public PositionJournalsCreatePositionJournalRequestBuilder retryConfig(RetryConfig retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = Optional.of(retryConfig);
    return this;
  }

  public PositionJournalsCreatePositionJournalRequestBuilder retryConfig(
      Optional<RetryConfig> retryConfig) {
    Utils.checkNotNull(retryConfig, "retryConfig");
    this.retryConfig = retryConfig;
    return this;
  }

  public PositionJournalsCreatePositionJournalResponse call() throws Exception {
    Optional<Options> options = Optional.of(Options.builder().retryConfig(retryConfig).build());

    RequestOperation<PositionJournalCreate, PositionJournalsCreatePositionJournalResponse>
        operation = new PositionJournalsCreatePositionJournal.Sync(sdkConfiguration, options);

    return operation.handleResponse(operation.doRequest(request));
  }
}
