/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;

public class ReaderGetEventMessageRequest {

  /** The message id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=message_id")
  private String messageId;

  @JsonCreator
  public ReaderGetEventMessageRequest(String messageId) {
    Utils.checkNotNull(messageId, "messageId");
    this.messageId = messageId;
  }

  /** The message id. */
  @JsonIgnore
  public String messageId() {
    return messageId;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The message id. */
  public ReaderGetEventMessageRequest withMessageId(String messageId) {
    Utils.checkNotNull(messageId, "messageId");
    this.messageId = messageId;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReaderGetEventMessageRequest other = (ReaderGetEventMessageRequest) o;
    return Objects.deepEquals(this.messageId, other.messageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId);
  }

  @Override
  public String toString() {
    return Utils.toString(ReaderGetEventMessageRequest.class, "messageId", messageId);
  }

  public static final class Builder {

    private String messageId;

    private Builder() {
      // force use of static builder() method
    }

    /** The message id. */
    public Builder messageId(String messageId) {
      Utils.checkNotNull(messageId, "messageId");
      this.messageId = messageId;
      return this;
    }

    public ReaderGetEventMessageRequest build() {
      return new ReaderGetEventMessageRequest(messageId);
    }
  }
}
