/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.operations.TransferScheduleSummariesListScheduleSummaries;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.Optional;

public class TransferScheduleSummariesListScheduleSummariesRequestBuilder {

  private Optional<String> filter = Optional.empty();
  private Optional<Integer> pageSize = Optional.empty();
  private Optional<String> pageToken = Optional.empty();
  private final SDKConfiguration sdkConfiguration;

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder(
      SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder filter(String filter) {
    Utils.checkNotNull(filter, "filter");
    this.filter = Optional.of(filter);
    return this;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder filter(
      Optional<String> filter) {
    Utils.checkNotNull(filter, "filter");
    this.filter = filter;
    return this;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder pageSize(int pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = Optional.of(pageSize);
    return this;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder pageSize(
      Optional<Integer> pageSize) {
    Utils.checkNotNull(pageSize, "pageSize");
    this.pageSize = pageSize;
    return this;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder pageToken(String pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = Optional.of(pageToken);
    return this;
  }

  public TransferScheduleSummariesListScheduleSummariesRequestBuilder pageToken(
      Optional<String> pageToken) {
    Utils.checkNotNull(pageToken, "pageToken");
    this.pageToken = pageToken;
    return this;
  }

  private TransferScheduleSummariesListScheduleSummariesRequest buildRequest() {

    TransferScheduleSummariesListScheduleSummariesRequest request =
        new TransferScheduleSummariesListScheduleSummariesRequest(filter, pageSize, pageToken);

    return request;
  }

  public TransferScheduleSummariesListScheduleSummariesResponse call() throws Exception {

    RequestOperation<
            TransferScheduleSummariesListScheduleSummariesRequest,
            TransferScheduleSummariesListScheduleSummariesResponse>
        operation = new TransferScheduleSummariesListScheduleSummaries.Sync(sdkConfiguration);
    TransferScheduleSummariesListScheduleSummariesRequest request = buildRequest();

    return operation.handleResponse(operation.doRequest(request));
  }
}
