/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.operations;

import com.apexfintechsolutions.ascendsdk.models.components.SimulateWireDepositRequestCreate;
import com.apexfintechsolutions.ascendsdk.utils.SpeakeasyMetadata;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;

public class WireDepositsSimulateWireDepositRequest {
  /** The account id. */
  @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
  private String accountId;

  @SpeakeasyMetadata("request:mediaType=application/json")
  private SimulateWireDepositRequestCreate simulateWireDepositRequestCreate;

  @JsonCreator
  public WireDepositsSimulateWireDepositRequest(
      String accountId, SimulateWireDepositRequestCreate simulateWireDepositRequestCreate) {
    Utils.checkNotNull(accountId, "accountId");
    Utils.checkNotNull(simulateWireDepositRequestCreate, "simulateWireDepositRequestCreate");
    this.accountId = accountId;
    this.simulateWireDepositRequestCreate = simulateWireDepositRequestCreate;
  }

  /** The account id. */
  @JsonIgnore
  public String accountId() {
    return accountId;
  }

  @JsonIgnore
  public SimulateWireDepositRequestCreate simulateWireDepositRequestCreate() {
    return simulateWireDepositRequestCreate;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** The account id. */
  public WireDepositsSimulateWireDepositRequest withAccountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  public WireDepositsSimulateWireDepositRequest withSimulateWireDepositRequestCreate(
      SimulateWireDepositRequestCreate simulateWireDepositRequestCreate) {
    Utils.checkNotNull(simulateWireDepositRequestCreate, "simulateWireDepositRequestCreate");
    this.simulateWireDepositRequestCreate = simulateWireDepositRequestCreate;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WireDepositsSimulateWireDepositRequest other = (WireDepositsSimulateWireDepositRequest) o;
    return Utils.enhancedDeepEquals(this.accountId, other.accountId)
        && Utils.enhancedDeepEquals(
            this.simulateWireDepositRequestCreate, other.simulateWireDepositRequestCreate);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(accountId, simulateWireDepositRequestCreate);
  }

  @Override
  public String toString() {
    return Utils.toString(
        WireDepositsSimulateWireDepositRequest.class,
        "accountId",
        accountId,
        "simulateWireDepositRequestCreate",
        simulateWireDepositRequestCreate);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private String accountId;

    private SimulateWireDepositRequestCreate simulateWireDepositRequestCreate;

    private Builder() {
      // force use of static builder() method
    }

    /** The account id. */
    public Builder accountId(String accountId) {
      Utils.checkNotNull(accountId, "accountId");
      this.accountId = accountId;
      return this;
    }

    public Builder simulateWireDepositRequestCreate(
        SimulateWireDepositRequestCreate simulateWireDepositRequestCreate) {
      Utils.checkNotNull(simulateWireDepositRequestCreate, "simulateWireDepositRequestCreate");
      this.simulateWireDepositRequestCreate = simulateWireDepositRequestCreate;
      return this;
    }

    public WireDepositsSimulateWireDepositRequest build() {

      return new WireDepositsSimulateWireDepositRequest(
          accountId, simulateWireDepositRequestCreate);
    }
  }
}
