/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.apexfintechsolutions.ascendsdk.models.components.AlternativeOrderCreate;
import com.apexfintechsolutions.ascendsdk.models.components.AlternativeOrderCreateIdentifierType;
import com.apexfintechsolutions.ascendsdk.models.components.AlternativeOrderCreateSide;
import com.apexfintechsolutions.ascendsdk.models.components.DecimalCreate;
import com.apexfintechsolutions.ascendsdk.models.components.OrderSettlementTarget;
import com.apexfintechsolutions.ascendsdk.models.components.Security;
import com.apexfintechsolutions.ascendsdk.models.components.ServiceAccountCreds;
import com.apexfintechsolutions.ascendsdk.models.components.SettleAlternativeOrderRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.operations.AlternativeOrdersCreateAlternativeOrderResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AlternativeOrdersGetAlternativeOrderResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AlternativeOrdersListAlternativeOrdersResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AlternativeOrdersRetrievePendingInvestorActionsResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AlternativeOrdersSettleAlternativeOrderResponse;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import java.util.UUID;
import org.junit.jupiter.api.Test;

public class AlternativeOrdersTests {

  @Test
  public void testAlternativeOrders_AlternativeOrdersCreateAlternativeOrder() throws Exception {

    var testHttpClient = Utils.createTestHTTPClient("AlternativeOrders_CreateAlternativeOrder");
    SDK sdk =
        SDK.builder()
            .serverURL(Utils.environmentVariable("SERVICE_ACCOUNT_CREDS_URL", ""))
            .security(
                Security.builder()
                    .apiKey(Utils.environmentVariable("API_KEY", ""))
                    .serviceAccountCreds(
                        ServiceAccountCreds.builder()
                            .privateKey(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""))
                            .name(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_NAME", ""))
                            .organization(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""))
                            .type(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_TYPE", ""))
                            .build())
                    .build())
            .client(testHttpClient)
            .build();

    AlternativeOrdersCreateAlternativeOrderResponse res =
        sdk.alternativeOrders()
            .createAlternativeOrder()
            .accountId("01JHGTEPC6ZTAHCFRH2MD3VJJT")
            .alternativeOrderCreate(
                AlternativeOrderCreate.builder()
                    .clientOrderId(UUID.randomUUID().toString())
                    .identifier("6684398")
                    .identifierType(AlternativeOrderCreateIdentifierType.ASSET_ID)
                    .side(AlternativeOrderCreateSide.BUY)
                    .notionalValue(DecimalCreate.builder().value("10000").build())
                    .build())
            .call();
    assertEquals(200, res.statusCode());
  }

  @Test
  public void testAlternativeOrders_AlternativeOrdersListAlternativeOrders() throws Exception {

    var testHttpClient = Utils.createTestHTTPClient("AlternativeOrders_ListAlternativeOrders");
    SDK sdk =
        SDK.builder()
            .serverURL(Utils.environmentVariable("SERVICE_ACCOUNT_CREDS_URL", ""))
            .security(
                Security.builder()
                    .apiKey(Utils.environmentVariable("API_KEY", ""))
                    .serviceAccountCreds(
                        ServiceAccountCreds.builder()
                            .privateKey(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""))
                            .name(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_NAME", ""))
                            .organization(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""))
                            .type(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_TYPE", ""))
                            .build())
                    .build())
            .client(testHttpClient)
            .build();

    AlternativeOrdersListAlternativeOrdersResponse res =
        sdk.alternativeOrders()
            .listAlternativeOrders()
            .accountId("01JHGTEPC6ZTAHCFRH2MD3VJJT")
            .pageSize(25)
            .pageToken("")
            .filter("")
            .call();
    assertEquals(200, res.statusCode());
  }

  @Test
  public void testAlternativeOrders_AlternativeOrdersGetAlternativeOrder() throws Exception {

    var testHttpClient = Utils.createTestHTTPClient("AlternativeOrders_GetAlternativeOrder");
    SDK sdk =
        SDK.builder()
            .serverURL(Utils.environmentVariable("SERVICE_ACCOUNT_CREDS_URL", ""))
            .security(
                Security.builder()
                    .apiKey(Utils.environmentVariable("API_KEY", ""))
                    .serviceAccountCreds(
                        ServiceAccountCreds.builder()
                            .privateKey(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""))
                            .name(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_NAME", ""))
                            .organization(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""))
                            .type(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_TYPE", ""))
                            .build())
                    .build())
            .client(testHttpClient)
            .build();

    AlternativeOrdersGetAlternativeOrderResponse res =
        sdk.alternativeOrders()
            .getAlternativeOrder()
            .accountId("01JHGTEPC6ZTAHCFRH2MD3VJJT")
            .alternativeOrderId("01KHYEFHKS7VM17YC8BQC6A8PV")
            .call();
    assertEquals(200, res.statusCode());
  }

  @Test
  public void testAlternativeOrders_AlternativeOrdersRetrievePendingInvestorActions()
      throws Exception {

    var testHttpClient =
        Utils.createTestHTTPClient("AlternativeOrders_RetrievePendingInvestorActions");
    SDK sdk =
        SDK.builder()
            .serverURL(Utils.environmentVariable("SERVICE_ACCOUNT_CREDS_URL", ""))
            .security(
                Security.builder()
                    .apiKey(Utils.environmentVariable("API_KEY", ""))
                    .serviceAccountCreds(
                        ServiceAccountCreds.builder()
                            .privateKey(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""))
                            .name(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_NAME", ""))
                            .organization(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""))
                            .type(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_TYPE", ""))
                            .build())
                    .build())
            .client(testHttpClient)
            .build();

    AlternativeOrdersRetrievePendingInvestorActionsResponse res =
        sdk.alternativeOrders()
            .retrievePendingInvestorActions()
            .accountId("01JHGTEPC6ZTAHCFRH2MD3VJJT")
            .alternativeOrderId("01KHYEFHKS7VM17YC8BQC6A8PV")
            .call();
    assertEquals(200, res.statusCode());
  }

  @Test
  public void testAlternativeOrders_AlternativeOrdersSettleAlternativeOrder() throws Exception {

    var testHttpClient = Utils.createTestHTTPClient("AlternativeOrders_SettleAlternativeOrder");
    SDK sdk =
        SDK.builder()
            .serverURL(Utils.environmentVariable("SERVICE_ACCOUNT_CREDS_URL", ""))
            .security(
                Security.builder()
                    .apiKey(Utils.environmentVariable("API_KEY", ""))
                    .serviceAccountCreds(
                        ServiceAccountCreds.builder()
                            .privateKey(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""))
                            .name(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_NAME", ""))
                            .organization(
                                System.getenv()
                                    .getOrDefault("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""))
                            .type(System.getenv().getOrDefault("SERVICE_ACCOUNT_CREDS_TYPE", ""))
                            .build())
                    .build())
            .client(testHttpClient)
            .build();

    AlternativeOrdersSettleAlternativeOrderResponse res =
        sdk.alternativeOrders()
            .settleAlternativeOrder()
            .accountId("01JHGTEPC6ZTAHCFRH2MD3VJJT")
            .alternativeOrderId("01KHYEFHKS7VM17YC8BQC6A8PV")
            .settleAlternativeOrderRequestCreate(
                SettleAlternativeOrderRequestCreate.builder()
                    .name(
                        "accounts/01JHGTEPC6ZTAHCFRH2MD3VJJT/alternativeOrders/01KHYEFHKS7VM17YC8BQC6A8PV")
                    .orderSettlementTarget(OrderSettlementTarget.FILLED)
                    .build())
            .call();
    assertEquals(400, res.statusCode());
  }
}
