/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk;

import com.apexfintechsolutions.ascendsdk.models.components.Account;
import com.apexfintechsolutions.ascendsdk.models.components.AccountRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.errors.SDKError;
import com.apexfintechsolutions.ascendsdk.models.errors.Status;
import com.apexfintechsolutions.ascendsdk.models.operations.AccountsCreateAccountRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.AccountsCreateAccountResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AccountsGetAccountRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.AccountsGetAccountRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.AccountsGetAccountResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.QueryParamView;
import com.apexfintechsolutions.ascendsdk.models.operations.SDKMethodInterfaces.*;
import com.apexfintechsolutions.ascendsdk.utils.HTTPClient;
import com.apexfintechsolutions.ascendsdk.utils.HTTPRequest;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterErrorContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterSuccessContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.BeforeRequestContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.SerializedBody;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.apexfintechsolutions.ascendsdk.utils.Utils.JsonShape;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;

public class AccountCreation
    implements MethodCallAccountsCreateAccount, MethodCallAccountsGetAccount {

  private final SDKConfiguration sdkConfiguration;

  AccountCreation(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  /**
   * Create Account CREATE Creates an account.
   *
   * @return The call builder
   */
  public AccountsCreateAccountRequestBuilder createAccount() {
    return new AccountsCreateAccountRequestBuilder(this);
  }

  /**
   * Create Account CREATE Creates an account.
   *
   * @param request The request object containing all of the parameters for the API call.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AccountsCreateAccountResponse createAccount(AccountRequestCreate request)
      throws Exception {
    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url = Utils.generateURL(_baseUrl, "/accounts/v1/accounts");

    HTTPRequest _req = new HTTPRequest(_url, "POST");
    Object _convertedRequest =
        Utils.convertToShape(
            request, JsonShape.DEFAULT, new TypeReference<AccountRequestCreate>() {});
    SerializedBody _serializedRequestBody =
        Utils.serializeRequestBody(_convertedRequest, "request", "json", false);
    if (_serializedRequestBody == null) {
      throw new Exception("Request body is required");
    }
    _req.setBody(Optional.ofNullable(_serializedRequestBody));
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "Accounts_CreateAccount", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(
          _httpRes.statusCode(), "400", "403", "4XX", "500", "503", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "Accounts_CreateAccount", Optional.of(List.of()), _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "Accounts_CreateAccount", Optional.of(List.of()), _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "Accounts_CreateAccount", Optional.of(List.of()), _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    AccountsCreateAccountResponse.Builder _resBuilder =
        AccountsCreateAccountResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    AccountsCreateAccountResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Account _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Account>() {});
        _res.withAccount(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "500", "503")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }

  /**
   * Get Account READ Get Account
   *
   * @return The call builder
   */
  public AccountsGetAccountRequestBuilder getAccount() {
    return new AccountsGetAccountRequestBuilder(this);
  }

  /**
   * Get Account READ Get Account
   *
   * @param accountId The account id.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AccountsGetAccountResponse getAccount(String accountId) throws Exception {
    return getAccount(accountId, Optional.empty());
  }

  /**
   * Get Account READ Get Account
   *
   * @param accountId The account id.
   * @param view The view to return. Defaults to `FULL`.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AccountsGetAccountResponse getAccount(
      String accountId, Optional<? extends QueryParamView> view) throws Exception {
    AccountsGetAccountRequest request =
        AccountsGetAccountRequest.builder().accountId(accountId).view(view).build();

    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url =
        Utils.generateURL(
            AccountsGetAccountRequest.class,
            _baseUrl,
            "/accounts/v1/accounts/{account_id}",
            request,
            null);

    HTTPRequest _req = new HTTPRequest(_url, "GET");
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    _req.addQueryParams(Utils.getQueryParams(AccountsGetAccountRequest.class, request, null));

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "Accounts_GetAccount", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(
          _httpRes.statusCode(), "400", "403", "404", "4XX", "500", "503", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "Accounts_GetAccount", Optional.of(List.of()), _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "Accounts_GetAccount", Optional.of(List.of()), _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "Accounts_GetAccount", Optional.of(List.of()), _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    AccountsGetAccountResponse.Builder _resBuilder =
        AccountsGetAccountResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    AccountsGetAccountResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Account _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Account>() {});
        _res.withAccount(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "404")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "500", "503")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }
}
