/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.models.components.GenerateServiceAccountTokenRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationGenerateServiceAccountTokenRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationGenerateServiceAccountTokenResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationGenerateServiceAccountTokenSecurity;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationListSigningKeysRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationListSigningKeysRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationListSigningKeysResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.AuthenticationListSigningKeysSecurity;
import com.apexfintechsolutions.ascendsdk.operations.AuthenticationGenerateServiceAccountToken;
import com.apexfintechsolutions.ascendsdk.operations.AuthenticationListSigningKeys;
import com.apexfintechsolutions.ascendsdk.utils.Options;
import java.util.Optional;

public class Authentication {
  private final SDKConfiguration sdkConfiguration;

  Authentication(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  /**
   * Generate Service Account Token
   *
   * <p>Creates an access token for a service account.
   *
   * @return The call builder
   */
  public AuthenticationGenerateServiceAccountTokenRequestBuilder generateServiceAccountToken() {
    return new AuthenticationGenerateServiceAccountTokenRequestBuilder(sdkConfiguration);
  }

  /**
   * Generate Service Account Token
   *
   * <p>Creates an access token for a service account.
   *
   * @param request The request object containing all the parameters for the API call.
   * @param security The security details to use for authentication.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AuthenticationGenerateServiceAccountTokenResponse generateServiceAccountToken(
      GenerateServiceAccountTokenRequestCreate request,
      AuthenticationGenerateServiceAccountTokenSecurity security)
      throws Exception {
    return generateServiceAccountToken(request, security, Optional.empty());
  }

  /**
   * Generate Service Account Token
   *
   * <p>Creates an access token for a service account.
   *
   * @param request The request object containing all the parameters for the API call.
   * @param security The security details to use for authentication.
   * @param options additional options
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AuthenticationGenerateServiceAccountTokenResponse generateServiceAccountToken(
      GenerateServiceAccountTokenRequestCreate request,
      AuthenticationGenerateServiceAccountTokenSecurity security,
      Optional<Options> options)
      throws Exception {
    RequestOperation<
            GenerateServiceAccountTokenRequestCreate,
            AuthenticationGenerateServiceAccountTokenResponse>
        operation =
            new AuthenticationGenerateServiceAccountToken.Sync(sdkConfiguration, security, options);
    return operation.handleResponse(operation.doRequest(request));
  }

  /**
   * List Signing Keys
   *
   * <p>Gets the public signing keys used to verify JSON Web Tokens generated by this service.
   *
   * @return The call builder
   */
  public AuthenticationListSigningKeysRequestBuilder listSigningKeys() {
    return new AuthenticationListSigningKeysRequestBuilder(sdkConfiguration);
  }

  /**
   * List Signing Keys
   *
   * <p>Gets the public signing keys used to verify JSON Web Tokens generated by this service.
   *
   * @param security The security details to use for authentication.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AuthenticationListSigningKeysResponse listSigningKeys(
      AuthenticationListSigningKeysSecurity security) throws Exception {
    return listSigningKeys(security, Optional.empty(), Optional.empty(), Optional.empty());
  }

  /**
   * List Signing Keys
   *
   * <p>Gets the public signing keys used to verify JSON Web Tokens generated by this service.
   *
   * @param security The security details to use for authentication.
   * @param pageSize The number of entries to return in a single page; Default = 100; Maximum = 1000
   * @param pageToken Page token used for pagination; Supplying a page token returns the next page
   *     of results
   * @param options additional options
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public AuthenticationListSigningKeysResponse listSigningKeys(
      AuthenticationListSigningKeysSecurity security,
      Optional<Integer> pageSize,
      Optional<String> pageToken,
      Optional<Options> options)
      throws Exception {
    AuthenticationListSigningKeysRequest request =
        AuthenticationListSigningKeysRequest.builder()
            .pageSize(pageSize)
            .pageToken(pageToken)
            .build();
    RequestOperation<AuthenticationListSigningKeysRequest, AuthenticationListSigningKeysResponse>
        operation = new AuthenticationListSigningKeys.Sync(sdkConfiguration, security, options);
    return operation.handleResponse(operation.doRequest(request));
  }
}
