/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk;

import com.apexfintechsolutions.ascendsdk.models.components.CancelCashJournalRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.components.CashJournal;
import com.apexfintechsolutions.ascendsdk.models.components.CashJournalConstraints;
import com.apexfintechsolutions.ascendsdk.models.components.CashJournalCreate;
import com.apexfintechsolutions.ascendsdk.models.components.CheckPartyTypeRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.components.CheckPartyTypeResponse;
import com.apexfintechsolutions.ascendsdk.models.components.RetrieveCashJournalConstraintsRequestCreate;
import com.apexfintechsolutions.ascendsdk.models.errors.SDKError;
import com.apexfintechsolutions.ascendsdk.models.errors.Status;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCancelCashJournalRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCancelCashJournalRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCancelCashJournalResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCheckPartyTypeRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCheckPartyTypeResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCreateCashJournalRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsCreateCashJournalResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsGetCashJournalRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsGetCashJournalRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.CashJournalsGetCashJournalResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.RetirementConstraintsRetrieveCashJournalConstraintsRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.RetirementConstraintsRetrieveCashJournalConstraintsResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.SDKMethodInterfaces.*;
import com.apexfintechsolutions.ascendsdk.utils.HTTPClient;
import com.apexfintechsolutions.ascendsdk.utils.HTTPRequest;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterErrorContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterSuccessContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.BeforeRequestContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.SerializedBody;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.apexfintechsolutions.ascendsdk.utils.Utils.JsonShape;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;

public class Journals
    implements MethodCallRetirementConstraintsRetrieveCashJournalConstraints,
        MethodCallCashJournalsCreateCashJournal,
        MethodCallCashJournalsGetCashJournal,
        MethodCallCashJournalsCancelCashJournal,
        MethodCallCashJournalsCheckPartyType {

  private final SDKConfiguration sdkConfiguration;

  Journals(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  /**
   * Retrieve Cash Journal Constraints Retrieves retirement contribution and distribution
   * constraints for a cash journal transfer
   *
   * @return The call builder
   */
  public RetirementConstraintsRetrieveCashJournalConstraintsRequestBuilder
      retrieveCashJournalConstraints() {
    return new RetirementConstraintsRetrieveCashJournalConstraintsRequestBuilder(this);
  }

  /**
   * Retrieve Cash Journal Constraints Retrieves retirement contribution and distribution
   * constraints for a cash journal transfer
   *
   * @param request The request object containing all of the parameters for the API call.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public RetirementConstraintsRetrieveCashJournalConstraintsResponse retrieveCashJournalConstraints(
      RetrieveCashJournalConstraintsRequestCreate request) throws Exception {
    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url =
        Utils.generateURL(_baseUrl, "/transfers/v1/cashJournals:retrieveCashJournalConstraints");

    HTTPRequest _req = new HTTPRequest(_url, "POST");
    Object _convertedRequest =
        Utils.convertToShape(
            request,
            JsonShape.DEFAULT,
            new TypeReference<RetrieveCashJournalConstraintsRequestCreate>() {});
    SerializedBody _serializedRequestBody =
        Utils.serializeRequestBody(_convertedRequest, "request", "json", false);
    if (_serializedRequestBody == null) {
      throw new Exception("Request body is required");
    }
    _req.setBody(Optional.ofNullable(_serializedRequestBody));
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "RetirementConstraints_RetrieveCashJournalConstraints",
                    Optional.of(List.of()),
                    _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "4XX", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "RetirementConstraints_RetrieveCashJournalConstraints",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "RetirementConstraints_RetrieveCashJournalConstraints",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "RetirementConstraints_RetrieveCashJournalConstraints",
                      Optional.of(List.of()),
                      _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    RetirementConstraintsRetrieveCashJournalConstraintsResponse.Builder _resBuilder =
        RetirementConstraintsRetrieveCashJournalConstraintsResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    RetirementConstraintsRetrieveCashJournalConstraintsResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        CashJournalConstraints _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<CashJournalConstraints>() {});
        _res.withCashJournalConstraints(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }

  /**
   * Create Cash Journal Creates a cash journal
   *
   * @return The call builder
   */
  public CashJournalsCreateCashJournalRequestBuilder createCashJournal() {
    return new CashJournalsCreateCashJournalRequestBuilder(this);
  }

  /**
   * Create Cash Journal Creates a cash journal
   *
   * @param request The request object containing all of the parameters for the API call.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public CashJournalsCreateCashJournalResponse createCashJournal(CashJournalCreate request)
      throws Exception {
    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url = Utils.generateURL(_baseUrl, "/transfers/v1/cashJournals");

    HTTPRequest _req = new HTTPRequest(_url, "POST");
    Object _convertedRequest =
        Utils.convertToShape(request, JsonShape.DEFAULT, new TypeReference<CashJournalCreate>() {});
    SerializedBody _serializedRequestBody =
        Utils.serializeRequestBody(_convertedRequest, "request", "json", false);
    if (_serializedRequestBody == null) {
      throw new Exception("Request body is required");
    }
    _req.setBody(Optional.ofNullable(_serializedRequestBody));
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "CashJournals_CreateCashJournal", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "409", "4XX", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "CashJournals_CreateCashJournal",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "CashJournals_CreateCashJournal",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "CashJournals_CreateCashJournal",
                      Optional.of(List.of()),
                      _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    CashJournalsCreateCashJournalResponse.Builder _resBuilder =
        CashJournalsCreateCashJournalResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    CashJournalsCreateCashJournalResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        CashJournal _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<CashJournal>() {});
        _res.withCashJournal(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "409")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }

  /**
   * Get Cash Journal Gets an existing cash journal
   *
   * @return The call builder
   */
  public CashJournalsGetCashJournalRequestBuilder getCashJournal() {
    return new CashJournalsGetCashJournalRequestBuilder(this);
  }

  /**
   * Get Cash Journal Gets an existing cash journal
   *
   * @param cashJournalId The cashJournal id.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public CashJournalsGetCashJournalResponse getCashJournal(String cashJournalId) throws Exception {
    CashJournalsGetCashJournalRequest request =
        CashJournalsGetCashJournalRequest.builder().cashJournalId(cashJournalId).build();

    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url =
        Utils.generateURL(
            CashJournalsGetCashJournalRequest.class,
            _baseUrl,
            "/transfers/v1/cashJournals/{cashJournal_id}",
            request,
            null);

    HTTPRequest _req = new HTTPRequest(_url, "GET");
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "CashJournals_GetCashJournal", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "4XX", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "CashJournals_GetCashJournal", Optional.of(List.of()), _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "CashJournals_GetCashJournal", Optional.of(List.of()), _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "CashJournals_GetCashJournal", Optional.of(List.of()), _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    CashJournalsGetCashJournalResponse.Builder _resBuilder =
        CashJournalsGetCashJournalResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    CashJournalsGetCashJournalResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        CashJournal _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<CashJournal>() {});
        _res.withCashJournal(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }

  /**
   * Cancel Cash Journal Cancels an existing cash journal
   *
   * @return The call builder
   */
  public CashJournalsCancelCashJournalRequestBuilder cancelCashJournal() {
    return new CashJournalsCancelCashJournalRequestBuilder(this);
  }

  /**
   * Cancel Cash Journal Cancels an existing cash journal
   *
   * @param cashJournalId The cashJournal id.
   * @param cancelCashJournalRequestCreate Request to cancel an existing cash journal
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public CashJournalsCancelCashJournalResponse cancelCashJournal(
      String cashJournalId, CancelCashJournalRequestCreate cancelCashJournalRequestCreate)
      throws Exception {
    CashJournalsCancelCashJournalRequest request =
        CashJournalsCancelCashJournalRequest.builder()
            .cashJournalId(cashJournalId)
            .cancelCashJournalRequestCreate(cancelCashJournalRequestCreate)
            .build();

    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url =
        Utils.generateURL(
            CashJournalsCancelCashJournalRequest.class,
            _baseUrl,
            "/transfers/v1/cashJournals/{cashJournal_id}:cancel",
            request,
            null);

    HTTPRequest _req = new HTTPRequest(_url, "POST");
    Object _convertedRequest =
        Utils.convertToShape(request, JsonShape.DEFAULT, new TypeReference<Object>() {});
    SerializedBody _serializedRequestBody =
        Utils.serializeRequestBody(
            _convertedRequest, "cancelCashJournalRequestCreate", "json", false);
    if (_serializedRequestBody == null) {
      throw new Exception("Request body is required");
    }
    _req.setBody(Optional.ofNullable(_serializedRequestBody));
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "CashJournals_CancelCashJournal", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "4XX", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "CashJournals_CancelCashJournal",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "CashJournals_CancelCashJournal",
                        Optional.of(List.of()),
                        _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "CashJournals_CancelCashJournal",
                      Optional.of(List.of()),
                      _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    CashJournalsCancelCashJournalResponse.Builder _resBuilder =
        CashJournalsCancelCashJournalResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    CashJournalsCancelCashJournalResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        CashJournal _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<CashJournal>() {});
        _res.withCashJournal(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }

  /**
   * Retrieve Cash Journal Party Determines whether a potential cash journal will be considered
   * first party or third party given a source and destination account
   *
   * @return The call builder
   */
  public CashJournalsCheckPartyTypeRequestBuilder checkPartyType() {
    return new CashJournalsCheckPartyTypeRequestBuilder(this);
  }

  /**
   * Retrieve Cash Journal Party Determines whether a potential cash journal will be considered
   * first party or third party given a source and destination account
   *
   * @param request The request object containing all of the parameters for the API call.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public CashJournalsCheckPartyTypeResponse checkPartyType(CheckPartyTypeRequestCreate request)
      throws Exception {
    String _baseUrl = this.sdkConfiguration.serverUrl;
    String _url = Utils.generateURL(_baseUrl, "/transfers/v1/cashJournals:checkPartyType");

    HTTPRequest _req = new HTTPRequest(_url, "POST");
    Object _convertedRequest =
        Utils.convertToShape(
            request, JsonShape.DEFAULT, new TypeReference<CheckPartyTypeRequestCreate>() {});
    SerializedBody _serializedRequestBody =
        Utils.serializeRequestBody(_convertedRequest, "request", "json", false);
    if (_serializedRequestBody == null) {
      throw new Exception("Request body is required");
    }
    _req.setBody(Optional.ofNullable(_serializedRequestBody));
    _req.addHeader("Accept", "application/json")
        .addHeader("user-agent", SDKConfiguration.USER_AGENT);

    Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
    Utils.configureSecurity(_req, this.sdkConfiguration.securitySource.getSecurity());
    HTTPClient _client = this.sdkConfiguration.defaultClient;
    HttpRequest _r =
        sdkConfiguration
            .hooks()
            .beforeRequest(
                new BeforeRequestContextImpl(
                    "CashJournals_CheckPartyType", Optional.of(List.of()), _hookSecuritySource),
                _req.build());
    HttpResponse<InputStream> _httpRes;
    try {
      _httpRes = _client.send(_r);
      if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403", "4XX", "5XX")) {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterError(
                    new AfterErrorContextImpl(
                        "CashJournals_CheckPartyType", Optional.of(List.of()), _hookSecuritySource),
                    Optional.of(_httpRes),
                    Optional.empty());
      } else {
        _httpRes =
            sdkConfiguration
                .hooks()
                .afterSuccess(
                    new AfterSuccessContextImpl(
                        "CashJournals_CheckPartyType", Optional.of(List.of()), _hookSecuritySource),
                    _httpRes);
      }
    } catch (Exception _e) {
      _httpRes =
          sdkConfiguration
              .hooks()
              .afterError(
                  new AfterErrorContextImpl(
                      "CashJournals_CheckPartyType", Optional.of(List.of()), _hookSecuritySource),
                  Optional.empty(),
                  Optional.of(_e));
    }
    String _contentType =
        _httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");
    CashJournalsCheckPartyTypeResponse.Builder _resBuilder =
        CashJournalsCheckPartyTypeResponse.builder()
            .contentType(_contentType)
            .statusCode(_httpRes.statusCode())
            .rawResponse(_httpRes);

    CashJournalsCheckPartyTypeResponse _res = _resBuilder.build();

    if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        CheckPartyTypeResponse _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<CheckPartyTypeResponse>() {});
        _res.withCheckPartyTypeResponse(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "403")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        Status _out =
            Utils.mapper()
                .readValue(Utils.toUtf8AndClose(_httpRes.body()), new TypeReference<Status>() {});
        throw _out;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "5XX")) {
      // no content
      throw new SDKError(
          _httpRes,
          _httpRes.statusCode(),
          "API error occurred",
          Utils.extractByteArrayFromBody(_httpRes));
    }
    if (Utils.statusCodeMatches(_httpRes.statusCode(), "default")) {
      if (Utils.contentTypeMatches(_contentType, "application/json")) {
        com.apexfintechsolutions.ascendsdk.models.components.Status _out =
            Utils.mapper()
                .readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<
                        com.apexfintechsolutions.ascendsdk.models.components.Status>() {});
        _res.withStatus(Optional.ofNullable(_out));
        return _res;
      } else {
        throw new SDKError(
            _httpRes,
            _httpRes.statusCode(),
            "Unexpected content-type received: " + _contentType,
            Utils.extractByteArrayFromBody(_httpRes));
      }
    }
    throw new SDKError(
        _httpRes,
        _httpRes.statusCode(),
        "Unexpected status code received: " + _httpRes.statusCode(),
        Utils.extractByteArrayFromBody(_httpRes));
  }
}
