/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.models.operations.ReaderGetEventMessageRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.ReaderGetEventMessageRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.ReaderGetEventMessageResponse;
import com.apexfintechsolutions.ascendsdk.models.operations.ReaderListEventMessagesRequest;
import com.apexfintechsolutions.ascendsdk.models.operations.ReaderListEventMessagesRequestBuilder;
import com.apexfintechsolutions.ascendsdk.models.operations.ReaderListEventMessagesResponse;
import com.apexfintechsolutions.ascendsdk.operations.ReaderGetEventMessage;
import com.apexfintechsolutions.ascendsdk.operations.ReaderListEventMessages;
import java.util.Optional;

public class Reader {
  private final SDKConfiguration sdkConfiguration;

  Reader(SDKConfiguration sdkConfiguration) {
    this.sdkConfiguration = sdkConfiguration;
  }

  /**
   * List Event Messages
   *
   * <p>Gets a list of events.
   *
   * @return The call builder
   */
  public ReaderListEventMessagesRequestBuilder listEventMessages() {
    return new ReaderListEventMessagesRequestBuilder(sdkConfiguration);
  }

  /**
   * List Event Messages
   *
   * <p>Gets a list of events.
   *
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public ReaderListEventMessagesResponse listEventMessagesDirect() throws Exception {
    return listEventMessages(Optional.empty(), Optional.empty(), Optional.empty());
  }

  /**
   * List Event Messages
   *
   * <p>Gets a list of events.
   *
   * @param filter A CEL string to filter results; See the [CEL
   *     Search](https://developer.apexclearing.com/apex-fintech-solutions/docs/cel-search) page in
   *     Guides for more information; If left empty, all events the user has permission to view are
   *     returned; Filter options include: `name` `message_id` `event_type` `publish_time`
   *     `partition_key` `client_id` `correspondent_id` `account_id`
   * @param pageSize The number of entries to return in a single page; Default = 100; Maximum = 1000
   * @param pageToken Page token used for pagination; Supplying a page token returns the next page
   *     of results
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public ReaderListEventMessagesResponse listEventMessages(
      Optional<String> filter, Optional<Integer> pageSize, Optional<String> pageToken)
      throws Exception {
    ReaderListEventMessagesRequest request =
        ReaderListEventMessagesRequest.builder()
            .filter(filter)
            .pageSize(pageSize)
            .pageToken(pageToken)
            .build();
    RequestOperation<ReaderListEventMessagesRequest, ReaderListEventMessagesResponse> operation =
        new ReaderListEventMessages.Sync(sdkConfiguration);
    return operation.handleResponse(operation.doRequest(request));
  }

  /**
   * Get Event Message
   *
   * <p>Gets the details of a specific event.
   *
   * @return The call builder
   */
  public ReaderGetEventMessageRequestBuilder getEventMessage() {
    return new ReaderGetEventMessageRequestBuilder(sdkConfiguration);
  }

  /**
   * Get Event Message
   *
   * <p>Gets the details of a specific event.
   *
   * @param messageId The message id.
   * @return The response from the API call
   * @throws Exception if the API call fails
   */
  public ReaderGetEventMessageResponse getEventMessage(String messageId) throws Exception {
    ReaderGetEventMessageRequest request =
        ReaderGetEventMessageRequest.builder().messageId(messageId).build();
    RequestOperation<ReaderGetEventMessageRequest, ReaderGetEventMessageResponse> operation =
        new ReaderGetEventMessage.Sync(sdkConfiguration);
    return operation.handleResponse(operation.doRequest(request));
  }
}
