/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.operations;

import static com.apexfintechsolutions.ascendsdk.operations.Operations.RequestOperation;

import com.apexfintechsolutions.ascendsdk.SDKConfiguration;
import com.apexfintechsolutions.ascendsdk.SecuritySource;
import com.apexfintechsolutions.ascendsdk.models.components.ListAssetsResponse;
import com.apexfintechsolutions.ascendsdk.models.errors.SDKError;
import com.apexfintechsolutions.ascendsdk.models.errors.Status;
import com.apexfintechsolutions.ascendsdk.models.operations.AssetsListAssets1Request;
import com.apexfintechsolutions.ascendsdk.models.operations.AssetsListAssets1Response;
import com.apexfintechsolutions.ascendsdk.utils.HTTPClient;
import com.apexfintechsolutions.ascendsdk.utils.HTTPRequest;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterErrorContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.AfterSuccessContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Hook.BeforeRequestContextImpl;
import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Optional;

public class AssetsListAssets1 {

  abstract static class Base {
    final SDKConfiguration sdkConfiguration;
    final String baseUrl;
    final SecuritySource securitySource;
    final HTTPClient client;

    public Base(SDKConfiguration sdkConfiguration) {
      this.sdkConfiguration = sdkConfiguration;
      this.baseUrl = this.sdkConfiguration.serverUrl();
      this.securitySource = this.sdkConfiguration.securitySource();
      this.client = this.sdkConfiguration.client();
    }

    Optional<SecuritySource> securitySource() {
      return Optional.ofNullable(this.securitySource);
    }

    HttpRequest buildRequest(AssetsListAssets1Request request) throws Exception {
      String url = Utils.generateURL(this.baseUrl, "/assets/v1/assets");
      HTTPRequest req = new HTTPRequest(url, "GET");
      req.addHeader("Accept", "application/json")
          .addHeader("user-agent", SDKConfiguration.USER_AGENT);

      req.addQueryParams(Utils.getQueryParams(AssetsListAssets1Request.class, request, null));
      Utils.configureSecurity(req, this.sdkConfiguration.securitySource().getSecurity());

      return sdkConfiguration
          .hooks()
          .beforeRequest(
              new BeforeRequestContextImpl(
                  this.sdkConfiguration,
                  this.baseUrl,
                  "Assets_ListAssets_1",
                  java.util.Optional.of(java.util.List.of()),
                  securitySource()),
              req.build());
    }
  }

  public static class Sync extends Base
      implements RequestOperation<AssetsListAssets1Request, AssetsListAssets1Response> {
    public Sync(SDKConfiguration sdkConfiguration) {
      super(sdkConfiguration);
    }

    private HttpResponse<InputStream> onError(HttpResponse<InputStream> response, Exception error)
        throws Exception {
      return sdkConfiguration
          .hooks()
          .afterError(
              new AfterErrorContextImpl(
                  this.sdkConfiguration,
                  this.baseUrl,
                  "Assets_ListAssets_1",
                  java.util.Optional.of(java.util.List.of()),
                  securitySource()),
              Optional.ofNullable(response),
              Optional.ofNullable(error));
    }

    private HttpResponse<InputStream> onSuccess(HttpResponse<InputStream> response)
        throws Exception {
      return sdkConfiguration
          .hooks()
          .afterSuccess(
              new AfterSuccessContextImpl(
                  this.sdkConfiguration,
                  this.baseUrl,
                  "Assets_ListAssets_1",
                  java.util.Optional.of(java.util.List.of()),
                  securitySource()),
              response);
    }

    @Override
    public HttpResponse<InputStream> doRequest(AssetsListAssets1Request request) throws Exception {
      HttpRequest r = buildRequest(request);
      HttpResponse<InputStream> httpRes;
      try {
        httpRes = client.send(r);
        if (Utils.statusCodeMatches(
            httpRes.statusCode(), "400", "403", "404", "4XX", "500", "503", "504", "5XX")) {
          httpRes = onError(httpRes, null);
        } else {
          httpRes = onSuccess(httpRes);
        }
      } catch (Exception e) {
        httpRes = onError(null, e);
      }

      return httpRes;
    }

    @Override
    public AssetsListAssets1Response handleResponse(HttpResponse<InputStream> response)
        throws Exception {
      String contentType =
          response.headers().firstValue("Content-Type").orElse("application/octet-stream");
      AssetsListAssets1Response.Builder resBuilder =
          AssetsListAssets1Response.builder()
              .contentType(contentType)
              .statusCode(response.statusCode())
              .rawResponse(response);

      AssetsListAssets1Response res = resBuilder.build();

      if (Utils.statusCodeMatches(response.statusCode(), "200")) {
        if (Utils.contentTypeMatches(contentType, "application/json")) {
          ListAssetsResponse out =
              Utils.mapper().readValue(response.body(), new TypeReference<>() {});
          res.withListAssetsResponse(out);
          return res;
        } else {
          throw new SDKError(
              response,
              response.statusCode(),
              "Unexpected content-type received: " + contentType,
              Utils.extractByteArrayFromBody(response));
        }
      }

      if (Utils.statusCodeMatches(response.statusCode(), "400", "403", "404")) {
        if (Utils.contentTypeMatches(contentType, "application/json")) {
          Status out = Utils.mapper().readValue(response.body(), new TypeReference<>() {});
          throw out;
        } else {
          throw new SDKError(
              response,
              response.statusCode(),
              "Unexpected content-type received: " + contentType,
              Utils.extractByteArrayFromBody(response));
        }
      }

      if (Utils.statusCodeMatches(response.statusCode(), "500", "503", "504")) {
        if (Utils.contentTypeMatches(contentType, "application/json")) {
          Status out = Utils.mapper().readValue(response.body(), new TypeReference<>() {});
          throw out;
        } else {
          throw new SDKError(
              response,
              response.statusCode(),
              "Unexpected content-type received: " + contentType,
              Utils.extractByteArrayFromBody(response));
        }
      }

      if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
        // no content
        throw new SDKError(
            response,
            response.statusCode(),
            "API error occurred",
            Utils.extractByteArrayFromBody(response));
      }

      if (Utils.statusCodeMatches(response.statusCode(), "5XX")) {
        // no content
        throw new SDKError(
            response,
            response.statusCode(),
            "API error occurred",
            Utils.extractByteArrayFromBody(response));
      }

      if (Utils.statusCodeMatches(response.statusCode(), "default")) {
        if (Utils.contentTypeMatches(contentType, "application/json")) {
          com.apexfintechsolutions.ascendsdk.models.components.Status out =
              Utils.mapper().readValue(response.body(), new TypeReference<>() {});
          res.withStatus(out);
          return res;
        } else {
          throw new SDKError(
              response,
              response.statusCode(),
              "Unexpected content-type received: " + contentType,
              Utils.extractByteArrayFromBody(response));
        }
      }

      throw new SDKError(
          response,
          response.statusCode(),
          "Unexpected status code received: " + response.statusCode(),
          Utils.extractByteArrayFromBody(response));
    }
  }
}
