/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * ActivityAcatsPendingOut
 *
 * <p>Used to record the movement of funds or shares to/ from the pending_acats memo location
 */
public class ActivityAcatsPendingOut {
  /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("acats_control_number")
  private Optional<String> acatsControlNumber;

  /** Free form text field containing additional information about a transaction */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("additional_instructions")
  private Optional<String> additionalInstructions;

  @JsonCreator
  public ActivityAcatsPendingOut(
      @JsonProperty("acats_control_number") Optional<String> acatsControlNumber,
      @JsonProperty("additional_instructions") Optional<String> additionalInstructions) {
    Utils.checkNotNull(acatsControlNumber, "acatsControlNumber");
    Utils.checkNotNull(additionalInstructions, "additionalInstructions");
    this.acatsControlNumber = acatsControlNumber;
    this.additionalInstructions = additionalInstructions;
  }

  public ActivityAcatsPendingOut() {
    this(Optional.empty(), Optional.empty());
  }

  /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
  @JsonIgnore
  public Optional<String> acatsControlNumber() {
    return acatsControlNumber;
  }

  /** Free form text field containing additional information about a transaction */
  @JsonIgnore
  public Optional<String> additionalInstructions() {
    return additionalInstructions;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
  public ActivityAcatsPendingOut withAcatsControlNumber(String acatsControlNumber) {
    Utils.checkNotNull(acatsControlNumber, "acatsControlNumber");
    this.acatsControlNumber = Optional.ofNullable(acatsControlNumber);
    return this;
  }

  /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
  public ActivityAcatsPendingOut withAcatsControlNumber(Optional<String> acatsControlNumber) {
    Utils.checkNotNull(acatsControlNumber, "acatsControlNumber");
    this.acatsControlNumber = acatsControlNumber;
    return this;
  }

  /** Free form text field containing additional information about a transaction */
  public ActivityAcatsPendingOut withAdditionalInstructions(String additionalInstructions) {
    Utils.checkNotNull(additionalInstructions, "additionalInstructions");
    this.additionalInstructions = Optional.ofNullable(additionalInstructions);
    return this;
  }

  /** Free form text field containing additional information about a transaction */
  public ActivityAcatsPendingOut withAdditionalInstructions(
      Optional<String> additionalInstructions) {
    Utils.checkNotNull(additionalInstructions, "additionalInstructions");
    this.additionalInstructions = additionalInstructions;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityAcatsPendingOut other = (ActivityAcatsPendingOut) o;
    return Utils.enhancedDeepEquals(this.acatsControlNumber, other.acatsControlNumber)
        && Utils.enhancedDeepEquals(this.additionalInstructions, other.additionalInstructions);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(acatsControlNumber, additionalInstructions);
  }

  @Override
  public String toString() {
    return Utils.toString(
        ActivityAcatsPendingOut.class,
        "acatsControlNumber",
        acatsControlNumber,
        "additionalInstructions",
        additionalInstructions);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<String> acatsControlNumber = Optional.empty();

    private Optional<String> additionalInstructions = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
    public Builder acatsControlNumber(String acatsControlNumber) {
      Utils.checkNotNull(acatsControlNumber, "acatsControlNumber");
      this.acatsControlNumber = Optional.ofNullable(acatsControlNumber);
      return this;
    }

    /** Unique Identifier generated by the NSCC ACATS when a transfer is initiated or submitted */
    public Builder acatsControlNumber(Optional<String> acatsControlNumber) {
      Utils.checkNotNull(acatsControlNumber, "acatsControlNumber");
      this.acatsControlNumber = acatsControlNumber;
      return this;
    }

    /** Free form text field containing additional information about a transaction */
    public Builder additionalInstructions(String additionalInstructions) {
      Utils.checkNotNull(additionalInstructions, "additionalInstructions");
      this.additionalInstructions = Optional.ofNullable(additionalInstructions);
      return this;
    }

    /** Free form text field containing additional information about a transaction */
    public Builder additionalInstructions(Optional<String> additionalInstructions) {
      Utils.checkNotNull(additionalInstructions, "additionalInstructions");
      this.additionalInstructions = additionalInstructions;
      return this;
    }

    public ActivityAcatsPendingOut build() {

      return new ActivityAcatsPendingOut(acatsControlNumber, additionalInstructions);
    }
  }
}
