/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/** ActivityAction - Denotes whether the shares are incoming or outgoing */
@JsonDeserialize(using = ActivityAction._Deserializer.class)
@JsonSerialize(using = ActivityAction._Serializer.class)
public class ActivityAction {

  public static final ActivityAction ACTION_UNSPECIFIED = new ActivityAction("ACTION_UNSPECIFIED");
  public static final ActivityAction INCOMING = new ActivityAction("INCOMING");
  public static final ActivityAction OUTGOING = new ActivityAction("OUTGOING");
  public static final ActivityAction CASH_IN_LIEU = new ActivityAction("CASH_IN_LIEU");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, ActivityAction> values = createValuesMap();
  private static final Map<String, ActivityActionEnum> enums = createEnumsMap();

  private final String value;

  private ActivityAction(String value) {
    this.value = value;
  }

  /**
   * Returns a ActivityAction with the given value. For a specific value the returned object will
   * always be a singleton so reference equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as ActivityAction
   */
  public static ActivityAction of(String value) {
    synchronized (ActivityAction.class) {
      return values.computeIfAbsent(value, v -> new ActivityAction(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<ActivityActionEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    ActivityAction other = (ActivityAction) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "ActivityAction [value=" + value + "]";
  }

  // return an array just like an enum
  public static ActivityAction[] values() {
    synchronized (ActivityAction.class) {
      return values.values().toArray(new ActivityAction[] {});
    }
  }

  private static final Map<String, ActivityAction> createValuesMap() {
    Map<String, ActivityAction> map = new LinkedHashMap<>();
    map.put("ACTION_UNSPECIFIED", ACTION_UNSPECIFIED);
    map.put("INCOMING", INCOMING);
    map.put("OUTGOING", OUTGOING);
    map.put("CASH_IN_LIEU", CASH_IN_LIEU);
    return map;
  }

  private static final Map<String, ActivityActionEnum> createEnumsMap() {
    Map<String, ActivityActionEnum> map = new HashMap<>();
    map.put("ACTION_UNSPECIFIED", ActivityActionEnum.ACTION_UNSPECIFIED);
    map.put("INCOMING", ActivityActionEnum.INCOMING);
    map.put("OUTGOING", ActivityActionEnum.OUTGOING);
    map.put("CASH_IN_LIEU", ActivityActionEnum.CASH_IN_LIEU);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<ActivityAction> {

    protected _Serializer() {
      super(ActivityAction.class);
    }

    @Override
    public void serialize(ActivityAction value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<ActivityAction> {

    protected _Deserializer() {
      super(ActivityAction.class);
    }

    @Override
    public ActivityAction deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return ActivityAction.of(v);
    }
  }

  public enum ActivityActionEnum {
    ACTION_UNSPECIFIED("ACTION_UNSPECIFIED"),
    INCOMING("INCOMING"),
    OUTGOING("OUTGOING"),
    CASH_IN_LIEU("CASH_IN_LIEU"),
    ;

    private final String value;

    private ActivityActionEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
