/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** AddPartyRequestCreate - A request to add a party to an account */
public class AddPartyRequestCreate {

  /**
   * A list of Party IDs on the account that have approved the addition of a party. The required
   * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
   * require one signer, Joint Registrations require all Joint Owners to sign
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("authorized_by_party_ids")
  private Optional<? extends List<String>> authorizedByPartyIds;

  /**
   * The parent, which is the account to which the party is being added Format:
   * accounts/{account}/parties
   */
  @JsonProperty("parent")
  private String parent;

  /**
   * A single record representing an owner or manager of an Account. Contains fully populated Party
   * Identity object.
   */
  @JsonProperty("party")
  private PartyRequestCreate party;

  @JsonCreator
  public AddPartyRequestCreate(
      @JsonProperty("authorized_by_party_ids")
          Optional<? extends List<String>> authorizedByPartyIds,
      @JsonProperty("parent") String parent,
      @JsonProperty("party") PartyRequestCreate party) {
    Utils.checkNotNull(authorizedByPartyIds, "authorizedByPartyIds");
    Utils.checkNotNull(parent, "parent");
    Utils.checkNotNull(party, "party");
    this.authorizedByPartyIds = authorizedByPartyIds;
    this.parent = parent;
    this.party = party;
  }

  public AddPartyRequestCreate(String parent, PartyRequestCreate party) {
    this(Optional.empty(), parent, party);
  }

  /**
   * A list of Party IDs on the account that have approved the addition of a party. The required
   * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
   * require one signer, Joint Registrations require all Joint Owners to sign
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> authorizedByPartyIds() {
    return (Optional<List<String>>) authorizedByPartyIds;
  }

  /**
   * The parent, which is the account to which the party is being added Format:
   * accounts/{account}/parties
   */
  @JsonIgnore
  public String parent() {
    return parent;
  }

  /**
   * A single record representing an owner or manager of an Account. Contains fully populated Party
   * Identity object.
   */
  @JsonIgnore
  public PartyRequestCreate party() {
    return party;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /**
   * A list of Party IDs on the account that have approved the addition of a party. The required
   * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
   * require one signer, Joint Registrations require all Joint Owners to sign
   */
  public AddPartyRequestCreate withAuthorizedByPartyIds(List<String> authorizedByPartyIds) {
    Utils.checkNotNull(authorizedByPartyIds, "authorizedByPartyIds");
    this.authorizedByPartyIds = Optional.ofNullable(authorizedByPartyIds);
    return this;
  }

  /**
   * A list of Party IDs on the account that have approved the addition of a party. The required
   * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
   * require one signer, Joint Registrations require all Joint Owners to sign
   */
  public AddPartyRequestCreate withAuthorizedByPartyIds(
      Optional<? extends List<String>> authorizedByPartyIds) {
    Utils.checkNotNull(authorizedByPartyIds, "authorizedByPartyIds");
    this.authorizedByPartyIds = authorizedByPartyIds;
    return this;
  }

  /**
   * The parent, which is the account to which the party is being added Format:
   * accounts/{account}/parties
   */
  public AddPartyRequestCreate withParent(String parent) {
    Utils.checkNotNull(parent, "parent");
    this.parent = parent;
    return this;
  }

  /**
   * A single record representing an owner or manager of an Account. Contains fully populated Party
   * Identity object.
   */
  public AddPartyRequestCreate withParty(PartyRequestCreate party) {
    Utils.checkNotNull(party, "party");
    this.party = party;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddPartyRequestCreate other = (AddPartyRequestCreate) o;
    return Objects.deepEquals(this.authorizedByPartyIds, other.authorizedByPartyIds)
        && Objects.deepEquals(this.parent, other.parent)
        && Objects.deepEquals(this.party, other.party);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizedByPartyIds, parent, party);
  }

  @Override
  public String toString() {
    return Utils.toString(
        AddPartyRequestCreate.class,
        "authorizedByPartyIds",
        authorizedByPartyIds,
        "parent",
        parent,
        "party",
        party);
  }

  public static final class Builder {

    private Optional<? extends List<String>> authorizedByPartyIds = Optional.empty();

    private String parent;

    private PartyRequestCreate party;

    private Builder() {
      // force use of static builder() method
    }

    /**
     * A list of Party IDs on the account that have approved the addition of a party. The required
     * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
     * require one signer, Joint Registrations require all Joint Owners to sign
     */
    public Builder authorizedByPartyIds(List<String> authorizedByPartyIds) {
      Utils.checkNotNull(authorizedByPartyIds, "authorizedByPartyIds");
      this.authorizedByPartyIds = Optional.ofNullable(authorizedByPartyIds);
      return this;
    }

    /**
     * A list of Party IDs on the account that have approved the addition of a party. The required
     * signers are defined by the Registration Type of the Account. e.g. Individual Registrations
     * require one signer, Joint Registrations require all Joint Owners to sign
     */
    public Builder authorizedByPartyIds(Optional<? extends List<String>> authorizedByPartyIds) {
      Utils.checkNotNull(authorizedByPartyIds, "authorizedByPartyIds");
      this.authorizedByPartyIds = authorizedByPartyIds;
      return this;
    }

    /**
     * The parent, which is the account to which the party is being added Format:
     * accounts/{account}/parties
     */
    public Builder parent(String parent) {
      Utils.checkNotNull(parent, "parent");
      this.parent = parent;
      return this;
    }

    /**
     * A single record representing an owner or manager of an Account. Contains fully populated
     * Party Identity object.
     */
    public Builder party(PartyRequestCreate party) {
      Utils.checkNotNull(party, "party");
      this.party = party;
      return this;
    }

    public AddPartyRequestCreate build() {
      return new AddPartyRequestCreate(authorizedByPartyIds, parent, party);
    }
  }
}
