/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import java.util.Optional;

/** AddressDetail - Address detail used for Dow Jones Profile details */
public class AddressDetail {

  /** Dow Jones persons address city */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("address_city")
  private Optional<String> addressCity;

  /** Dow Jones persons address line */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("address_line")
  private Optional<String> addressLine;

  /** Dow Jones persons address administrative area */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("administrative_area")
  private Optional<String> administrativeArea;

  /** Dow Jones persons address postal code */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("postal_code")
  private Optional<String> postalCode;

  /**
   * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
   * "CA"
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("region_code")
  private Optional<String> regionCode;

  @JsonCreator
  public AddressDetail(
      @JsonProperty("address_city") Optional<String> addressCity,
      @JsonProperty("address_line") Optional<String> addressLine,
      @JsonProperty("administrative_area") Optional<String> administrativeArea,
      @JsonProperty("postal_code") Optional<String> postalCode,
      @JsonProperty("region_code") Optional<String> regionCode) {
    Utils.checkNotNull(addressCity, "addressCity");
    Utils.checkNotNull(addressLine, "addressLine");
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    Utils.checkNotNull(postalCode, "postalCode");
    Utils.checkNotNull(regionCode, "regionCode");
    this.addressCity = addressCity;
    this.addressLine = addressLine;
    this.administrativeArea = administrativeArea;
    this.postalCode = postalCode;
    this.regionCode = regionCode;
  }

  public AddressDetail() {
    this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
  }

  /** Dow Jones persons address city */
  @JsonIgnore
  public Optional<String> addressCity() {
    return addressCity;
  }

  /** Dow Jones persons address line */
  @JsonIgnore
  public Optional<String> addressLine() {
    return addressLine;
  }

  /** Dow Jones persons address administrative area */
  @JsonIgnore
  public Optional<String> administrativeArea() {
    return administrativeArea;
  }

  /** Dow Jones persons address postal code */
  @JsonIgnore
  public Optional<String> postalCode() {
    return postalCode;
  }

  /**
   * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
   * "CA"
   */
  @JsonIgnore
  public Optional<String> regionCode() {
    return regionCode;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** Dow Jones persons address city */
  public AddressDetail withAddressCity(String addressCity) {
    Utils.checkNotNull(addressCity, "addressCity");
    this.addressCity = Optional.ofNullable(addressCity);
    return this;
  }

  /** Dow Jones persons address city */
  public AddressDetail withAddressCity(Optional<String> addressCity) {
    Utils.checkNotNull(addressCity, "addressCity");
    this.addressCity = addressCity;
    return this;
  }

  /** Dow Jones persons address line */
  public AddressDetail withAddressLine(String addressLine) {
    Utils.checkNotNull(addressLine, "addressLine");
    this.addressLine = Optional.ofNullable(addressLine);
    return this;
  }

  /** Dow Jones persons address line */
  public AddressDetail withAddressLine(Optional<String> addressLine) {
    Utils.checkNotNull(addressLine, "addressLine");
    this.addressLine = addressLine;
    return this;
  }

  /** Dow Jones persons address administrative area */
  public AddressDetail withAdministrativeArea(String administrativeArea) {
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    this.administrativeArea = Optional.ofNullable(administrativeArea);
    return this;
  }

  /** Dow Jones persons address administrative area */
  public AddressDetail withAdministrativeArea(Optional<String> administrativeArea) {
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    this.administrativeArea = administrativeArea;
    return this;
  }

  /** Dow Jones persons address postal code */
  public AddressDetail withPostalCode(String postalCode) {
    Utils.checkNotNull(postalCode, "postalCode");
    this.postalCode = Optional.ofNullable(postalCode);
    return this;
  }

  /** Dow Jones persons address postal code */
  public AddressDetail withPostalCode(Optional<String> postalCode) {
    Utils.checkNotNull(postalCode, "postalCode");
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
   * "CA"
   */
  public AddressDetail withRegionCode(String regionCode) {
    Utils.checkNotNull(regionCode, "regionCode");
    this.regionCode = Optional.ofNullable(regionCode);
    return this;
  }

  /**
   * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
   * "CA"
   */
  public AddressDetail withRegionCode(Optional<String> regionCode) {
    Utils.checkNotNull(regionCode, "regionCode");
    this.regionCode = regionCode;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressDetail other = (AddressDetail) o;
    return Objects.deepEquals(this.addressCity, other.addressCity)
        && Objects.deepEquals(this.addressLine, other.addressLine)
        && Objects.deepEquals(this.administrativeArea, other.administrativeArea)
        && Objects.deepEquals(this.postalCode, other.postalCode)
        && Objects.deepEquals(this.regionCode, other.regionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressCity, addressLine, administrativeArea, postalCode, regionCode);
  }

  @Override
  public String toString() {
    return Utils.toString(
        AddressDetail.class,
        "addressCity",
        addressCity,
        "addressLine",
        addressLine,
        "administrativeArea",
        administrativeArea,
        "postalCode",
        postalCode,
        "regionCode",
        regionCode);
  }

  public static final class Builder {

    private Optional<String> addressCity = Optional.empty();

    private Optional<String> addressLine = Optional.empty();

    private Optional<String> administrativeArea = Optional.empty();

    private Optional<String> postalCode = Optional.empty();

    private Optional<String> regionCode = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Dow Jones persons address city */
    public Builder addressCity(String addressCity) {
      Utils.checkNotNull(addressCity, "addressCity");
      this.addressCity = Optional.ofNullable(addressCity);
      return this;
    }

    /** Dow Jones persons address city */
    public Builder addressCity(Optional<String> addressCity) {
      Utils.checkNotNull(addressCity, "addressCity");
      this.addressCity = addressCity;
      return this;
    }

    /** Dow Jones persons address line */
    public Builder addressLine(String addressLine) {
      Utils.checkNotNull(addressLine, "addressLine");
      this.addressLine = Optional.ofNullable(addressLine);
      return this;
    }

    /** Dow Jones persons address line */
    public Builder addressLine(Optional<String> addressLine) {
      Utils.checkNotNull(addressLine, "addressLine");
      this.addressLine = addressLine;
      return this;
    }

    /** Dow Jones persons address administrative area */
    public Builder administrativeArea(String administrativeArea) {
      Utils.checkNotNull(administrativeArea, "administrativeArea");
      this.administrativeArea = Optional.ofNullable(administrativeArea);
      return this;
    }

    /** Dow Jones persons address administrative area */
    public Builder administrativeArea(Optional<String> administrativeArea) {
      Utils.checkNotNull(administrativeArea, "administrativeArea");
      this.administrativeArea = administrativeArea;
      return this;
    }

    /** Dow Jones persons address postal code */
    public Builder postalCode(String postalCode) {
      Utils.checkNotNull(postalCode, "postalCode");
      this.postalCode = Optional.ofNullable(postalCode);
      return this;
    }

    /** Dow Jones persons address postal code */
    public Builder postalCode(Optional<String> postalCode) {
      Utils.checkNotNull(postalCode, "postalCode");
      this.postalCode = postalCode;
      return this;
    }

    /**
     * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
     * "CA"
     */
    public Builder regionCode(String regionCode) {
      Utils.checkNotNull(regionCode, "regionCode");
      this.regionCode = Optional.ofNullable(regionCode);
      return this;
    }

    /**
     * Two character region code, complies with https://cldr.unicode.org/index Example values: "US",
     * "CA"
     */
    public Builder regionCode(Optional<String> regionCode) {
      Utils.checkNotNull(regionCode, "regionCode");
      this.regionCode = regionCode;
      return this;
    }

    public AddressDetail build() {
      return new AddressDetail(
          addressCity, addressLine, administrativeArea, postalCode, regionCode);
    }
  }
}
