/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * AlternativeOrderCreateIdentifierType
 *
 * <p>Identifies which parameter value is used to identify the asset in the order. The value for
 * that parameter is used in the `identifier` field.
 */
@JsonDeserialize(using = AlternativeOrderCreateIdentifierType._Deserializer.class)
@JsonSerialize(using = AlternativeOrderCreateIdentifierType._Serializer.class)
public class AlternativeOrderCreateIdentifierType {

  public static final AlternativeOrderCreateIdentifierType IDENTIFIER_TYPE_UNSPECIFIED =
      new AlternativeOrderCreateIdentifierType("IDENTIFIER_TYPE_UNSPECIFIED");
  public static final AlternativeOrderCreateIdentifierType ASSET_ID =
      new AlternativeOrderCreateIdentifierType("ASSET_ID");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, AlternativeOrderCreateIdentifierType> values = createValuesMap();
  private static final Map<String, AlternativeOrderCreateIdentifierTypeEnum> enums =
      createEnumsMap();

  private final String value;

  private AlternativeOrderCreateIdentifierType(String value) {
    this.value = value;
  }

  /**
   * Returns a AlternativeOrderCreateIdentifierType with the given value. For a specific value the
   * returned object will always be a singleton so reference equality is satisfied when the values
   * are the same.
   *
   * @param value value to be wrapped as AlternativeOrderCreateIdentifierType
   */
  public static AlternativeOrderCreateIdentifierType of(String value) {
    synchronized (AlternativeOrderCreateIdentifierType.class) {
      return values.computeIfAbsent(value, v -> new AlternativeOrderCreateIdentifierType(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<AlternativeOrderCreateIdentifierTypeEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    AlternativeOrderCreateIdentifierType other = (AlternativeOrderCreateIdentifierType) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "AlternativeOrderCreateIdentifierType [value=" + value + "]";
  }

  // return an array just like an enum
  public static AlternativeOrderCreateIdentifierType[] values() {
    synchronized (AlternativeOrderCreateIdentifierType.class) {
      return values.values().toArray(new AlternativeOrderCreateIdentifierType[] {});
    }
  }

  private static final Map<String, AlternativeOrderCreateIdentifierType> createValuesMap() {
    Map<String, AlternativeOrderCreateIdentifierType> map = new LinkedHashMap<>();
    map.put("IDENTIFIER_TYPE_UNSPECIFIED", IDENTIFIER_TYPE_UNSPECIFIED);
    map.put("ASSET_ID", ASSET_ID);
    return map;
  }

  private static final Map<String, AlternativeOrderCreateIdentifierTypeEnum> createEnumsMap() {
    Map<String, AlternativeOrderCreateIdentifierTypeEnum> map = new HashMap<>();
    map.put(
        "IDENTIFIER_TYPE_UNSPECIFIED",
        AlternativeOrderCreateIdentifierTypeEnum.IDENTIFIER_TYPE_UNSPECIFIED);
    map.put("ASSET_ID", AlternativeOrderCreateIdentifierTypeEnum.ASSET_ID);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer
      extends StdSerializer<AlternativeOrderCreateIdentifierType> {

    protected _Serializer() {
      super(AlternativeOrderCreateIdentifierType.class);
    }

    @Override
    public void serialize(
        AlternativeOrderCreateIdentifierType value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<AlternativeOrderCreateIdentifierType> {

    protected _Deserializer() {
      super(AlternativeOrderCreateIdentifierType.class);
    }

    @Override
    public AlternativeOrderCreateIdentifierType deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return AlternativeOrderCreateIdentifierType.of(v);
    }
  }

  public enum AlternativeOrderCreateIdentifierTypeEnum {
    IDENTIFIER_TYPE_UNSPECIFIED("IDENTIFIER_TYPE_UNSPECIFIED"),
    ASSET_ID("ASSET_ID"),
    ;

    private final String value;

    private AlternativeOrderCreateIdentifierTypeEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
