/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * BankRelationshipStateState
 *
 * <p>The high level state of the bank relationship.
 */
@JsonDeserialize(using = BankRelationshipStateState._Deserializer.class)
@JsonSerialize(using = BankRelationshipStateState._Serializer.class)
public class BankRelationshipStateState {

  public static final BankRelationshipStateState STATE_UNSPECIFIED =
      new BankRelationshipStateState("STATE_UNSPECIFIED");
  public static final BankRelationshipStateState PENDING =
      new BankRelationshipStateState("PENDING");
  public static final BankRelationshipStateState APPROVED =
      new BankRelationshipStateState("APPROVED");
  public static final BankRelationshipStateState CANCELED =
      new BankRelationshipStateState("CANCELED");
  public static final BankRelationshipStateState REJECTED =
      new BankRelationshipStateState("REJECTED");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, BankRelationshipStateState> values = createValuesMap();
  private static final Map<String, BankRelationshipStateStateEnum> enums = createEnumsMap();

  private final String value;

  private BankRelationshipStateState(String value) {
    this.value = value;
  }

  /**
   * Returns a BankRelationshipStateState with the given value. For a specific value the returned
   * object will always be a singleton so reference equality is satisfied when the values are the
   * same.
   *
   * @param value value to be wrapped as BankRelationshipStateState
   */
  public static BankRelationshipStateState of(String value) {
    synchronized (BankRelationshipStateState.class) {
      return values.computeIfAbsent(value, v -> new BankRelationshipStateState(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<BankRelationshipStateStateEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    BankRelationshipStateState other = (BankRelationshipStateState) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "BankRelationshipStateState [value=" + value + "]";
  }

  // return an array just like an enum
  public static BankRelationshipStateState[] values() {
    synchronized (BankRelationshipStateState.class) {
      return values.values().toArray(new BankRelationshipStateState[] {});
    }
  }

  private static final Map<String, BankRelationshipStateState> createValuesMap() {
    Map<String, BankRelationshipStateState> map = new LinkedHashMap<>();
    map.put("STATE_UNSPECIFIED", STATE_UNSPECIFIED);
    map.put("PENDING", PENDING);
    map.put("APPROVED", APPROVED);
    map.put("CANCELED", CANCELED);
    map.put("REJECTED", REJECTED);
    return map;
  }

  private static final Map<String, BankRelationshipStateStateEnum> createEnumsMap() {
    Map<String, BankRelationshipStateStateEnum> map = new HashMap<>();
    map.put("STATE_UNSPECIFIED", BankRelationshipStateStateEnum.STATE_UNSPECIFIED);
    map.put("PENDING", BankRelationshipStateStateEnum.PENDING);
    map.put("APPROVED", BankRelationshipStateStateEnum.APPROVED);
    map.put("CANCELED", BankRelationshipStateStateEnum.CANCELED);
    map.put("REJECTED", BankRelationshipStateStateEnum.REJECTED);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<BankRelationshipStateState> {

    protected _Serializer() {
      super(BankRelationshipStateState.class);
    }

    @Override
    public void serialize(
        BankRelationshipStateState value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<BankRelationshipStateState> {

    protected _Deserializer() {
      super(BankRelationshipStateState.class);
    }

    @Override
    public BankRelationshipStateState deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return BankRelationshipStateState.of(v);
    }
  }

  public enum BankRelationshipStateStateEnum {
    STATE_UNSPECIFIED("STATE_UNSPECIFIED"),
    PENDING("PENDING"),
    APPROVED("APPROVED"),
    CANCELED("CANCELED"),
    REJECTED("REJECTED"),
    ;

    private final String value;

    private BankRelationshipStateStateEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
