/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/** CalculateCashBalanceResponseTransferSummaryMechanism - The mechanism of the transfer. */
@JsonDeserialize(using = CalculateCashBalanceResponseTransferSummaryMechanism._Deserializer.class)
@JsonSerialize(using = CalculateCashBalanceResponseTransferSummaryMechanism._Serializer.class)
public class CalculateCashBalanceResponseTransferSummaryMechanism {

  public static final CalculateCashBalanceResponseTransferSummaryMechanism MECHANISM_UNSPECIFIED =
      new CalculateCashBalanceResponseTransferSummaryMechanism("MECHANISM_UNSPECIFIED");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism ACAT =
      new CalculateCashBalanceResponseTransferSummaryMechanism("ACAT");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism ACH =
      new CalculateCashBalanceResponseTransferSummaryMechanism("ACH");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism CASH_JOURNAL =
      new CalculateCashBalanceResponseTransferSummaryMechanism("CASH_JOURNAL");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism CHECK =
      new CalculateCashBalanceResponseTransferSummaryMechanism("CHECK");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism CREDIT =
      new CalculateCashBalanceResponseTransferSummaryMechanism("CREDIT");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism FEE =
      new CalculateCashBalanceResponseTransferSummaryMechanism("FEE");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism ICT =
      new CalculateCashBalanceResponseTransferSummaryMechanism("ICT");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism PAYPAL =
      new CalculateCashBalanceResponseTransferSummaryMechanism("PAYPAL");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism RTP =
      new CalculateCashBalanceResponseTransferSummaryMechanism("RTP");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism TPJ =
      new CalculateCashBalanceResponseTransferSummaryMechanism("TPJ");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism WIRE =
      new CalculateCashBalanceResponseTransferSummaryMechanism("WIRE");
  public static final CalculateCashBalanceResponseTransferSummaryMechanism EXTERNAL_ACH =
      new CalculateCashBalanceResponseTransferSummaryMechanism("EXTERNAL_ACH");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, CalculateCashBalanceResponseTransferSummaryMechanism> values =
      createValuesMap();
  private static final Map<String, CalculateCashBalanceResponseTransferSummaryMechanismEnum> enums =
      createEnumsMap();

  private final String value;

  private CalculateCashBalanceResponseTransferSummaryMechanism(String value) {
    this.value = value;
  }

  /**
   * Returns a CalculateCashBalanceResponseTransferSummaryMechanism with the given value. For a
   * specific value the returned object will always be a singleton so reference equality is
   * satisfied when the values are the same.
   *
   * @param value value to be wrapped as CalculateCashBalanceResponseTransferSummaryMechanism
   */
  public static CalculateCashBalanceResponseTransferSummaryMechanism of(String value) {
    synchronized (CalculateCashBalanceResponseTransferSummaryMechanism.class) {
      return values.computeIfAbsent(
          value, v -> new CalculateCashBalanceResponseTransferSummaryMechanism(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<CalculateCashBalanceResponseTransferSummaryMechanismEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    CalculateCashBalanceResponseTransferSummaryMechanism other =
        (CalculateCashBalanceResponseTransferSummaryMechanism) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "CalculateCashBalanceResponseTransferSummaryMechanism [value=" + value + "]";
  }

  // return an array just like an enum
  public static CalculateCashBalanceResponseTransferSummaryMechanism[] values() {
    synchronized (CalculateCashBalanceResponseTransferSummaryMechanism.class) {
      return values.values().toArray(new CalculateCashBalanceResponseTransferSummaryMechanism[] {});
    }
  }

  private static final Map<String, CalculateCashBalanceResponseTransferSummaryMechanism>
      createValuesMap() {
    Map<String, CalculateCashBalanceResponseTransferSummaryMechanism> map = new LinkedHashMap<>();
    map.put("MECHANISM_UNSPECIFIED", MECHANISM_UNSPECIFIED);
    map.put("ACAT", ACAT);
    map.put("ACH", ACH);
    map.put("CASH_JOURNAL", CASH_JOURNAL);
    map.put("CHECK", CHECK);
    map.put("CREDIT", CREDIT);
    map.put("FEE", FEE);
    map.put("ICT", ICT);
    map.put("PAYPAL", PAYPAL);
    map.put("RTP", RTP);
    map.put("TPJ", TPJ);
    map.put("WIRE", WIRE);
    map.put("EXTERNAL_ACH", EXTERNAL_ACH);
    return map;
  }

  private static final Map<String, CalculateCashBalanceResponseTransferSummaryMechanismEnum>
      createEnumsMap() {
    Map<String, CalculateCashBalanceResponseTransferSummaryMechanismEnum> map = new HashMap<>();
    map.put(
        "MECHANISM_UNSPECIFIED",
        CalculateCashBalanceResponseTransferSummaryMechanismEnum.MECHANISM_UNSPECIFIED);
    map.put("ACAT", CalculateCashBalanceResponseTransferSummaryMechanismEnum.ACAT);
    map.put("ACH", CalculateCashBalanceResponseTransferSummaryMechanismEnum.ACH);
    map.put("CASH_JOURNAL", CalculateCashBalanceResponseTransferSummaryMechanismEnum.CASH_JOURNAL);
    map.put("CHECK", CalculateCashBalanceResponseTransferSummaryMechanismEnum.CHECK);
    map.put("CREDIT", CalculateCashBalanceResponseTransferSummaryMechanismEnum.CREDIT);
    map.put("FEE", CalculateCashBalanceResponseTransferSummaryMechanismEnum.FEE);
    map.put("ICT", CalculateCashBalanceResponseTransferSummaryMechanismEnum.ICT);
    map.put("PAYPAL", CalculateCashBalanceResponseTransferSummaryMechanismEnum.PAYPAL);
    map.put("RTP", CalculateCashBalanceResponseTransferSummaryMechanismEnum.RTP);
    map.put("TPJ", CalculateCashBalanceResponseTransferSummaryMechanismEnum.TPJ);
    map.put("WIRE", CalculateCashBalanceResponseTransferSummaryMechanismEnum.WIRE);
    map.put("EXTERNAL_ACH", CalculateCashBalanceResponseTransferSummaryMechanismEnum.EXTERNAL_ACH);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer
      extends StdSerializer<CalculateCashBalanceResponseTransferSummaryMechanism> {

    protected _Serializer() {
      super(CalculateCashBalanceResponseTransferSummaryMechanism.class);
    }

    @Override
    public void serialize(
        CalculateCashBalanceResponseTransferSummaryMechanism value,
        JsonGenerator g,
        SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<CalculateCashBalanceResponseTransferSummaryMechanism> {

    protected _Deserializer() {
      super(CalculateCashBalanceResponseTransferSummaryMechanism.class);
    }

    @Override
    public CalculateCashBalanceResponseTransferSummaryMechanism deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return CalculateCashBalanceResponseTransferSummaryMechanism.of(v);
    }
  }

  public enum CalculateCashBalanceResponseTransferSummaryMechanismEnum {
    MECHANISM_UNSPECIFIED("MECHANISM_UNSPECIFIED"),
    ACAT("ACAT"),
    ACH("ACH"),
    CASH_JOURNAL("CASH_JOURNAL"),
    CHECK("CHECK"),
    CREDIT("CREDIT"),
    FEE("FEE"),
    ICT("ICT"),
    PAYPAL("PAYPAL"),
    RTP("RTP"),
    TPJ("TPJ"),
    WIRE("WIRE"),
    EXTERNAL_ACH("EXTERNAL_ACH"),
    ;

    private final String value;

    private CalculateCashBalanceResponseTransferSummaryMechanismEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
