/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/** CancelTradeAllocationResponseSideModifier - Side modifier for the trade allocation. */
@JsonDeserialize(using = CancelTradeAllocationResponseSideModifier._Deserializer.class)
@JsonSerialize(using = CancelTradeAllocationResponseSideModifier._Serializer.class)
public class CancelTradeAllocationResponseSideModifier {

  public static final CancelTradeAllocationResponseSideModifier SIDE_MODIFIER_UNSPECIFIED =
      new CancelTradeAllocationResponseSideModifier("SIDE_MODIFIER_UNSPECIFIED");
  public static final CancelTradeAllocationResponseSideModifier SHORT =
      new CancelTradeAllocationResponseSideModifier("SHORT");
  public static final CancelTradeAllocationResponseSideModifier SHORT_EXEMPT =
      new CancelTradeAllocationResponseSideModifier("SHORT_EXEMPT");
  public static final CancelTradeAllocationResponseSideModifier SHORT_COVER =
      new CancelTradeAllocationResponseSideModifier("SHORT_COVER");
  public static final CancelTradeAllocationResponseSideModifier OPEN =
      new CancelTradeAllocationResponseSideModifier("OPEN");
  public static final CancelTradeAllocationResponseSideModifier CLOSE =
      new CancelTradeAllocationResponseSideModifier("CLOSE");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, CancelTradeAllocationResponseSideModifier> values =
      createValuesMap();
  private static final Map<String, CancelTradeAllocationResponseSideModifierEnum> enums =
      createEnumsMap();

  private final String value;

  private CancelTradeAllocationResponseSideModifier(String value) {
    this.value = value;
  }

  /**
   * Returns a CancelTradeAllocationResponseSideModifier with the given value. For a specific value
   * the returned object will always be a singleton so reference equality is satisfied when the
   * values are the same.
   *
   * @param value value to be wrapped as CancelTradeAllocationResponseSideModifier
   */
  public static CancelTradeAllocationResponseSideModifier of(String value) {
    synchronized (CancelTradeAllocationResponseSideModifier.class) {
      return values.computeIfAbsent(value, v -> new CancelTradeAllocationResponseSideModifier(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<CancelTradeAllocationResponseSideModifierEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    CancelTradeAllocationResponseSideModifier other =
        (CancelTradeAllocationResponseSideModifier) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "CancelTradeAllocationResponseSideModifier [value=" + value + "]";
  }

  // return an array just like an enum
  public static CancelTradeAllocationResponseSideModifier[] values() {
    synchronized (CancelTradeAllocationResponseSideModifier.class) {
      return values.values().toArray(new CancelTradeAllocationResponseSideModifier[] {});
    }
  }

  private static final Map<String, CancelTradeAllocationResponseSideModifier> createValuesMap() {
    Map<String, CancelTradeAllocationResponseSideModifier> map = new LinkedHashMap<>();
    map.put("SIDE_MODIFIER_UNSPECIFIED", SIDE_MODIFIER_UNSPECIFIED);
    map.put("SHORT", SHORT);
    map.put("SHORT_EXEMPT", SHORT_EXEMPT);
    map.put("SHORT_COVER", SHORT_COVER);
    map.put("OPEN", OPEN);
    map.put("CLOSE", CLOSE);
    return map;
  }

  private static final Map<String, CancelTradeAllocationResponseSideModifierEnum> createEnumsMap() {
    Map<String, CancelTradeAllocationResponseSideModifierEnum> map = new HashMap<>();
    map.put(
        "SIDE_MODIFIER_UNSPECIFIED",
        CancelTradeAllocationResponseSideModifierEnum.SIDE_MODIFIER_UNSPECIFIED);
    map.put("SHORT", CancelTradeAllocationResponseSideModifierEnum.SHORT);
    map.put("SHORT_EXEMPT", CancelTradeAllocationResponseSideModifierEnum.SHORT_EXEMPT);
    map.put("SHORT_COVER", CancelTradeAllocationResponseSideModifierEnum.SHORT_COVER);
    map.put("OPEN", CancelTradeAllocationResponseSideModifierEnum.OPEN);
    map.put("CLOSE", CancelTradeAllocationResponseSideModifierEnum.CLOSE);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer
      extends StdSerializer<CancelTradeAllocationResponseSideModifier> {

    protected _Serializer() {
      super(CancelTradeAllocationResponseSideModifier.class);
    }

    @Override
    public void serialize(
        CancelTradeAllocationResponseSideModifier value,
        JsonGenerator g,
        SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<CancelTradeAllocationResponseSideModifier> {

    protected _Deserializer() {
      super(CancelTradeAllocationResponseSideModifier.class);
    }

    @Override
    public CancelTradeAllocationResponseSideModifier deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return CancelTradeAllocationResponseSideModifier.of(v);
    }
  }

  public enum CancelTradeAllocationResponseSideModifierEnum {
    SIDE_MODIFIER_UNSPECIFIED("SIDE_MODIFIER_UNSPECIFIED"),
    SHORT("SHORT"),
    SHORT_EXEMPT("SHORT_EXEMPT"),
    SHORT_COVER("SHORT_COVER"),
    OPEN("OPEN"),
    CLOSE("CLOSE"),
    ;

    private final String value;

    private CancelTradeAllocationResponseSideModifierEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
