/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/** CancelTradeRequestCreate - A request for canceling all executions underneath a trade. */
public class CancelTradeRequestCreate {

  /** The name of the trade to cancel. */
  @JsonProperty("name")
  private String name;

  @JsonCreator
  public CancelTradeRequestCreate(@JsonProperty("name") String name) {
    Utils.checkNotNull(name, "name");
    this.name = name;
  }

  /** The name of the trade to cancel. */
  @JsonIgnore
  public String name() {
    return name;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The name of the trade to cancel. */
  public CancelTradeRequestCreate withName(String name) {
    Utils.checkNotNull(name, "name");
    this.name = name;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelTradeRequestCreate other = (CancelTradeRequestCreate) o;
    return Objects.deepEquals(this.name, other.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }

  @Override
  public String toString() {
    return Utils.toString(CancelTradeRequestCreate.class, "name", name);
  }

  public static final class Builder {

    private String name;

    private Builder() {
      // force use of static builder() method
    }

    /** The name of the trade to cancel. */
    public Builder name(String name) {
      Utils.checkNotNull(name, "name");
      this.name = name;
      return this;
    }

    public CancelTradeRequestCreate build() {
      return new CancelTradeRequestCreate(name);
    }
  }
}
