/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * CashJournal - A cash journal transfer. Funds are moved from a source account to a destination
 * account
 */
public class CashJournal {

  /** The amount to transfer in USD */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("amount")
  private JsonNullable<? extends CashJournalAmount> amount;

  /**
   * The external identifier supplied by the API caller Each request must have a unique pairing of
   * `client_transfer_id` and `source_account`
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("client_transfer_id")
  private Optional<String> clientTransferId;

  /** The account that funds will be moved to */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("destination_account")
  private Optional<String> destinationAccount;

  /** The resource name of the cash journal */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("name")
  private Optional<String> name;

  /**
   * Whether a cash journal is first party or third party Determined asynchronously when the
   * transfer is processing, and will be set by the time the transfer is posted
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("party_type")
  private Optional<? extends PartyType> partyType;

  /**
   * The retirement contribution details Must be provided when the destination account is a
   * retirement account
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("retirement_contribution")
  private JsonNullable<? extends CashJournalRetirementContribution> retirementContribution;

  /**
   * The retirement distribution details Must be provided when the source account is a retirement
   * account
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("retirement_distribution")
  private JsonNullable<? extends CashJournalRetirementDistribution> retirementDistribution;

  /** The account that funds will be moved from */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("source_account")
  private Optional<String> sourceAccount;

  /** The current state of the cash journal */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("state")
  private JsonNullable<? extends CashJournalState> state;

  @JsonCreator
  public CashJournal(
      @JsonProperty("amount") JsonNullable<? extends CashJournalAmount> amount,
      @JsonProperty("client_transfer_id") Optional<String> clientTransferId,
      @JsonProperty("destination_account") Optional<String> destinationAccount,
      @JsonProperty("name") Optional<String> name,
      @JsonProperty("party_type") Optional<? extends PartyType> partyType,
      @JsonProperty("retirement_contribution")
          JsonNullable<? extends CashJournalRetirementContribution> retirementContribution,
      @JsonProperty("retirement_distribution")
          JsonNullable<? extends CashJournalRetirementDistribution> retirementDistribution,
      @JsonProperty("source_account") Optional<String> sourceAccount,
      @JsonProperty("state") JsonNullable<? extends CashJournalState> state) {
    Utils.checkNotNull(amount, "amount");
    Utils.checkNotNull(clientTransferId, "clientTransferId");
    Utils.checkNotNull(destinationAccount, "destinationAccount");
    Utils.checkNotNull(name, "name");
    Utils.checkNotNull(partyType, "partyType");
    Utils.checkNotNull(retirementContribution, "retirementContribution");
    Utils.checkNotNull(retirementDistribution, "retirementDistribution");
    Utils.checkNotNull(sourceAccount, "sourceAccount");
    Utils.checkNotNull(state, "state");
    this.amount = amount;
    this.clientTransferId = clientTransferId;
    this.destinationAccount = destinationAccount;
    this.name = name;
    this.partyType = partyType;
    this.retirementContribution = retirementContribution;
    this.retirementDistribution = retirementDistribution;
    this.sourceAccount = sourceAccount;
    this.state = state;
  }

  public CashJournal() {
    this(
        JsonNullable.undefined(),
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        JsonNullable.undefined(),
        JsonNullable.undefined(),
        Optional.empty(),
        JsonNullable.undefined());
  }

  /** The amount to transfer in USD */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalAmount> amount() {
    return (JsonNullable<CashJournalAmount>) amount;
  }

  /**
   * The external identifier supplied by the API caller Each request must have a unique pairing of
   * `client_transfer_id` and `source_account`
   */
  @JsonIgnore
  public Optional<String> clientTransferId() {
    return clientTransferId;
  }

  /** The account that funds will be moved to */
  @JsonIgnore
  public Optional<String> destinationAccount() {
    return destinationAccount;
  }

  /** The resource name of the cash journal */
  @JsonIgnore
  public Optional<String> name() {
    return name;
  }

  /**
   * Whether a cash journal is first party or third party Determined asynchronously when the
   * transfer is processing, and will be set by the time the transfer is posted
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<PartyType> partyType() {
    return (Optional<PartyType>) partyType;
  }

  /**
   * The retirement contribution details Must be provided when the destination account is a
   * retirement account
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalRetirementContribution> retirementContribution() {
    return (JsonNullable<CashJournalRetirementContribution>) retirementContribution;
  }

  /**
   * The retirement distribution details Must be provided when the source account is a retirement
   * account
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalRetirementDistribution> retirementDistribution() {
    return (JsonNullable<CashJournalRetirementDistribution>) retirementDistribution;
  }

  /** The account that funds will be moved from */
  @JsonIgnore
  public Optional<String> sourceAccount() {
    return sourceAccount;
  }

  /** The current state of the cash journal */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalState> state() {
    return (JsonNullable<CashJournalState>) state;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The amount to transfer in USD */
  public CashJournal withAmount(CashJournalAmount amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = JsonNullable.of(amount);
    return this;
  }

  /** The amount to transfer in USD */
  public CashJournal withAmount(JsonNullable<? extends CashJournalAmount> amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = amount;
    return this;
  }

  /**
   * The external identifier supplied by the API caller Each request must have a unique pairing of
   * `client_transfer_id` and `source_account`
   */
  public CashJournal withClientTransferId(String clientTransferId) {
    Utils.checkNotNull(clientTransferId, "clientTransferId");
    this.clientTransferId = Optional.ofNullable(clientTransferId);
    return this;
  }

  /**
   * The external identifier supplied by the API caller Each request must have a unique pairing of
   * `client_transfer_id` and `source_account`
   */
  public CashJournal withClientTransferId(Optional<String> clientTransferId) {
    Utils.checkNotNull(clientTransferId, "clientTransferId");
    this.clientTransferId = clientTransferId;
    return this;
  }

  /** The account that funds will be moved to */
  public CashJournal withDestinationAccount(String destinationAccount) {
    Utils.checkNotNull(destinationAccount, "destinationAccount");
    this.destinationAccount = Optional.ofNullable(destinationAccount);
    return this;
  }

  /** The account that funds will be moved to */
  public CashJournal withDestinationAccount(Optional<String> destinationAccount) {
    Utils.checkNotNull(destinationAccount, "destinationAccount");
    this.destinationAccount = destinationAccount;
    return this;
  }

  /** The resource name of the cash journal */
  public CashJournal withName(String name) {
    Utils.checkNotNull(name, "name");
    this.name = Optional.ofNullable(name);
    return this;
  }

  /** The resource name of the cash journal */
  public CashJournal withName(Optional<String> name) {
    Utils.checkNotNull(name, "name");
    this.name = name;
    return this;
  }

  /**
   * Whether a cash journal is first party or third party Determined asynchronously when the
   * transfer is processing, and will be set by the time the transfer is posted
   */
  public CashJournal withPartyType(PartyType partyType) {
    Utils.checkNotNull(partyType, "partyType");
    this.partyType = Optional.ofNullable(partyType);
    return this;
  }

  /**
   * Whether a cash journal is first party or third party Determined asynchronously when the
   * transfer is processing, and will be set by the time the transfer is posted
   */
  public CashJournal withPartyType(Optional<? extends PartyType> partyType) {
    Utils.checkNotNull(partyType, "partyType");
    this.partyType = partyType;
    return this;
  }

  /**
   * The retirement contribution details Must be provided when the destination account is a
   * retirement account
   */
  public CashJournal withRetirementContribution(
      CashJournalRetirementContribution retirementContribution) {
    Utils.checkNotNull(retirementContribution, "retirementContribution");
    this.retirementContribution = JsonNullable.of(retirementContribution);
    return this;
  }

  /**
   * The retirement contribution details Must be provided when the destination account is a
   * retirement account
   */
  public CashJournal withRetirementContribution(
      JsonNullable<? extends CashJournalRetirementContribution> retirementContribution) {
    Utils.checkNotNull(retirementContribution, "retirementContribution");
    this.retirementContribution = retirementContribution;
    return this;
  }

  /**
   * The retirement distribution details Must be provided when the source account is a retirement
   * account
   */
  public CashJournal withRetirementDistribution(
      CashJournalRetirementDistribution retirementDistribution) {
    Utils.checkNotNull(retirementDistribution, "retirementDistribution");
    this.retirementDistribution = JsonNullable.of(retirementDistribution);
    return this;
  }

  /**
   * The retirement distribution details Must be provided when the source account is a retirement
   * account
   */
  public CashJournal withRetirementDistribution(
      JsonNullable<? extends CashJournalRetirementDistribution> retirementDistribution) {
    Utils.checkNotNull(retirementDistribution, "retirementDistribution");
    this.retirementDistribution = retirementDistribution;
    return this;
  }

  /** The account that funds will be moved from */
  public CashJournal withSourceAccount(String sourceAccount) {
    Utils.checkNotNull(sourceAccount, "sourceAccount");
    this.sourceAccount = Optional.ofNullable(sourceAccount);
    return this;
  }

  /** The account that funds will be moved from */
  public CashJournal withSourceAccount(Optional<String> sourceAccount) {
    Utils.checkNotNull(sourceAccount, "sourceAccount");
    this.sourceAccount = sourceAccount;
    return this;
  }

  /** The current state of the cash journal */
  public CashJournal withState(CashJournalState state) {
    Utils.checkNotNull(state, "state");
    this.state = JsonNullable.of(state);
    return this;
  }

  /** The current state of the cash journal */
  public CashJournal withState(JsonNullable<? extends CashJournalState> state) {
    Utils.checkNotNull(state, "state");
    this.state = state;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashJournal other = (CashJournal) o;
    return Objects.deepEquals(this.amount, other.amount)
        && Objects.deepEquals(this.clientTransferId, other.clientTransferId)
        && Objects.deepEquals(this.destinationAccount, other.destinationAccount)
        && Objects.deepEquals(this.name, other.name)
        && Objects.deepEquals(this.partyType, other.partyType)
        && Objects.deepEquals(this.retirementContribution, other.retirementContribution)
        && Objects.deepEquals(this.retirementDistribution, other.retirementDistribution)
        && Objects.deepEquals(this.sourceAccount, other.sourceAccount)
        && Objects.deepEquals(this.state, other.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        amount,
        clientTransferId,
        destinationAccount,
        name,
        partyType,
        retirementContribution,
        retirementDistribution,
        sourceAccount,
        state);
  }

  @Override
  public String toString() {
    return Utils.toString(
        CashJournal.class,
        "amount",
        amount,
        "clientTransferId",
        clientTransferId,
        "destinationAccount",
        destinationAccount,
        "name",
        name,
        "partyType",
        partyType,
        "retirementContribution",
        retirementContribution,
        "retirementDistribution",
        retirementDistribution,
        "sourceAccount",
        sourceAccount,
        "state",
        state);
  }

  public static final class Builder {

    private JsonNullable<? extends CashJournalAmount> amount = JsonNullable.undefined();

    private Optional<String> clientTransferId = Optional.empty();

    private Optional<String> destinationAccount = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<? extends PartyType> partyType = Optional.empty();

    private JsonNullable<? extends CashJournalRetirementContribution> retirementContribution =
        JsonNullable.undefined();

    private JsonNullable<? extends CashJournalRetirementDistribution> retirementDistribution =
        JsonNullable.undefined();

    private Optional<String> sourceAccount = Optional.empty();

    private JsonNullable<? extends CashJournalState> state = JsonNullable.undefined();

    private Builder() {
      // force use of static builder() method
    }

    /** The amount to transfer in USD */
    public Builder amount(CashJournalAmount amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = JsonNullable.of(amount);
      return this;
    }

    /** The amount to transfer in USD */
    public Builder amount(JsonNullable<? extends CashJournalAmount> amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = amount;
      return this;
    }

    /**
     * The external identifier supplied by the API caller Each request must have a unique pairing of
     * `client_transfer_id` and `source_account`
     */
    public Builder clientTransferId(String clientTransferId) {
      Utils.checkNotNull(clientTransferId, "clientTransferId");
      this.clientTransferId = Optional.ofNullable(clientTransferId);
      return this;
    }

    /**
     * The external identifier supplied by the API caller Each request must have a unique pairing of
     * `client_transfer_id` and `source_account`
     */
    public Builder clientTransferId(Optional<String> clientTransferId) {
      Utils.checkNotNull(clientTransferId, "clientTransferId");
      this.clientTransferId = clientTransferId;
      return this;
    }

    /** The account that funds will be moved to */
    public Builder destinationAccount(String destinationAccount) {
      Utils.checkNotNull(destinationAccount, "destinationAccount");
      this.destinationAccount = Optional.ofNullable(destinationAccount);
      return this;
    }

    /** The account that funds will be moved to */
    public Builder destinationAccount(Optional<String> destinationAccount) {
      Utils.checkNotNull(destinationAccount, "destinationAccount");
      this.destinationAccount = destinationAccount;
      return this;
    }

    /** The resource name of the cash journal */
    public Builder name(String name) {
      Utils.checkNotNull(name, "name");
      this.name = Optional.ofNullable(name);
      return this;
    }

    /** The resource name of the cash journal */
    public Builder name(Optional<String> name) {
      Utils.checkNotNull(name, "name");
      this.name = name;
      return this;
    }

    /**
     * Whether a cash journal is first party or third party Determined asynchronously when the
     * transfer is processing, and will be set by the time the transfer is posted
     */
    public Builder partyType(PartyType partyType) {
      Utils.checkNotNull(partyType, "partyType");
      this.partyType = Optional.ofNullable(partyType);
      return this;
    }

    /**
     * Whether a cash journal is first party or third party Determined asynchronously when the
     * transfer is processing, and will be set by the time the transfer is posted
     */
    public Builder partyType(Optional<? extends PartyType> partyType) {
      Utils.checkNotNull(partyType, "partyType");
      this.partyType = partyType;
      return this;
    }

    /**
     * The retirement contribution details Must be provided when the destination account is a
     * retirement account
     */
    public Builder retirementContribution(
        CashJournalRetirementContribution retirementContribution) {
      Utils.checkNotNull(retirementContribution, "retirementContribution");
      this.retirementContribution = JsonNullable.of(retirementContribution);
      return this;
    }

    /**
     * The retirement contribution details Must be provided when the destination account is a
     * retirement account
     */
    public Builder retirementContribution(
        JsonNullable<? extends CashJournalRetirementContribution> retirementContribution) {
      Utils.checkNotNull(retirementContribution, "retirementContribution");
      this.retirementContribution = retirementContribution;
      return this;
    }

    /**
     * The retirement distribution details Must be provided when the source account is a retirement
     * account
     */
    public Builder retirementDistribution(
        CashJournalRetirementDistribution retirementDistribution) {
      Utils.checkNotNull(retirementDistribution, "retirementDistribution");
      this.retirementDistribution = JsonNullable.of(retirementDistribution);
      return this;
    }

    /**
     * The retirement distribution details Must be provided when the source account is a retirement
     * account
     */
    public Builder retirementDistribution(
        JsonNullable<? extends CashJournalRetirementDistribution> retirementDistribution) {
      Utils.checkNotNull(retirementDistribution, "retirementDistribution");
      this.retirementDistribution = retirementDistribution;
      return this;
    }

    /** The account that funds will be moved from */
    public Builder sourceAccount(String sourceAccount) {
      Utils.checkNotNull(sourceAccount, "sourceAccount");
      this.sourceAccount = Optional.ofNullable(sourceAccount);
      return this;
    }

    /** The account that funds will be moved from */
    public Builder sourceAccount(Optional<String> sourceAccount) {
      Utils.checkNotNull(sourceAccount, "sourceAccount");
      this.sourceAccount = sourceAccount;
      return this;
    }

    /** The current state of the cash journal */
    public Builder state(CashJournalState state) {
      Utils.checkNotNull(state, "state");
      this.state = JsonNullable.of(state);
      return this;
    }

    /** The current state of the cash journal */
    public Builder state(JsonNullable<? extends CashJournalState> state) {
      Utils.checkNotNull(state, "state");
      this.state = state;
      return this;
    }

    public CashJournal build() {
      return new CashJournal(
          amount,
          clientTransferId,
          destinationAccount,
          name,
          partyType,
          retirementContribution,
          retirementDistribution,
          sourceAccount,
          state);
    }
  }
}
