/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * CashJournalScheduleScheduleDetails
 *
 * <p>The schedule details. This uses the WithdrawalScheduleDetails object in order to also support
 * full disbursement journals. The source_account is the account debited and would be completely
 * drawn down when schedule_details.full_disbursement == true
 */
public class CashJournalScheduleScheduleDetails {
  /** A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement') */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("amount")
  private JsonNullable<? extends CashJournalScheduleAmount> amount;

  /**
   * External identifier supplied by the API caller. Each request must have a unique pairing of
   * client_schedule_id and account
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("client_schedule_id")
  private Optional<String> clientScheduleId;

  /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("full_disbursement")
  private Optional<Boolean> fullDisbursement;

  /** Common schedule properties */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("schedule_properties")
  private JsonNullable<? extends CashJournalScheduleScheduleProperties> scheduleProperties;

  @JsonCreator
  public CashJournalScheduleScheduleDetails(
      @JsonProperty("amount") JsonNullable<? extends CashJournalScheduleAmount> amount,
      @JsonProperty("client_schedule_id") Optional<String> clientScheduleId,
      @JsonProperty("full_disbursement") Optional<Boolean> fullDisbursement,
      @JsonProperty("schedule_properties")
          JsonNullable<? extends CashJournalScheduleScheduleProperties> scheduleProperties) {
    Utils.checkNotNull(amount, "amount");
    Utils.checkNotNull(clientScheduleId, "clientScheduleId");
    Utils.checkNotNull(fullDisbursement, "fullDisbursement");
    Utils.checkNotNull(scheduleProperties, "scheduleProperties");
    this.amount = amount;
    this.clientScheduleId = clientScheduleId;
    this.fullDisbursement = fullDisbursement;
    this.scheduleProperties = scheduleProperties;
  }

  public CashJournalScheduleScheduleDetails() {
    this(JsonNullable.undefined(), Optional.empty(), Optional.empty(), JsonNullable.undefined());
  }

  /** A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement') */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalScheduleAmount> amount() {
    return (JsonNullable<CashJournalScheduleAmount>) amount;
  }

  /**
   * External identifier supplied by the API caller. Each request must have a unique pairing of
   * client_schedule_id and account
   */
  @JsonIgnore
  public Optional<String> clientScheduleId() {
    return clientScheduleId;
  }

  /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
  @JsonIgnore
  public Optional<Boolean> fullDisbursement() {
    return fullDisbursement;
  }

  /** Common schedule properties */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CashJournalScheduleScheduleProperties> scheduleProperties() {
    return (JsonNullable<CashJournalScheduleScheduleProperties>) scheduleProperties;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement') */
  public CashJournalScheduleScheduleDetails withAmount(CashJournalScheduleAmount amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = JsonNullable.of(amount);
    return this;
  }

  /** A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement') */
  public CashJournalScheduleScheduleDetails withAmount(
      JsonNullable<? extends CashJournalScheduleAmount> amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = amount;
    return this;
  }

  /**
   * External identifier supplied by the API caller. Each request must have a unique pairing of
   * client_schedule_id and account
   */
  public CashJournalScheduleScheduleDetails withClientScheduleId(String clientScheduleId) {
    Utils.checkNotNull(clientScheduleId, "clientScheduleId");
    this.clientScheduleId = Optional.ofNullable(clientScheduleId);
    return this;
  }

  /**
   * External identifier supplied by the API caller. Each request must have a unique pairing of
   * client_schedule_id and account
   */
  public CashJournalScheduleScheduleDetails withClientScheduleId(
      Optional<String> clientScheduleId) {
    Utils.checkNotNull(clientScheduleId, "clientScheduleId");
    this.clientScheduleId = clientScheduleId;
    return this;
  }

  /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
  public CashJournalScheduleScheduleDetails withFullDisbursement(boolean fullDisbursement) {
    Utils.checkNotNull(fullDisbursement, "fullDisbursement");
    this.fullDisbursement = Optional.ofNullable(fullDisbursement);
    return this;
  }

  /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
  public CashJournalScheduleScheduleDetails withFullDisbursement(
      Optional<Boolean> fullDisbursement) {
    Utils.checkNotNull(fullDisbursement, "fullDisbursement");
    this.fullDisbursement = fullDisbursement;
    return this;
  }

  /** Common schedule properties */
  public CashJournalScheduleScheduleDetails withScheduleProperties(
      CashJournalScheduleScheduleProperties scheduleProperties) {
    Utils.checkNotNull(scheduleProperties, "scheduleProperties");
    this.scheduleProperties = JsonNullable.of(scheduleProperties);
    return this;
  }

  /** Common schedule properties */
  public CashJournalScheduleScheduleDetails withScheduleProperties(
      JsonNullable<? extends CashJournalScheduleScheduleProperties> scheduleProperties) {
    Utils.checkNotNull(scheduleProperties, "scheduleProperties");
    this.scheduleProperties = scheduleProperties;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashJournalScheduleScheduleDetails other = (CashJournalScheduleScheduleDetails) o;
    return Utils.enhancedDeepEquals(this.amount, other.amount)
        && Utils.enhancedDeepEquals(this.clientScheduleId, other.clientScheduleId)
        && Utils.enhancedDeepEquals(this.fullDisbursement, other.fullDisbursement)
        && Utils.enhancedDeepEquals(this.scheduleProperties, other.scheduleProperties);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(amount, clientScheduleId, fullDisbursement, scheduleProperties);
  }

  @Override
  public String toString() {
    return Utils.toString(
        CashJournalScheduleScheduleDetails.class,
        "amount",
        amount,
        "clientScheduleId",
        clientScheduleId,
        "fullDisbursement",
        fullDisbursement,
        "scheduleProperties",
        scheduleProperties);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private JsonNullable<? extends CashJournalScheduleAmount> amount = JsonNullable.undefined();

    private Optional<String> clientScheduleId = Optional.empty();

    private Optional<Boolean> fullDisbursement = Optional.empty();

    private JsonNullable<? extends CashJournalScheduleScheduleProperties> scheduleProperties =
        JsonNullable.undefined();

    private Builder() {
      // force use of static builder() method
    }

    /**
     * A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement')
     */
    public Builder amount(CashJournalScheduleAmount amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = JsonNullable.of(amount);
      return this;
    }

    /**
     * A cash amount in the format of decimal value (mutually exclusive with 'full_disbursement')
     */
    public Builder amount(JsonNullable<? extends CashJournalScheduleAmount> amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = amount;
      return this;
    }

    /**
     * External identifier supplied by the API caller. Each request must have a unique pairing of
     * client_schedule_id and account
     */
    public Builder clientScheduleId(String clientScheduleId) {
      Utils.checkNotNull(clientScheduleId, "clientScheduleId");
      this.clientScheduleId = Optional.ofNullable(clientScheduleId);
      return this;
    }

    /**
     * External identifier supplied by the API caller. Each request must have a unique pairing of
     * client_schedule_id and account
     */
    public Builder clientScheduleId(Optional<String> clientScheduleId) {
      Utils.checkNotNull(clientScheduleId, "clientScheduleId");
      this.clientScheduleId = clientScheduleId;
      return this;
    }

    /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
    public Builder fullDisbursement(boolean fullDisbursement) {
      Utils.checkNotNull(fullDisbursement, "fullDisbursement");
      this.fullDisbursement = Optional.ofNullable(fullDisbursement);
      return this;
    }

    /** Flag to indicate a full disbursement transfer (mutually exclusive with 'amount') */
    public Builder fullDisbursement(Optional<Boolean> fullDisbursement) {
      Utils.checkNotNull(fullDisbursement, "fullDisbursement");
      this.fullDisbursement = fullDisbursement;
      return this;
    }

    /** Common schedule properties */
    public Builder scheduleProperties(CashJournalScheduleScheduleProperties scheduleProperties) {
      Utils.checkNotNull(scheduleProperties, "scheduleProperties");
      this.scheduleProperties = JsonNullable.of(scheduleProperties);
      return this;
    }

    /** Common schedule properties */
    public Builder scheduleProperties(
        JsonNullable<? extends CashJournalScheduleScheduleProperties> scheduleProperties) {
      Utils.checkNotNull(scheduleProperties, "scheduleProperties");
      this.scheduleProperties = scheduleProperties;
      return this;
    }

    public CashJournalScheduleScheduleDetails build() {

      return new CashJournalScheduleScheduleDetails(
          amount, clientScheduleId, fullDisbursement, scheduleProperties);
    }
  }
}
