/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapitools.jackson.nullable.JsonNullable;

public class Commission {
  /** Monetary amount associated with the commission */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("amount")
  private JsonNullable<? extends CommissionAmount1> amount;

  @JsonCreator
  public Commission(@JsonProperty("amount") JsonNullable<? extends CommissionAmount1> amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = amount;
  }

  public Commission() {
    this(JsonNullable.undefined());
  }

  /** Monetary amount associated with the commission */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<CommissionAmount1> amount() {
    return (JsonNullable<CommissionAmount1>) amount;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Monetary amount associated with the commission */
  public Commission withAmount(CommissionAmount1 amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = JsonNullable.of(amount);
    return this;
  }

  /** Monetary amount associated with the commission */
  public Commission withAmount(JsonNullable<? extends CommissionAmount1> amount) {
    Utils.checkNotNull(amount, "amount");
    this.amount = amount;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Commission other = (Commission) o;
    return Utils.enhancedDeepEquals(this.amount, other.amount);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(amount);
  }

  @Override
  public String toString() {
    return Utils.toString(Commission.class, "amount", amount);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private JsonNullable<? extends CommissionAmount1> amount = JsonNullable.undefined();

    private Builder() {
      // force use of static builder() method
    }

    /** Monetary amount associated with the commission */
    public Builder amount(CommissionAmount1 amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = JsonNullable.of(amount);
      return this;
    }

    /** Monetary amount associated with the commission */
    public Builder amount(JsonNullable<? extends CommissionAmount1> amount) {
      Utils.checkNotNull(amount, "amount");
      this.amount = amount;
      return this;
    }

    public Commission build() {

      return new Commission(amount);
    }
  }
}
