/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import java.util.Optional;

/** DeactivateEnrollmentRequestCreate - The request for deactivating an Enrollment on an account. */
public class DeactivateEnrollmentRequestCreate {

  /** A system-generated unique identifier referencing a single instance of an enrollment; */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("enrollment_id")
  private Optional<String> enrollmentId;

  /** Describes the name of the enrollment; Expressed as an enum */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("enrollment_type")
  private Optional<? extends DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType;

  @JsonCreator
  public DeactivateEnrollmentRequestCreate(
      @JsonProperty("enrollment_id") Optional<String> enrollmentId,
      @JsonProperty("enrollment_type")
          Optional<? extends DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType) {
    Utils.checkNotNull(enrollmentId, "enrollmentId");
    Utils.checkNotNull(enrollmentType, "enrollmentType");
    this.enrollmentId = enrollmentId;
    this.enrollmentType = enrollmentType;
  }

  public DeactivateEnrollmentRequestCreate() {
    this(Optional.empty(), Optional.empty());
  }

  /** A system-generated unique identifier referencing a single instance of an enrollment; */
  @JsonIgnore
  public Optional<String> enrollmentId() {
    return enrollmentId;
  }

  /** Describes the name of the enrollment; Expressed as an enum */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType() {
    return (Optional<DeactivateEnrollmentRequestCreateEnrollmentType>) enrollmentType;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** A system-generated unique identifier referencing a single instance of an enrollment; */
  public DeactivateEnrollmentRequestCreate withEnrollmentId(String enrollmentId) {
    Utils.checkNotNull(enrollmentId, "enrollmentId");
    this.enrollmentId = Optional.ofNullable(enrollmentId);
    return this;
  }

  /** A system-generated unique identifier referencing a single instance of an enrollment; */
  public DeactivateEnrollmentRequestCreate withEnrollmentId(Optional<String> enrollmentId) {
    Utils.checkNotNull(enrollmentId, "enrollmentId");
    this.enrollmentId = enrollmentId;
    return this;
  }

  /** Describes the name of the enrollment; Expressed as an enum */
  public DeactivateEnrollmentRequestCreate withEnrollmentType(
      DeactivateEnrollmentRequestCreateEnrollmentType enrollmentType) {
    Utils.checkNotNull(enrollmentType, "enrollmentType");
    this.enrollmentType = Optional.ofNullable(enrollmentType);
    return this;
  }

  /** Describes the name of the enrollment; Expressed as an enum */
  public DeactivateEnrollmentRequestCreate withEnrollmentType(
      Optional<? extends DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType) {
    Utils.checkNotNull(enrollmentType, "enrollmentType");
    this.enrollmentType = enrollmentType;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeactivateEnrollmentRequestCreate other = (DeactivateEnrollmentRequestCreate) o;
    return Objects.deepEquals(this.enrollmentId, other.enrollmentId)
        && Objects.deepEquals(this.enrollmentType, other.enrollmentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enrollmentId, enrollmentType);
  }

  @Override
  public String toString() {
    return Utils.toString(
        DeactivateEnrollmentRequestCreate.class,
        "enrollmentId",
        enrollmentId,
        "enrollmentType",
        enrollmentType);
  }

  public static final class Builder {

    private Optional<String> enrollmentId = Optional.empty();

    private Optional<? extends DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType =
        Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** A system-generated unique identifier referencing a single instance of an enrollment; */
    public Builder enrollmentId(String enrollmentId) {
      Utils.checkNotNull(enrollmentId, "enrollmentId");
      this.enrollmentId = Optional.ofNullable(enrollmentId);
      return this;
    }

    /** A system-generated unique identifier referencing a single instance of an enrollment; */
    public Builder enrollmentId(Optional<String> enrollmentId) {
      Utils.checkNotNull(enrollmentId, "enrollmentId");
      this.enrollmentId = enrollmentId;
      return this;
    }

    /** Describes the name of the enrollment; Expressed as an enum */
    public Builder enrollmentType(DeactivateEnrollmentRequestCreateEnrollmentType enrollmentType) {
      Utils.checkNotNull(enrollmentType, "enrollmentType");
      this.enrollmentType = Optional.ofNullable(enrollmentType);
      return this;
    }

    /** Describes the name of the enrollment; Expressed as an enum */
    public Builder enrollmentType(
        Optional<? extends DeactivateEnrollmentRequestCreateEnrollmentType> enrollmentType) {
      Utils.checkNotNull(enrollmentType, "enrollmentType");
      this.enrollmentType = enrollmentType;
      return this;
    }

    public DeactivateEnrollmentRequestCreate build() {
      return new DeactivateEnrollmentRequestCreate(enrollmentId, enrollmentType);
    }
  }
}
