/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * DisposalMethod
 *
 * <p>Disposal method applied.
 */
@JsonDeserialize(using = DisposalMethod._Deserializer.class)
@JsonSerialize(using = DisposalMethod._Serializer.class)
public class DisposalMethod {

  public static final DisposalMethod DISPOSAL_METHOD_UNSPECIFIED =
      new DisposalMethod("DISPOSAL_METHOD_UNSPECIFIED");
  public static final DisposalMethod FIFO = new DisposalMethod("FIFO");
  public static final DisposalMethod LIFO = new DisposalMethod("LIFO");
  public static final DisposalMethod HIGH_COST = new DisposalMethod("HIGH_COST");
  public static final DisposalMethod LOW_COST = new DisposalMethod("LOW_COST");
  public static final DisposalMethod MIN_TAX_TERM = new DisposalMethod("MIN_TAX_TERM");
  public static final DisposalMethod SPECIFIC_LOT = new DisposalMethod("SPECIFIC_LOT");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, DisposalMethod> values = createValuesMap();
  private static final Map<String, DisposalMethodEnum> enums = createEnumsMap();

  private final String value;

  private DisposalMethod(String value) {
    this.value = value;
  }

  /**
   * Returns a DisposalMethod with the given value. For a specific value the returned object will
   * always be a singleton so reference equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as DisposalMethod
   */
  public static DisposalMethod of(String value) {
    synchronized (DisposalMethod.class) {
      return values.computeIfAbsent(value, v -> new DisposalMethod(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<DisposalMethodEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    DisposalMethod other = (DisposalMethod) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "DisposalMethod [value=" + value + "]";
  }

  // return an array just like an enum
  public static DisposalMethod[] values() {
    synchronized (DisposalMethod.class) {
      return values.values().toArray(new DisposalMethod[] {});
    }
  }

  private static final Map<String, DisposalMethod> createValuesMap() {
    Map<String, DisposalMethod> map = new LinkedHashMap<>();
    map.put("DISPOSAL_METHOD_UNSPECIFIED", DISPOSAL_METHOD_UNSPECIFIED);
    map.put("FIFO", FIFO);
    map.put("LIFO", LIFO);
    map.put("HIGH_COST", HIGH_COST);
    map.put("LOW_COST", LOW_COST);
    map.put("MIN_TAX_TERM", MIN_TAX_TERM);
    map.put("SPECIFIC_LOT", SPECIFIC_LOT);
    return map;
  }

  private static final Map<String, DisposalMethodEnum> createEnumsMap() {
    Map<String, DisposalMethodEnum> map = new HashMap<>();
    map.put("DISPOSAL_METHOD_UNSPECIFIED", DisposalMethodEnum.DISPOSAL_METHOD_UNSPECIFIED);
    map.put("FIFO", DisposalMethodEnum.FIFO);
    map.put("LIFO", DisposalMethodEnum.LIFO);
    map.put("HIGH_COST", DisposalMethodEnum.HIGH_COST);
    map.put("LOW_COST", DisposalMethodEnum.LOW_COST);
    map.put("MIN_TAX_TERM", DisposalMethodEnum.MIN_TAX_TERM);
    map.put("SPECIFIC_LOT", DisposalMethodEnum.SPECIFIC_LOT);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<DisposalMethod> {

    protected _Serializer() {
      super(DisposalMethod.class);
    }

    @Override
    public void serialize(DisposalMethod value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<DisposalMethod> {

    protected _Deserializer() {
      super(DisposalMethod.class);
    }

    @Override
    public DisposalMethod deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return DisposalMethod.of(v);
    }
  }

  public enum DisposalMethodEnum {
    DISPOSAL_METHOD_UNSPECIFIED("DISPOSAL_METHOD_UNSPECIFIED"),
    FIFO("FIFO"),
    LIFO("LIFO"),
    HIGH_COST("HIGH_COST"),
    LOW_COST("LOW_COST"),
    MIN_TAX_TERM("MIN_TAX_TERM"),
    SPECIFIC_LOT("SPECIFIC_LOT"),
    ;

    private final String value;

    private DisposalMethodEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
