/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep
 *
 * <p>Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
 */
@JsonDeserialize(
    using = EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep._Deserializer.class)
@JsonSerialize(
    using = EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep._Serializer.class)
public class EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep {

  public static final EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep
      AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED =
          new EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep(
              "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED");
  public static final EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep
      FDIC_CASH_SWEEP_ENROLL =
          new EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep(
              "FDIC_CASH_SWEEP_ENROLL");
  public static final EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep
      FDIC_CASH_SWEEP_DECLINE =
          new EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep(
              "FDIC_CASH_SWEEP_DECLINE");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<
          String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep>
      values = createValuesMap();
  private static final Map<
          String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum>
      enums = createEnumsMap();

  private final String value;

  private EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep(String value) {
    this.value = value;
  }

  /**
   * Returns a EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep with the given
   * value. For a specific value the returned object will always be a singleton so reference
   * equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as
   *     EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep
   */
  public static EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep of(String value) {
    synchronized (EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep.class) {
      return values.computeIfAbsent(
          value, v -> new EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep other =
        (EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep [value="
        + value
        + "]";
  }

  // return an array just like an enum
  public static EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep[] values() {
    synchronized (EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep.class) {
      return values
          .values()
          .toArray(new EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep[] {});
    }
  }

  private static final Map<
          String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep>
      createValuesMap() {
    Map<String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep> map =
        new LinkedHashMap<>();
    map.put("AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED", AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED);
    map.put("FDIC_CASH_SWEEP_ENROLL", FDIC_CASH_SWEEP_ENROLL);
    map.put("FDIC_CASH_SWEEP_DECLINE", FDIC_CASH_SWEEP_DECLINE);
    return map;
  }

  private static final Map<
          String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum>
      createEnumsMap() {
    Map<String, EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum> map =
        new HashMap<>();
    map.put(
        "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED",
        EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum
            .AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED);
    map.put(
        "FDIC_CASH_SWEEP_ENROLL",
        EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum
            .FDIC_CASH_SWEEP_ENROLL);
    map.put(
        "FDIC_CASH_SWEEP_DECLINE",
        EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum
            .FDIC_CASH_SWEEP_DECLINE);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer
      extends StdSerializer<EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep> {

    protected _Serializer() {
      super(EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep.class);
    }

    @Override
    public void serialize(
        EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep value,
        JsonGenerator g,
        SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep> {

    protected _Deserializer() {
      super(EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep.class);
    }

    @Override
    public EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweep.of(v);
    }
  }

  public enum EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum {
    AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED("AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED"),
    FDIC_CASH_SWEEP_ENROLL("FDIC_CASH_SWEEP_ENROLL"),
    FDIC_CASH_SWEEP_DECLINE("FDIC_CASH_SWEEP_DECLINE"),
    ;

    private final String value;

    private EnrollmentForeignIndividualAccountEnrollmentMetadataFdicCashSweepEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
