/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Entity
 *
 * <p>investigation details on an entity
 */
public class Entity {
  /** Other names the entity is known by (Doing Business As) */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("dba_names")
  private Optional<? extends List<String>> dbaNames;

  /** Email addresses */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("email_addresses")
  private Optional<? extends List<String>> emailAddresses;

  /** Identification details including id value, and type (e.g. ein, lei) */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("identifications")
  private Optional<? extends List<EntityIdentification>> identifications;

  /** legal address */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("legal_address")
  private JsonNullable<? extends InvestigationLegalAddress> legalAddress;

  /** The legal name of the entity */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("legal_name")
  private Optional<String> legalName;

  /** mailing address */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("mailing_addresses")
  private Optional<? extends List<PostalAddress>> mailingAddresses;

  /**
   * The countries where an entity does business Two character region code, complies with
   * https://cldr.unicode.org/index Example values: "US", "CA"
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("operating_region_codes")
  private Optional<? extends List<String>> operatingRegionCodes;

  /** phone numbers */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("phone_numbers")
  private Optional<? extends List<String>> phoneNumbers;

  /**
   * Region of registration Two character region code, complies with https://cldr.unicode.org/index
   * Example values: "US", "CA"
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("registration_region")
  private Optional<String> registrationRegion;

  @JsonCreator
  public Entity(
      @JsonProperty("dba_names") Optional<? extends List<String>> dbaNames,
      @JsonProperty("email_addresses") Optional<? extends List<String>> emailAddresses,
      @JsonProperty("identifications")
          Optional<? extends List<EntityIdentification>> identifications,
      @JsonProperty("legal_address") JsonNullable<? extends InvestigationLegalAddress> legalAddress,
      @JsonProperty("legal_name") Optional<String> legalName,
      @JsonProperty("mailing_addresses") Optional<? extends List<PostalAddress>> mailingAddresses,
      @JsonProperty("operating_region_codes") Optional<? extends List<String>> operatingRegionCodes,
      @JsonProperty("phone_numbers") Optional<? extends List<String>> phoneNumbers,
      @JsonProperty("registration_region") Optional<String> registrationRegion) {
    Utils.checkNotNull(dbaNames, "dbaNames");
    Utils.checkNotNull(emailAddresses, "emailAddresses");
    Utils.checkNotNull(identifications, "identifications");
    Utils.checkNotNull(legalAddress, "legalAddress");
    Utils.checkNotNull(legalName, "legalName");
    Utils.checkNotNull(mailingAddresses, "mailingAddresses");
    Utils.checkNotNull(operatingRegionCodes, "operatingRegionCodes");
    Utils.checkNotNull(phoneNumbers, "phoneNumbers");
    Utils.checkNotNull(registrationRegion, "registrationRegion");
    this.dbaNames = dbaNames;
    this.emailAddresses = emailAddresses;
    this.identifications = identifications;
    this.legalAddress = legalAddress;
    this.legalName = legalName;
    this.mailingAddresses = mailingAddresses;
    this.operatingRegionCodes = operatingRegionCodes;
    this.phoneNumbers = phoneNumbers;
    this.registrationRegion = registrationRegion;
  }

  public Entity() {
    this(
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        JsonNullable.undefined(),
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        Optional.empty());
  }

  /** Other names the entity is known by (Doing Business As) */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> dbaNames() {
    return (Optional<List<String>>) dbaNames;
  }

  /** Email addresses */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> emailAddresses() {
    return (Optional<List<String>>) emailAddresses;
  }

  /** Identification details including id value, and type (e.g. ein, lei) */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<EntityIdentification>> identifications() {
    return (Optional<List<EntityIdentification>>) identifications;
  }

  /** legal address */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<InvestigationLegalAddress> legalAddress() {
    return (JsonNullable<InvestigationLegalAddress>) legalAddress;
  }

  /** The legal name of the entity */
  @JsonIgnore
  public Optional<String> legalName() {
    return legalName;
  }

  /** mailing address */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<PostalAddress>> mailingAddresses() {
    return (Optional<List<PostalAddress>>) mailingAddresses;
  }

  /**
   * The countries where an entity does business Two character region code, complies with
   * https://cldr.unicode.org/index Example values: "US", "CA"
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> operatingRegionCodes() {
    return (Optional<List<String>>) operatingRegionCodes;
  }

  /** phone numbers */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> phoneNumbers() {
    return (Optional<List<String>>) phoneNumbers;
  }

  /**
   * Region of registration Two character region code, complies with https://cldr.unicode.org/index
   * Example values: "US", "CA"
   */
  @JsonIgnore
  public Optional<String> registrationRegion() {
    return registrationRegion;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Other names the entity is known by (Doing Business As) */
  public Entity withDbaNames(List<String> dbaNames) {
    Utils.checkNotNull(dbaNames, "dbaNames");
    this.dbaNames = Optional.ofNullable(dbaNames);
    return this;
  }

  /** Other names the entity is known by (Doing Business As) */
  public Entity withDbaNames(Optional<? extends List<String>> dbaNames) {
    Utils.checkNotNull(dbaNames, "dbaNames");
    this.dbaNames = dbaNames;
    return this;
  }

  /** Email addresses */
  public Entity withEmailAddresses(List<String> emailAddresses) {
    Utils.checkNotNull(emailAddresses, "emailAddresses");
    this.emailAddresses = Optional.ofNullable(emailAddresses);
    return this;
  }

  /** Email addresses */
  public Entity withEmailAddresses(Optional<? extends List<String>> emailAddresses) {
    Utils.checkNotNull(emailAddresses, "emailAddresses");
    this.emailAddresses = emailAddresses;
    return this;
  }

  /** Identification details including id value, and type (e.g. ein, lei) */
  public Entity withIdentifications(List<EntityIdentification> identifications) {
    Utils.checkNotNull(identifications, "identifications");
    this.identifications = Optional.ofNullable(identifications);
    return this;
  }

  /** Identification details including id value, and type (e.g. ein, lei) */
  public Entity withIdentifications(
      Optional<? extends List<EntityIdentification>> identifications) {
    Utils.checkNotNull(identifications, "identifications");
    this.identifications = identifications;
    return this;
  }

  /** legal address */
  public Entity withLegalAddress(InvestigationLegalAddress legalAddress) {
    Utils.checkNotNull(legalAddress, "legalAddress");
    this.legalAddress = JsonNullable.of(legalAddress);
    return this;
  }

  /** legal address */
  public Entity withLegalAddress(JsonNullable<? extends InvestigationLegalAddress> legalAddress) {
    Utils.checkNotNull(legalAddress, "legalAddress");
    this.legalAddress = legalAddress;
    return this;
  }

  /** The legal name of the entity */
  public Entity withLegalName(String legalName) {
    Utils.checkNotNull(legalName, "legalName");
    this.legalName = Optional.ofNullable(legalName);
    return this;
  }

  /** The legal name of the entity */
  public Entity withLegalName(Optional<String> legalName) {
    Utils.checkNotNull(legalName, "legalName");
    this.legalName = legalName;
    return this;
  }

  /** mailing address */
  public Entity withMailingAddresses(List<PostalAddress> mailingAddresses) {
    Utils.checkNotNull(mailingAddresses, "mailingAddresses");
    this.mailingAddresses = Optional.ofNullable(mailingAddresses);
    return this;
  }

  /** mailing address */
  public Entity withMailingAddresses(Optional<? extends List<PostalAddress>> mailingAddresses) {
    Utils.checkNotNull(mailingAddresses, "mailingAddresses");
    this.mailingAddresses = mailingAddresses;
    return this;
  }

  /**
   * The countries where an entity does business Two character region code, complies with
   * https://cldr.unicode.org/index Example values: "US", "CA"
   */
  public Entity withOperatingRegionCodes(List<String> operatingRegionCodes) {
    Utils.checkNotNull(operatingRegionCodes, "operatingRegionCodes");
    this.operatingRegionCodes = Optional.ofNullable(operatingRegionCodes);
    return this;
  }

  /**
   * The countries where an entity does business Two character region code, complies with
   * https://cldr.unicode.org/index Example values: "US", "CA"
   */
  public Entity withOperatingRegionCodes(Optional<? extends List<String>> operatingRegionCodes) {
    Utils.checkNotNull(operatingRegionCodes, "operatingRegionCodes");
    this.operatingRegionCodes = operatingRegionCodes;
    return this;
  }

  /** phone numbers */
  public Entity withPhoneNumbers(List<String> phoneNumbers) {
    Utils.checkNotNull(phoneNumbers, "phoneNumbers");
    this.phoneNumbers = Optional.ofNullable(phoneNumbers);
    return this;
  }

  /** phone numbers */
  public Entity withPhoneNumbers(Optional<? extends List<String>> phoneNumbers) {
    Utils.checkNotNull(phoneNumbers, "phoneNumbers");
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  /**
   * Region of registration Two character region code, complies with https://cldr.unicode.org/index
   * Example values: "US", "CA"
   */
  public Entity withRegistrationRegion(String registrationRegion) {
    Utils.checkNotNull(registrationRegion, "registrationRegion");
    this.registrationRegion = Optional.ofNullable(registrationRegion);
    return this;
  }

  /**
   * Region of registration Two character region code, complies with https://cldr.unicode.org/index
   * Example values: "US", "CA"
   */
  public Entity withRegistrationRegion(Optional<String> registrationRegion) {
    Utils.checkNotNull(registrationRegion, "registrationRegion");
    this.registrationRegion = registrationRegion;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity other = (Entity) o;
    return Utils.enhancedDeepEquals(this.dbaNames, other.dbaNames)
        && Utils.enhancedDeepEquals(this.emailAddresses, other.emailAddresses)
        && Utils.enhancedDeepEquals(this.identifications, other.identifications)
        && Utils.enhancedDeepEquals(this.legalAddress, other.legalAddress)
        && Utils.enhancedDeepEquals(this.legalName, other.legalName)
        && Utils.enhancedDeepEquals(this.mailingAddresses, other.mailingAddresses)
        && Utils.enhancedDeepEquals(this.operatingRegionCodes, other.operatingRegionCodes)
        && Utils.enhancedDeepEquals(this.phoneNumbers, other.phoneNumbers)
        && Utils.enhancedDeepEquals(this.registrationRegion, other.registrationRegion);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(
        dbaNames,
        emailAddresses,
        identifications,
        legalAddress,
        legalName,
        mailingAddresses,
        operatingRegionCodes,
        phoneNumbers,
        registrationRegion);
  }

  @Override
  public String toString() {
    return Utils.toString(
        Entity.class,
        "dbaNames",
        dbaNames,
        "emailAddresses",
        emailAddresses,
        "identifications",
        identifications,
        "legalAddress",
        legalAddress,
        "legalName",
        legalName,
        "mailingAddresses",
        mailingAddresses,
        "operatingRegionCodes",
        operatingRegionCodes,
        "phoneNumbers",
        phoneNumbers,
        "registrationRegion",
        registrationRegion);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<? extends List<String>> dbaNames = Optional.empty();

    private Optional<? extends List<String>> emailAddresses = Optional.empty();

    private Optional<? extends List<EntityIdentification>> identifications = Optional.empty();

    private JsonNullable<? extends InvestigationLegalAddress> legalAddress =
        JsonNullable.undefined();

    private Optional<String> legalName = Optional.empty();

    private Optional<? extends List<PostalAddress>> mailingAddresses = Optional.empty();

    private Optional<? extends List<String>> operatingRegionCodes = Optional.empty();

    private Optional<? extends List<String>> phoneNumbers = Optional.empty();

    private Optional<String> registrationRegion = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Other names the entity is known by (Doing Business As) */
    public Builder dbaNames(List<String> dbaNames) {
      Utils.checkNotNull(dbaNames, "dbaNames");
      this.dbaNames = Optional.ofNullable(dbaNames);
      return this;
    }

    /** Other names the entity is known by (Doing Business As) */
    public Builder dbaNames(Optional<? extends List<String>> dbaNames) {
      Utils.checkNotNull(dbaNames, "dbaNames");
      this.dbaNames = dbaNames;
      return this;
    }

    /** Email addresses */
    public Builder emailAddresses(List<String> emailAddresses) {
      Utils.checkNotNull(emailAddresses, "emailAddresses");
      this.emailAddresses = Optional.ofNullable(emailAddresses);
      return this;
    }

    /** Email addresses */
    public Builder emailAddresses(Optional<? extends List<String>> emailAddresses) {
      Utils.checkNotNull(emailAddresses, "emailAddresses");
      this.emailAddresses = emailAddresses;
      return this;
    }

    /** Identification details including id value, and type (e.g. ein, lei) */
    public Builder identifications(List<EntityIdentification> identifications) {
      Utils.checkNotNull(identifications, "identifications");
      this.identifications = Optional.ofNullable(identifications);
      return this;
    }

    /** Identification details including id value, and type (e.g. ein, lei) */
    public Builder identifications(Optional<? extends List<EntityIdentification>> identifications) {
      Utils.checkNotNull(identifications, "identifications");
      this.identifications = identifications;
      return this;
    }

    /** legal address */
    public Builder legalAddress(InvestigationLegalAddress legalAddress) {
      Utils.checkNotNull(legalAddress, "legalAddress");
      this.legalAddress = JsonNullable.of(legalAddress);
      return this;
    }

    /** legal address */
    public Builder legalAddress(JsonNullable<? extends InvestigationLegalAddress> legalAddress) {
      Utils.checkNotNull(legalAddress, "legalAddress");
      this.legalAddress = legalAddress;
      return this;
    }

    /** The legal name of the entity */
    public Builder legalName(String legalName) {
      Utils.checkNotNull(legalName, "legalName");
      this.legalName = Optional.ofNullable(legalName);
      return this;
    }

    /** The legal name of the entity */
    public Builder legalName(Optional<String> legalName) {
      Utils.checkNotNull(legalName, "legalName");
      this.legalName = legalName;
      return this;
    }

    /** mailing address */
    public Builder mailingAddresses(List<PostalAddress> mailingAddresses) {
      Utils.checkNotNull(mailingAddresses, "mailingAddresses");
      this.mailingAddresses = Optional.ofNullable(mailingAddresses);
      return this;
    }

    /** mailing address */
    public Builder mailingAddresses(Optional<? extends List<PostalAddress>> mailingAddresses) {
      Utils.checkNotNull(mailingAddresses, "mailingAddresses");
      this.mailingAddresses = mailingAddresses;
      return this;
    }

    /**
     * The countries where an entity does business Two character region code, complies with
     * https://cldr.unicode.org/index Example values: "US", "CA"
     */
    public Builder operatingRegionCodes(List<String> operatingRegionCodes) {
      Utils.checkNotNull(operatingRegionCodes, "operatingRegionCodes");
      this.operatingRegionCodes = Optional.ofNullable(operatingRegionCodes);
      return this;
    }

    /**
     * The countries where an entity does business Two character region code, complies with
     * https://cldr.unicode.org/index Example values: "US", "CA"
     */
    public Builder operatingRegionCodes(Optional<? extends List<String>> operatingRegionCodes) {
      Utils.checkNotNull(operatingRegionCodes, "operatingRegionCodes");
      this.operatingRegionCodes = operatingRegionCodes;
      return this;
    }

    /** phone numbers */
    public Builder phoneNumbers(List<String> phoneNumbers) {
      Utils.checkNotNull(phoneNumbers, "phoneNumbers");
      this.phoneNumbers = Optional.ofNullable(phoneNumbers);
      return this;
    }

    /** phone numbers */
    public Builder phoneNumbers(Optional<? extends List<String>> phoneNumbers) {
      Utils.checkNotNull(phoneNumbers, "phoneNumbers");
      this.phoneNumbers = phoneNumbers;
      return this;
    }

    /**
     * Region of registration Two character region code, complies with
     * https://cldr.unicode.org/index Example values: "US", "CA"
     */
    public Builder registrationRegion(String registrationRegion) {
      Utils.checkNotNull(registrationRegion, "registrationRegion");
      this.registrationRegion = Optional.ofNullable(registrationRegion);
      return this;
    }

    /**
     * Region of registration Two character region code, complies with
     * https://cldr.unicode.org/index Example values: "US", "CA"
     */
    public Builder registrationRegion(Optional<String> registrationRegion) {
      Utils.checkNotNull(registrationRegion, "registrationRegion");
      this.registrationRegion = registrationRegion;
      return this;
    }

    public Entity build() {

      return new Entity(
          dbaNames,
          emailAddresses,
          identifications,
          legalAddress,
          legalName,
          mailingAddresses,
          operatingRegionCodes,
          phoneNumbers,
          registrationRegion);
    }
  }
}
