/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Entitlement
 *
 * <p>An Entitlement for an Account. Defines what the account is allowed to do.
 */
public class Entitlement {
  /** A friendly name for the entitlement used primarily for UI display */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("display_name")
  private Optional<String> displayName;

  /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("entitlement_code")
  private Optional<String> entitlementCode;

  /**
   * A system-generated reason about why the last modification occurred - typically due to an
   * enrollment or restriction event
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("last_modified_reason")
  private Optional<String> lastModifiedReason;

  /** The last time the underlying entitlement had its status updated */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("last_modified_time")
  private JsonNullable<OffsetDateTime> lastModifiedTime;

  /**
   * The entitlement above the subject; A model of status inheritance exists which provides context
   * on this value
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("parent_entitlements")
  private Optional<? extends List<String>> parentEntitlements;

  /**
   * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
   * disabled it, or DENIED if it has never before been GRANTED
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("state")
  private Optional<? extends EntitlementState> state;

  @JsonCreator
  public Entitlement(
      @JsonProperty("display_name") Optional<String> displayName,
      @JsonProperty("entitlement_code") Optional<String> entitlementCode,
      @JsonProperty("last_modified_reason") Optional<String> lastModifiedReason,
      @JsonProperty("last_modified_time") JsonNullable<OffsetDateTime> lastModifiedTime,
      @JsonProperty("parent_entitlements") Optional<? extends List<String>> parentEntitlements,
      @JsonProperty("state") Optional<? extends EntitlementState> state) {
    Utils.checkNotNull(displayName, "displayName");
    Utils.checkNotNull(entitlementCode, "entitlementCode");
    Utils.checkNotNull(lastModifiedReason, "lastModifiedReason");
    Utils.checkNotNull(lastModifiedTime, "lastModifiedTime");
    Utils.checkNotNull(parentEntitlements, "parentEntitlements");
    Utils.checkNotNull(state, "state");
    this.displayName = displayName;
    this.entitlementCode = entitlementCode;
    this.lastModifiedReason = lastModifiedReason;
    this.lastModifiedTime = lastModifiedTime;
    this.parentEntitlements = parentEntitlements;
    this.state = state;
  }

  public Entitlement() {
    this(
        Optional.empty(),
        Optional.empty(),
        Optional.empty(),
        JsonNullable.undefined(),
        Optional.empty(),
        Optional.empty());
  }

  /** A friendly name for the entitlement used primarily for UI display */
  @JsonIgnore
  public Optional<String> displayName() {
    return displayName;
  }

  /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
  @JsonIgnore
  public Optional<String> entitlementCode() {
    return entitlementCode;
  }

  /**
   * A system-generated reason about why the last modification occurred - typically due to an
   * enrollment or restriction event
   */
  @JsonIgnore
  public Optional<String> lastModifiedReason() {
    return lastModifiedReason;
  }

  /** The last time the underlying entitlement had its status updated */
  @JsonIgnore
  public JsonNullable<OffsetDateTime> lastModifiedTime() {
    return lastModifiedTime;
  }

  /**
   * The entitlement above the subject; A model of status inheritance exists which provides context
   * on this value
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> parentEntitlements() {
    return (Optional<List<String>>) parentEntitlements;
  }

  /**
   * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
   * disabled it, or DENIED if it has never before been GRANTED
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<EntitlementState> state() {
    return (Optional<EntitlementState>) state;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** A friendly name for the entitlement used primarily for UI display */
  public Entitlement withDisplayName(String displayName) {
    Utils.checkNotNull(displayName, "displayName");
    this.displayName = Optional.ofNullable(displayName);
    return this;
  }

  /** A friendly name for the entitlement used primarily for UI display */
  public Entitlement withDisplayName(Optional<String> displayName) {
    Utils.checkNotNull(displayName, "displayName");
    this.displayName = displayName;
    return this;
  }

  /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
  public Entitlement withEntitlementCode(String entitlementCode) {
    Utils.checkNotNull(entitlementCode, "entitlementCode");
    this.entitlementCode = Optional.ofNullable(entitlementCode);
    return this;
  }

  /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
  public Entitlement withEntitlementCode(Optional<String> entitlementCode) {
    Utils.checkNotNull(entitlementCode, "entitlementCode");
    this.entitlementCode = entitlementCode;
    return this;
  }

  /**
   * A system-generated reason about why the last modification occurred - typically due to an
   * enrollment or restriction event
   */
  public Entitlement withLastModifiedReason(String lastModifiedReason) {
    Utils.checkNotNull(lastModifiedReason, "lastModifiedReason");
    this.lastModifiedReason = Optional.ofNullable(lastModifiedReason);
    return this;
  }

  /**
   * A system-generated reason about why the last modification occurred - typically due to an
   * enrollment or restriction event
   */
  public Entitlement withLastModifiedReason(Optional<String> lastModifiedReason) {
    Utils.checkNotNull(lastModifiedReason, "lastModifiedReason");
    this.lastModifiedReason = lastModifiedReason;
    return this;
  }

  /** The last time the underlying entitlement had its status updated */
  public Entitlement withLastModifiedTime(OffsetDateTime lastModifiedTime) {
    Utils.checkNotNull(lastModifiedTime, "lastModifiedTime");
    this.lastModifiedTime = JsonNullable.of(lastModifiedTime);
    return this;
  }

  /** The last time the underlying entitlement had its status updated */
  public Entitlement withLastModifiedTime(JsonNullable<OffsetDateTime> lastModifiedTime) {
    Utils.checkNotNull(lastModifiedTime, "lastModifiedTime");
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

  /**
   * The entitlement above the subject; A model of status inheritance exists which provides context
   * on this value
   */
  public Entitlement withParentEntitlements(List<String> parentEntitlements) {
    Utils.checkNotNull(parentEntitlements, "parentEntitlements");
    this.parentEntitlements = Optional.ofNullable(parentEntitlements);
    return this;
  }

  /**
   * The entitlement above the subject; A model of status inheritance exists which provides context
   * on this value
   */
  public Entitlement withParentEntitlements(Optional<? extends List<String>> parentEntitlements) {
    Utils.checkNotNull(parentEntitlements, "parentEntitlements");
    this.parentEntitlements = parentEntitlements;
    return this;
  }

  /**
   * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
   * disabled it, or DENIED if it has never before been GRANTED
   */
  public Entitlement withState(EntitlementState state) {
    Utils.checkNotNull(state, "state");
    this.state = Optional.ofNullable(state);
    return this;
  }

  /**
   * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
   * disabled it, or DENIED if it has never before been GRANTED
   */
  public Entitlement withState(Optional<? extends EntitlementState> state) {
    Utils.checkNotNull(state, "state");
    this.state = state;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entitlement other = (Entitlement) o;
    return Utils.enhancedDeepEquals(this.displayName, other.displayName)
        && Utils.enhancedDeepEquals(this.entitlementCode, other.entitlementCode)
        && Utils.enhancedDeepEquals(this.lastModifiedReason, other.lastModifiedReason)
        && Utils.enhancedDeepEquals(this.lastModifiedTime, other.lastModifiedTime)
        && Utils.enhancedDeepEquals(this.parentEntitlements, other.parentEntitlements)
        && Utils.enhancedDeepEquals(this.state, other.state);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(
        displayName,
        entitlementCode,
        lastModifiedReason,
        lastModifiedTime,
        parentEntitlements,
        state);
  }

  @Override
  public String toString() {
    return Utils.toString(
        Entitlement.class,
        "displayName",
        displayName,
        "entitlementCode",
        entitlementCode,
        "lastModifiedReason",
        lastModifiedReason,
        "lastModifiedTime",
        lastModifiedTime,
        "parentEntitlements",
        parentEntitlements,
        "state",
        state);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<String> displayName = Optional.empty();

    private Optional<String> entitlementCode = Optional.empty();

    private Optional<String> lastModifiedReason = Optional.empty();

    private JsonNullable<OffsetDateTime> lastModifiedTime = JsonNullable.undefined();

    private Optional<? extends List<String>> parentEntitlements = Optional.empty();

    private Optional<? extends EntitlementState> state = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** A friendly name for the entitlement used primarily for UI display */
    public Builder displayName(String displayName) {
      Utils.checkNotNull(displayName, "displayName");
      this.displayName = Optional.ofNullable(displayName);
      return this;
    }

    /** A friendly name for the entitlement used primarily for UI display */
    public Builder displayName(Optional<String> displayName) {
      Utils.checkNotNull(displayName, "displayName");
      this.displayName = displayName;
      return this;
    }

    /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
    public Builder entitlementCode(String entitlementCode) {
      Utils.checkNotNull(entitlementCode, "entitlementCode");
      this.entitlementCode = Optional.ofNullable(entitlementCode);
      return this;
    }

    /** The enum value of the entitlement being described; e.g., BANKING_CHECK */
    public Builder entitlementCode(Optional<String> entitlementCode) {
      Utils.checkNotNull(entitlementCode, "entitlementCode");
      this.entitlementCode = entitlementCode;
      return this;
    }

    /**
     * A system-generated reason about why the last modification occurred - typically due to an
     * enrollment or restriction event
     */
    public Builder lastModifiedReason(String lastModifiedReason) {
      Utils.checkNotNull(lastModifiedReason, "lastModifiedReason");
      this.lastModifiedReason = Optional.ofNullable(lastModifiedReason);
      return this;
    }

    /**
     * A system-generated reason about why the last modification occurred - typically due to an
     * enrollment or restriction event
     */
    public Builder lastModifiedReason(Optional<String> lastModifiedReason) {
      Utils.checkNotNull(lastModifiedReason, "lastModifiedReason");
      this.lastModifiedReason = lastModifiedReason;
      return this;
    }

    /** The last time the underlying entitlement had its status updated */
    public Builder lastModifiedTime(OffsetDateTime lastModifiedTime) {
      Utils.checkNotNull(lastModifiedTime, "lastModifiedTime");
      this.lastModifiedTime = JsonNullable.of(lastModifiedTime);
      return this;
    }

    /** The last time the underlying entitlement had its status updated */
    public Builder lastModifiedTime(JsonNullable<OffsetDateTime> lastModifiedTime) {
      Utils.checkNotNull(lastModifiedTime, "lastModifiedTime");
      this.lastModifiedTime = lastModifiedTime;
      return this;
    }

    /**
     * The entitlement above the subject; A model of status inheritance exists which provides
     * context on this value
     */
    public Builder parentEntitlements(List<String> parentEntitlements) {
      Utils.checkNotNull(parentEntitlements, "parentEntitlements");
      this.parentEntitlements = Optional.ofNullable(parentEntitlements);
      return this;
    }

    /**
     * The entitlement above the subject; A model of status inheritance exists which provides
     * context on this value
     */
    public Builder parentEntitlements(Optional<? extends List<String>> parentEntitlements) {
      Utils.checkNotNull(parentEntitlements, "parentEntitlements");
      this.parentEntitlements = parentEntitlements;
      return this;
    }

    /**
     * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
     * disabled it, or DENIED if it has never before been GRANTED
     */
    public Builder state(EntitlementState state) {
      Utils.checkNotNull(state, "state");
      this.state = Optional.ofNullable(state);
      return this;
    }

    /**
     * GRANTED if it was activated via an enrollment, SUSPENDED if a restriction has temporarily
     * disabled it, or DENIED if it has never before been GRANTED
     */
    public Builder state(Optional<? extends EntitlementState> state) {
      Utils.checkNotNull(state, "state");
      this.state = state;
      return this;
    }

    public Entitlement build() {

      return new Entitlement(
          displayName,
          entitlementCode,
          lastModifiedReason,
          lastModifiedTime,
          parentEntitlements,
          state);
    }
  }
}
