/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * EntityIdentification
 *
 * <p>stores various Entity identification types
 */
public class EntityIdentification {
  /**
   * Administrative area that issued the identification For example, this can be a state, a
   * province, an oblast, or a prefecture.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("administrative_area")
  private Optional<String> administrativeArea;

  /**
   * One or more UUIDs from the documents api of the image(s) of the document that relates to the
   * identification for the person investigation.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("document_reference_ids")
  private Optional<? extends List<String>> documentReferenceIds;

  /**
   * Country that issued identification Two character region code, complies with
   * https://cldr.unicode.org/index
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("region_code")
  private Optional<String> regionCode;

  /**
   * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN` -
   * Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` - Legal
   * Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("type")
  private Optional<? extends EntityIdentificationType> type;

  /** Tax id value */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("value")
  private Optional<String> value;

  @JsonCreator
  public EntityIdentification(
      @JsonProperty("administrative_area") Optional<String> administrativeArea,
      @JsonProperty("document_reference_ids") Optional<? extends List<String>> documentReferenceIds,
      @JsonProperty("region_code") Optional<String> regionCode,
      @JsonProperty("type") Optional<? extends EntityIdentificationType> type,
      @JsonProperty("value") Optional<String> value) {
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    Utils.checkNotNull(documentReferenceIds, "documentReferenceIds");
    Utils.checkNotNull(regionCode, "regionCode");
    Utils.checkNotNull(type, "type");
    Utils.checkNotNull(value, "value");
    this.administrativeArea = administrativeArea;
    this.documentReferenceIds = documentReferenceIds;
    this.regionCode = regionCode;
    this.type = type;
    this.value = value;
  }

  public EntityIdentification() {
    this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
  }

  /**
   * Administrative area that issued the identification For example, this can be a state, a
   * province, an oblast, or a prefecture.
   */
  @JsonIgnore
  public Optional<String> administrativeArea() {
    return administrativeArea;
  }

  /**
   * One or more UUIDs from the documents api of the image(s) of the document that relates to the
   * identification for the person investigation.
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<String>> documentReferenceIds() {
    return (Optional<List<String>>) documentReferenceIds;
  }

  /**
   * Country that issued identification Two character region code, complies with
   * https://cldr.unicode.org/index
   */
  @JsonIgnore
  public Optional<String> regionCode() {
    return regionCode;
  }

  /**
   * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN` -
   * Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` - Legal
   * Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
   */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<EntityIdentificationType> type() {
    return (Optional<EntityIdentificationType>) type;
  }

  /** Tax id value */
  @JsonIgnore
  public Optional<String> value() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  /**
   * Administrative area that issued the identification For example, this can be a state, a
   * province, an oblast, or a prefecture.
   */
  public EntityIdentification withAdministrativeArea(String administrativeArea) {
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    this.administrativeArea = Optional.ofNullable(administrativeArea);
    return this;
  }

  /**
   * Administrative area that issued the identification For example, this can be a state, a
   * province, an oblast, or a prefecture.
   */
  public EntityIdentification withAdministrativeArea(Optional<String> administrativeArea) {
    Utils.checkNotNull(administrativeArea, "administrativeArea");
    this.administrativeArea = administrativeArea;
    return this;
  }

  /**
   * One or more UUIDs from the documents api of the image(s) of the document that relates to the
   * identification for the person investigation.
   */
  public EntityIdentification withDocumentReferenceIds(List<String> documentReferenceIds) {
    Utils.checkNotNull(documentReferenceIds, "documentReferenceIds");
    this.documentReferenceIds = Optional.ofNullable(documentReferenceIds);
    return this;
  }

  /**
   * One or more UUIDs from the documents api of the image(s) of the document that relates to the
   * identification for the person investigation.
   */
  public EntityIdentification withDocumentReferenceIds(
      Optional<? extends List<String>> documentReferenceIds) {
    Utils.checkNotNull(documentReferenceIds, "documentReferenceIds");
    this.documentReferenceIds = documentReferenceIds;
    return this;
  }

  /**
   * Country that issued identification Two character region code, complies with
   * https://cldr.unicode.org/index
   */
  public EntityIdentification withRegionCode(String regionCode) {
    Utils.checkNotNull(regionCode, "regionCode");
    this.regionCode = Optional.ofNullable(regionCode);
    return this;
  }

  /**
   * Country that issued identification Two character region code, complies with
   * https://cldr.unicode.org/index
   */
  public EntityIdentification withRegionCode(Optional<String> regionCode) {
    Utils.checkNotNull(regionCode, "regionCode");
    this.regionCode = regionCode;
    return this;
  }

  /**
   * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN` -
   * Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` - Legal
   * Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
   */
  public EntityIdentification withType(EntityIdentificationType type) {
    Utils.checkNotNull(type, "type");
    this.type = Optional.ofNullable(type);
    return this;
  }

  /**
   * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN` -
   * Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` - Legal
   * Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
   */
  public EntityIdentification withType(Optional<? extends EntityIdentificationType> type) {
    Utils.checkNotNull(type, "type");
    this.type = type;
    return this;
  }

  /** Tax id value */
  public EntityIdentification withValue(String value) {
    Utils.checkNotNull(value, "value");
    this.value = Optional.ofNullable(value);
    return this;
  }

  /** Tax id value */
  public EntityIdentification withValue(Optional<String> value) {
    Utils.checkNotNull(value, "value");
    this.value = value;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityIdentification other = (EntityIdentification) o;
    return Utils.enhancedDeepEquals(this.administrativeArea, other.administrativeArea)
        && Utils.enhancedDeepEquals(this.documentReferenceIds, other.documentReferenceIds)
        && Utils.enhancedDeepEquals(this.regionCode, other.regionCode)
        && Utils.enhancedDeepEquals(this.type, other.type)
        && Utils.enhancedDeepEquals(this.value, other.value);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(administrativeArea, documentReferenceIds, regionCode, type, value);
  }

  @Override
  public String toString() {
    return Utils.toString(
        EntityIdentification.class,
        "administrativeArea",
        administrativeArea,
        "documentReferenceIds",
        documentReferenceIds,
        "regionCode",
        regionCode,
        "type",
        type,
        "value",
        value);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<String> administrativeArea = Optional.empty();

    private Optional<? extends List<String>> documentReferenceIds = Optional.empty();

    private Optional<String> regionCode = Optional.empty();

    private Optional<? extends EntityIdentificationType> type = Optional.empty();

    private Optional<String> value = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /**
     * Administrative area that issued the identification For example, this can be a state, a
     * province, an oblast, or a prefecture.
     */
    public Builder administrativeArea(String administrativeArea) {
      Utils.checkNotNull(administrativeArea, "administrativeArea");
      this.administrativeArea = Optional.ofNullable(administrativeArea);
      return this;
    }

    /**
     * Administrative area that issued the identification For example, this can be a state, a
     * province, an oblast, or a prefecture.
     */
    public Builder administrativeArea(Optional<String> administrativeArea) {
      Utils.checkNotNull(administrativeArea, "administrativeArea");
      this.administrativeArea = administrativeArea;
      return this;
    }

    /**
     * One or more UUIDs from the documents api of the image(s) of the document that relates to the
     * identification for the person investigation.
     */
    public Builder documentReferenceIds(List<String> documentReferenceIds) {
      Utils.checkNotNull(documentReferenceIds, "documentReferenceIds");
      this.documentReferenceIds = Optional.ofNullable(documentReferenceIds);
      return this;
    }

    /**
     * One or more UUIDs from the documents api of the image(s) of the document that relates to the
     * identification for the person investigation.
     */
    public Builder documentReferenceIds(Optional<? extends List<String>> documentReferenceIds) {
      Utils.checkNotNull(documentReferenceIds, "documentReferenceIds");
      this.documentReferenceIds = documentReferenceIds;
      return this;
    }

    /**
     * Country that issued identification Two character region code, complies with
     * https://cldr.unicode.org/index
     */
    public Builder regionCode(String regionCode) {
      Utils.checkNotNull(regionCode, "regionCode");
      this.regionCode = Optional.ofNullable(regionCode);
      return this;
    }

    /**
     * Country that issued identification Two character region code, complies with
     * https://cldr.unicode.org/index
     */
    public Builder regionCode(Optional<String> regionCode) {
      Utils.checkNotNull(regionCode, "regionCode");
      this.regionCode = regionCode;
      return this;
    }

    /**
     * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN`
     * - Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` -
     * Legal Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
     */
    public Builder type(EntityIdentificationType type) {
      Utils.checkNotNull(type, "type");
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * The entity tax id type, one of: - `ID_ENTITY_TYPE_UNSPECIFIED` - Default/Null value. - `EIN`
     * - Employer Identification Number (US government issued, 9 digits, XX-XXXXXXX). - `LEI` -
     * Legal Entity Identifier (20 digit alphanumeric). - `DUNS` - Dun and Bradstreet number.
     */
    public Builder type(Optional<? extends EntityIdentificationType> type) {
      Utils.checkNotNull(type, "type");
      this.type = type;
      return this;
    }

    /** Tax id value */
    public Builder value(String value) {
      Utils.checkNotNull(value, "value");
      this.value = Optional.ofNullable(value);
      return this;
    }

    /** Tax id value */
    public Builder value(Optional<String> value) {
      Utils.checkNotNull(value, "value");
      this.value = value;
      return this;
    }

    public EntityIdentification build() {

      return new EntityIdentification(
          administrativeArea, documentReferenceIds, regionCode, type, value);
    }
  }
}
