/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/** ExternalAccountCreate - The external account information */
public class ExternalAccountCreate {

  /** The account identifier The account number for external communications */
  @JsonProperty("account_number")
  private String accountNumber;

  /** The NSCC brokerage / clearing house identifier */
  @JsonProperty("participant_number")
  private String participantNumber;

  @JsonCreator
  public ExternalAccountCreate(
      @JsonProperty("account_number") String accountNumber,
      @JsonProperty("participant_number") String participantNumber) {
    Utils.checkNotNull(accountNumber, "accountNumber");
    Utils.checkNotNull(participantNumber, "participantNumber");
    this.accountNumber = accountNumber;
    this.participantNumber = participantNumber;
  }

  /** The account identifier The account number for external communications */
  @JsonIgnore
  public String accountNumber() {
    return accountNumber;
  }

  /** The NSCC brokerage / clearing house identifier */
  @JsonIgnore
  public String participantNumber() {
    return participantNumber;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** The account identifier The account number for external communications */
  public ExternalAccountCreate withAccountNumber(String accountNumber) {
    Utils.checkNotNull(accountNumber, "accountNumber");
    this.accountNumber = accountNumber;
    return this;
  }

  /** The NSCC brokerage / clearing house identifier */
  public ExternalAccountCreate withParticipantNumber(String participantNumber) {
    Utils.checkNotNull(participantNumber, "participantNumber");
    this.participantNumber = participantNumber;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountCreate other = (ExternalAccountCreate) o;
    return Objects.deepEquals(this.accountNumber, other.accountNumber)
        && Objects.deepEquals(this.participantNumber, other.participantNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, participantNumber);
  }

  @Override
  public String toString() {
    return Utils.toString(
        ExternalAccountCreate.class,
        "accountNumber",
        accountNumber,
        "participantNumber",
        participantNumber);
  }

  public static final class Builder {

    private String accountNumber;

    private String participantNumber;

    private Builder() {
      // force use of static builder() method
    }

    /** The account identifier The account number for external communications */
    public Builder accountNumber(String accountNumber) {
      Utils.checkNotNull(accountNumber, "accountNumber");
      this.accountNumber = accountNumber;
      return this;
    }

    /** The NSCC brokerage / clearing house identifier */
    public Builder participantNumber(String participantNumber) {
      Utils.checkNotNull(participantNumber, "participantNumber");
      this.participantNumber = participantNumber;
      return this;
    }

    public ExternalAccountCreate build() {
      return new ExternalAccountCreate(accountNumber, participantNumber);
    }
  }
}
