/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * InvestorDocument
 *
 * <p>Fields specific to an investor document
 */
public class InvestorDocument {
  /** Identifies the account relevant to the document */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("account_id")
  private Optional<String> accountId;

  /** Describes the contents of a document and how it is used */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("document_type")
  private Optional<? extends DocumentInvestorDocumentDocumentType> documentType;

  /** Date that the related activities were processed */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("process_date")
  private JsonNullable<? extends DocumentProcessDate> processDate;

  @JsonCreator
  public InvestorDocument(
      @JsonProperty("account_id") Optional<String> accountId,
      @JsonProperty("document_type")
          Optional<? extends DocumentInvestorDocumentDocumentType> documentType,
      @JsonProperty("process_date") JsonNullable<? extends DocumentProcessDate> processDate) {
    Utils.checkNotNull(accountId, "accountId");
    Utils.checkNotNull(documentType, "documentType");
    Utils.checkNotNull(processDate, "processDate");
    this.accountId = accountId;
    this.documentType = documentType;
    this.processDate = processDate;
  }

  public InvestorDocument() {
    this(Optional.empty(), Optional.empty(), JsonNullable.undefined());
  }

  /** Identifies the account relevant to the document */
  @JsonIgnore
  public Optional<String> accountId() {
    return accountId;
  }

  /** Describes the contents of a document and how it is used */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<DocumentInvestorDocumentDocumentType> documentType() {
    return (Optional<DocumentInvestorDocumentDocumentType>) documentType;
  }

  /** Date that the related activities were processed */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<DocumentProcessDate> processDate() {
    return (JsonNullable<DocumentProcessDate>) processDate;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Identifies the account relevant to the document */
  public InvestorDocument withAccountId(String accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = Optional.ofNullable(accountId);
    return this;
  }

  /** Identifies the account relevant to the document */
  public InvestorDocument withAccountId(Optional<String> accountId) {
    Utils.checkNotNull(accountId, "accountId");
    this.accountId = accountId;
    return this;
  }

  /** Describes the contents of a document and how it is used */
  public InvestorDocument withDocumentType(DocumentInvestorDocumentDocumentType documentType) {
    Utils.checkNotNull(documentType, "documentType");
    this.documentType = Optional.ofNullable(documentType);
    return this;
  }

  /** Describes the contents of a document and how it is used */
  public InvestorDocument withDocumentType(
      Optional<? extends DocumentInvestorDocumentDocumentType> documentType) {
    Utils.checkNotNull(documentType, "documentType");
    this.documentType = documentType;
    return this;
  }

  /** Date that the related activities were processed */
  public InvestorDocument withProcessDate(DocumentProcessDate processDate) {
    Utils.checkNotNull(processDate, "processDate");
    this.processDate = JsonNullable.of(processDate);
    return this;
  }

  /** Date that the related activities were processed */
  public InvestorDocument withProcessDate(JsonNullable<? extends DocumentProcessDate> processDate) {
    Utils.checkNotNull(processDate, "processDate");
    this.processDate = processDate;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestorDocument other = (InvestorDocument) o;
    return Utils.enhancedDeepEquals(this.accountId, other.accountId)
        && Utils.enhancedDeepEquals(this.documentType, other.documentType)
        && Utils.enhancedDeepEquals(this.processDate, other.processDate);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(accountId, documentType, processDate);
  }

  @Override
  public String toString() {
    return Utils.toString(
        InvestorDocument.class,
        "accountId",
        accountId,
        "documentType",
        documentType,
        "processDate",
        processDate);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<String> accountId = Optional.empty();

    private Optional<? extends DocumentInvestorDocumentDocumentType> documentType =
        Optional.empty();

    private JsonNullable<? extends DocumentProcessDate> processDate = JsonNullable.undefined();

    private Builder() {
      // force use of static builder() method
    }

    /** Identifies the account relevant to the document */
    public Builder accountId(String accountId) {
      Utils.checkNotNull(accountId, "accountId");
      this.accountId = Optional.ofNullable(accountId);
      return this;
    }

    /** Identifies the account relevant to the document */
    public Builder accountId(Optional<String> accountId) {
      Utils.checkNotNull(accountId, "accountId");
      this.accountId = accountId;
      return this;
    }

    /** Describes the contents of a document and how it is used */
    public Builder documentType(DocumentInvestorDocumentDocumentType documentType) {
      Utils.checkNotNull(documentType, "documentType");
      this.documentType = Optional.ofNullable(documentType);
      return this;
    }

    /** Describes the contents of a document and how it is used */
    public Builder documentType(
        Optional<? extends DocumentInvestorDocumentDocumentType> documentType) {
      Utils.checkNotNull(documentType, "documentType");
      this.documentType = documentType;
      return this;
    }

    /** Date that the related activities were processed */
    public Builder processDate(DocumentProcessDate processDate) {
      Utils.checkNotNull(processDate, "processDate");
      this.processDate = JsonNullable.of(processDate);
      return this;
    }

    /** Date that the related activities were processed */
    public Builder processDate(JsonNullable<? extends DocumentProcessDate> processDate) {
      Utils.checkNotNull(processDate, "processDate");
      this.processDate = processDate;
      return this;
    }

    public InvestorDocument build() {

      return new InvestorDocument(accountId, documentType, processDate);
    }
  }
}
