/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * ListAssetTradingConfigsResponse
 *
 * <p>ListAssetTradingConfigsResponse is the response message for ListAssetTradingConfig method.
 */
public class ListAssetTradingConfigsResponse {
  /** The asset trading configs returned in the response. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("asset_trading_configs")
  private Optional<? extends List<AssetTradingConfig>> assetTradingConfigs;

  /**
   * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
   * retrieve the next page of results.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("next_page_token")
  private Optional<String> nextPageToken;

  @JsonCreator
  public ListAssetTradingConfigsResponse(
      @JsonProperty("asset_trading_configs")
          Optional<? extends List<AssetTradingConfig>> assetTradingConfigs,
      @JsonProperty("next_page_token") Optional<String> nextPageToken) {
    Utils.checkNotNull(assetTradingConfigs, "assetTradingConfigs");
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.assetTradingConfigs = assetTradingConfigs;
    this.nextPageToken = nextPageToken;
  }

  public ListAssetTradingConfigsResponse() {
    this(Optional.empty(), Optional.empty());
  }

  /** The asset trading configs returned in the response. */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<AssetTradingConfig>> assetTradingConfigs() {
    return (Optional<List<AssetTradingConfig>>) assetTradingConfigs;
  }

  /**
   * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
   * retrieve the next page of results.
   */
  @JsonIgnore
  public Optional<String> nextPageToken() {
    return nextPageToken;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** The asset trading configs returned in the response. */
  public ListAssetTradingConfigsResponse withAssetTradingConfigs(
      List<AssetTradingConfig> assetTradingConfigs) {
    Utils.checkNotNull(assetTradingConfigs, "assetTradingConfigs");
    this.assetTradingConfigs = Optional.ofNullable(assetTradingConfigs);
    return this;
  }

  /** The asset trading configs returned in the response. */
  public ListAssetTradingConfigsResponse withAssetTradingConfigs(
      Optional<? extends List<AssetTradingConfig>> assetTradingConfigs) {
    Utils.checkNotNull(assetTradingConfigs, "assetTradingConfigs");
    this.assetTradingConfigs = assetTradingConfigs;
    return this;
  }

  /**
   * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
   * retrieve the next page of results.
   */
  public ListAssetTradingConfigsResponse withNextPageToken(String nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = Optional.ofNullable(nextPageToken);
    return this;
  }

  /**
   * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
   * retrieve the next page of results.
   */
  public ListAssetTradingConfigsResponse withNextPageToken(Optional<String> nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAssetTradingConfigsResponse other = (ListAssetTradingConfigsResponse) o;
    return Utils.enhancedDeepEquals(this.assetTradingConfigs, other.assetTradingConfigs)
        && Utils.enhancedDeepEquals(this.nextPageToken, other.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(assetTradingConfigs, nextPageToken);
  }

  @Override
  public String toString() {
    return Utils.toString(
        ListAssetTradingConfigsResponse.class,
        "assetTradingConfigs",
        assetTradingConfigs,
        "nextPageToken",
        nextPageToken);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<? extends List<AssetTradingConfig>> assetTradingConfigs = Optional.empty();

    private Optional<String> nextPageToken = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** The asset trading configs returned in the response. */
    public Builder assetTradingConfigs(List<AssetTradingConfig> assetTradingConfigs) {
      Utils.checkNotNull(assetTradingConfigs, "assetTradingConfigs");
      this.assetTradingConfigs = Optional.ofNullable(assetTradingConfigs);
      return this;
    }

    /** The asset trading configs returned in the response. */
    public Builder assetTradingConfigs(
        Optional<? extends List<AssetTradingConfig>> assetTradingConfigs) {
      Utils.checkNotNull(assetTradingConfigs, "assetTradingConfigs");
      this.assetTradingConfigs = assetTradingConfigs;
      return this;
    }

    /**
     * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
     * retrieve the next page of results.
     */
    public Builder nextPageToken(String nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = Optional.ofNullable(nextPageToken);
      return this;
    }

    /**
     * The next_page_token value to include in a subsequent ListAssetTradingConfigs request to
     * retrieve the next page of results.
     */
    public Builder nextPageToken(Optional<String> nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = nextPageToken;
      return this;
    }

    public ListAssetTradingConfigsResponse build() {

      return new ListAssetTradingConfigsResponse(assetTradingConfigs, nextPageToken);
    }
  }
}
