/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** ListPushSubscriptionsResponse - A response to a list push subscriptions method */
public class ListPushSubscriptionsResponse {

  /** Page token used for pagination; Supplying a page token returns the next page of results */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("next_page_token")
  private Optional<String> nextPageToken;

  /** The returned collection of subscriptions */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("push_subscriptions")
  private Optional<? extends List<PushSubscription>> pushSubscriptions;

  @JsonCreator
  public ListPushSubscriptionsResponse(
      @JsonProperty("next_page_token") Optional<String> nextPageToken,
      @JsonProperty("push_subscriptions")
          Optional<? extends List<PushSubscription>> pushSubscriptions) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    Utils.checkNotNull(pushSubscriptions, "pushSubscriptions");
    this.nextPageToken = nextPageToken;
    this.pushSubscriptions = pushSubscriptions;
  }

  public ListPushSubscriptionsResponse() {
    this(Optional.empty(), Optional.empty());
  }

  /** Page token used for pagination; Supplying a page token returns the next page of results */
  @JsonIgnore
  public Optional<String> nextPageToken() {
    return nextPageToken;
  }

  /** The returned collection of subscriptions */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<PushSubscription>> pushSubscriptions() {
    return (Optional<List<PushSubscription>>) pushSubscriptions;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** Page token used for pagination; Supplying a page token returns the next page of results */
  public ListPushSubscriptionsResponse withNextPageToken(String nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = Optional.ofNullable(nextPageToken);
    return this;
  }

  /** Page token used for pagination; Supplying a page token returns the next page of results */
  public ListPushSubscriptionsResponse withNextPageToken(Optional<String> nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = nextPageToken;
    return this;
  }

  /** The returned collection of subscriptions */
  public ListPushSubscriptionsResponse withPushSubscriptions(
      List<PushSubscription> pushSubscriptions) {
    Utils.checkNotNull(pushSubscriptions, "pushSubscriptions");
    this.pushSubscriptions = Optional.ofNullable(pushSubscriptions);
    return this;
  }

  /** The returned collection of subscriptions */
  public ListPushSubscriptionsResponse withPushSubscriptions(
      Optional<? extends List<PushSubscription>> pushSubscriptions) {
    Utils.checkNotNull(pushSubscriptions, "pushSubscriptions");
    this.pushSubscriptions = pushSubscriptions;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListPushSubscriptionsResponse other = (ListPushSubscriptionsResponse) o;
    return Objects.deepEquals(this.nextPageToken, other.nextPageToken)
        && Objects.deepEquals(this.pushSubscriptions, other.pushSubscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, pushSubscriptions);
  }

  @Override
  public String toString() {
    return Utils.toString(
        ListPushSubscriptionsResponse.class,
        "nextPageToken",
        nextPageToken,
        "pushSubscriptions",
        pushSubscriptions);
  }

  public static final class Builder {

    private Optional<String> nextPageToken = Optional.empty();

    private Optional<? extends List<PushSubscription>> pushSubscriptions = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Page token used for pagination; Supplying a page token returns the next page of results */
    public Builder nextPageToken(String nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = Optional.ofNullable(nextPageToken);
      return this;
    }

    /** Page token used for pagination; Supplying a page token returns the next page of results */
    public Builder nextPageToken(Optional<String> nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = nextPageToken;
      return this;
    }

    /** The returned collection of subscriptions */
    public Builder pushSubscriptions(List<PushSubscription> pushSubscriptions) {
      Utils.checkNotNull(pushSubscriptions, "pushSubscriptions");
      this.pushSubscriptions = Optional.ofNullable(pushSubscriptions);
      return this;
    }

    /** The returned collection of subscriptions */
    public Builder pushSubscriptions(Optional<? extends List<PushSubscription>> pushSubscriptions) {
      Utils.checkNotNull(pushSubscriptions, "pushSubscriptions");
      this.pushSubscriptions = pushSubscriptions;
      return this;
    }

    public ListPushSubscriptionsResponse build() {
      return new ListPushSubscriptionsResponse(nextPageToken, pushSubscriptions);
    }
  }
}
