/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** ListTransfersResponse - Response to list existing transfers. */
public class ListTransfersResponse {

  /**
   * A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted,
   * there are no subsequent pages.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("next_page_token")
  private Optional<String> nextPageToken;

  /** transfers resulting from filter query */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("transfers")
  private Optional<? extends List<AcatsTransfer>> transfers;

  @JsonCreator
  public ListTransfersResponse(
      @JsonProperty("next_page_token") Optional<String> nextPageToken,
      @JsonProperty("transfers") Optional<? extends List<AcatsTransfer>> transfers) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    Utils.checkNotNull(transfers, "transfers");
    this.nextPageToken = nextPageToken;
    this.transfers = transfers;
  }

  public ListTransfersResponse() {
    this(Optional.empty(), Optional.empty());
  }

  /**
   * A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted,
   * there are no subsequent pages.
   */
  @JsonIgnore
  public Optional<String> nextPageToken() {
    return nextPageToken;
  }

  /** transfers resulting from filter query */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<AcatsTransfer>> transfers() {
    return (Optional<List<AcatsTransfer>>) transfers;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /**
   * A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted,
   * there are no subsequent pages.
   */
  public ListTransfersResponse withNextPageToken(String nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = Optional.ofNullable(nextPageToken);
    return this;
  }

  /**
   * A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted,
   * there are no subsequent pages.
   */
  public ListTransfersResponse withNextPageToken(Optional<String> nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = nextPageToken;
    return this;
  }

  /** transfers resulting from filter query */
  public ListTransfersResponse withTransfers(List<AcatsTransfer> transfers) {
    Utils.checkNotNull(transfers, "transfers");
    this.transfers = Optional.ofNullable(transfers);
    return this;
  }

  /** transfers resulting from filter query */
  public ListTransfersResponse withTransfers(Optional<? extends List<AcatsTransfer>> transfers) {
    Utils.checkNotNull(transfers, "transfers");
    this.transfers = transfers;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListTransfersResponse other = (ListTransfersResponse) o;
    return Objects.deepEquals(this.nextPageToken, other.nextPageToken)
        && Objects.deepEquals(this.transfers, other.transfers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, transfers);
  }

  @Override
  public String toString() {
    return Utils.toString(
        ListTransfersResponse.class, "nextPageToken", nextPageToken, "transfers", transfers);
  }

  public static final class Builder {

    private Optional<String> nextPageToken = Optional.empty();

    private Optional<? extends List<AcatsTransfer>> transfers = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /**
     * A token, which can be sent as `page_token` to retrieve the next page. If this field is
     * omitted, there are no subsequent pages.
     */
    public Builder nextPageToken(String nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = Optional.ofNullable(nextPageToken);
      return this;
    }

    /**
     * A token, which can be sent as `page_token` to retrieve the next page. If this field is
     * omitted, there are no subsequent pages.
     */
    public Builder nextPageToken(Optional<String> nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = nextPageToken;
      return this;
    }

    /** transfers resulting from filter query */
    public Builder transfers(List<AcatsTransfer> transfers) {
      Utils.checkNotNull(transfers, "transfers");
      this.transfers = Optional.ofNullable(transfers);
      return this;
    }

    /** transfers resulting from filter query */
    public Builder transfers(Optional<? extends List<AcatsTransfer>> transfers) {
      Utils.checkNotNull(transfers, "transfers");
      this.transfers = transfers;
      return this;
    }

    public ListTransfersResponse build() {
      return new ListTransfersResponse(nextPageToken, transfers);
    }
  }
}
