/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * OpenedOnBehalfOf
 *
 * <p>Trust account is opened on behalf of
 */
@JsonDeserialize(using = OpenedOnBehalfOf._Deserializer.class)
@JsonSerialize(using = OpenedOnBehalfOf._Serializer.class)
public class OpenedOnBehalfOf {

  public static final OpenedOnBehalfOf OPENED_ON_BEHALF_OF_UNSPECIFIED =
      new OpenedOnBehalfOf("OPENED_ON_BEHALF_OF_UNSPECIFIED");
  public static final OpenedOnBehalfOf PERSONAL_TRUST = new OpenedOnBehalfOf("PERSONAL_TRUST");
  public static final OpenedOnBehalfOf BUSINESS_TRUST = new OpenedOnBehalfOf("BUSINESS_TRUST");
  public static final OpenedOnBehalfOf THIRD_PARTY_ADMINISTRATOR =
      new OpenedOnBehalfOf("THIRD_PARTY_ADMINISTRATOR");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, OpenedOnBehalfOf> values = createValuesMap();
  private static final Map<String, OpenedOnBehalfOfEnum> enums = createEnumsMap();

  private final String value;

  private OpenedOnBehalfOf(String value) {
    this.value = value;
  }

  /**
   * Returns a OpenedOnBehalfOf with the given value. For a specific value the returned object will
   * always be a singleton so reference equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as OpenedOnBehalfOf
   */
  public static OpenedOnBehalfOf of(String value) {
    synchronized (OpenedOnBehalfOf.class) {
      return values.computeIfAbsent(value, v -> new OpenedOnBehalfOf(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<OpenedOnBehalfOfEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    OpenedOnBehalfOf other = (OpenedOnBehalfOf) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "OpenedOnBehalfOf [value=" + value + "]";
  }

  // return an array just like an enum
  public static OpenedOnBehalfOf[] values() {
    synchronized (OpenedOnBehalfOf.class) {
      return values.values().toArray(new OpenedOnBehalfOf[] {});
    }
  }

  private static final Map<String, OpenedOnBehalfOf> createValuesMap() {
    Map<String, OpenedOnBehalfOf> map = new LinkedHashMap<>();
    map.put("OPENED_ON_BEHALF_OF_UNSPECIFIED", OPENED_ON_BEHALF_OF_UNSPECIFIED);
    map.put("PERSONAL_TRUST", PERSONAL_TRUST);
    map.put("BUSINESS_TRUST", BUSINESS_TRUST);
    map.put("THIRD_PARTY_ADMINISTRATOR", THIRD_PARTY_ADMINISTRATOR);
    return map;
  }

  private static final Map<String, OpenedOnBehalfOfEnum> createEnumsMap() {
    Map<String, OpenedOnBehalfOfEnum> map = new HashMap<>();
    map.put(
        "OPENED_ON_BEHALF_OF_UNSPECIFIED", OpenedOnBehalfOfEnum.OPENED_ON_BEHALF_OF_UNSPECIFIED);
    map.put("PERSONAL_TRUST", OpenedOnBehalfOfEnum.PERSONAL_TRUST);
    map.put("BUSINESS_TRUST", OpenedOnBehalfOfEnum.BUSINESS_TRUST);
    map.put("THIRD_PARTY_ADMINISTRATOR", OpenedOnBehalfOfEnum.THIRD_PARTY_ADMINISTRATOR);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<OpenedOnBehalfOf> {

    protected _Serializer() {
      super(OpenedOnBehalfOf.class);
    }

    @Override
    public void serialize(OpenedOnBehalfOf value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<OpenedOnBehalfOf> {

    protected _Deserializer() {
      super(OpenedOnBehalfOf.class);
    }

    @Override
    public OpenedOnBehalfOf deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return OpenedOnBehalfOf.of(v);
    }
  }

  public enum OpenedOnBehalfOfEnum {
    OPENED_ON_BEHALF_OF_UNSPECIFIED("OPENED_ON_BEHALF_OF_UNSPECIFIED"),
    PERSONAL_TRUST("PERSONAL_TRUST"),
    BUSINESS_TRUST("BUSINESS_TRUST"),
    THIRD_PARTY_ADMINISTRATOR("THIRD_PARTY_ADMINISTRATOR"),
    ;

    private final String value;

    private OpenedOnBehalfOfEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
