/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * OptionAdjustment
 *
 * <p>Object containing metadata for option adjustments
 */
public class OptionAdjustment {
  /** Asset Id of the new security after the option adjustment was processed */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("disbursed_asset_id")
  private Optional<String> disbursedAssetId;

  /** Symbol of the new security after the option adjustment was processed */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("disbursed_symbol")
  private Optional<String> disbursedSymbol;

  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("target_asset_id")
  private Optional<String> targetAssetId;

  /** Symbol of the existing security before the option adjustment was processed */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("target_symbol")
  private Optional<String> targetSymbol;

  @JsonCreator
  public OptionAdjustment(
      @JsonProperty("disbursed_asset_id") Optional<String> disbursedAssetId,
      @JsonProperty("disbursed_symbol") Optional<String> disbursedSymbol,
      @JsonProperty("target_asset_id") Optional<String> targetAssetId,
      @JsonProperty("target_symbol") Optional<String> targetSymbol) {
    Utils.checkNotNull(disbursedAssetId, "disbursedAssetId");
    Utils.checkNotNull(disbursedSymbol, "disbursedSymbol");
    Utils.checkNotNull(targetAssetId, "targetAssetId");
    Utils.checkNotNull(targetSymbol, "targetSymbol");
    this.disbursedAssetId = disbursedAssetId;
    this.disbursedSymbol = disbursedSymbol;
    this.targetAssetId = targetAssetId;
    this.targetSymbol = targetSymbol;
  }

  public OptionAdjustment() {
    this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
  }

  /** Asset Id of the new security after the option adjustment was processed */
  @JsonIgnore
  public Optional<String> disbursedAssetId() {
    return disbursedAssetId;
  }

  /** Symbol of the new security after the option adjustment was processed */
  @JsonIgnore
  public Optional<String> disbursedSymbol() {
    return disbursedSymbol;
  }

  @JsonIgnore
  public Optional<String> targetAssetId() {
    return targetAssetId;
  }

  /** Symbol of the existing security before the option adjustment was processed */
  @JsonIgnore
  public Optional<String> targetSymbol() {
    return targetSymbol;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Asset Id of the new security after the option adjustment was processed */
  public OptionAdjustment withDisbursedAssetId(String disbursedAssetId) {
    Utils.checkNotNull(disbursedAssetId, "disbursedAssetId");
    this.disbursedAssetId = Optional.ofNullable(disbursedAssetId);
    return this;
  }

  /** Asset Id of the new security after the option adjustment was processed */
  public OptionAdjustment withDisbursedAssetId(Optional<String> disbursedAssetId) {
    Utils.checkNotNull(disbursedAssetId, "disbursedAssetId");
    this.disbursedAssetId = disbursedAssetId;
    return this;
  }

  /** Symbol of the new security after the option adjustment was processed */
  public OptionAdjustment withDisbursedSymbol(String disbursedSymbol) {
    Utils.checkNotNull(disbursedSymbol, "disbursedSymbol");
    this.disbursedSymbol = Optional.ofNullable(disbursedSymbol);
    return this;
  }

  /** Symbol of the new security after the option adjustment was processed */
  public OptionAdjustment withDisbursedSymbol(Optional<String> disbursedSymbol) {
    Utils.checkNotNull(disbursedSymbol, "disbursedSymbol");
    this.disbursedSymbol = disbursedSymbol;
    return this;
  }

  public OptionAdjustment withTargetAssetId(String targetAssetId) {
    Utils.checkNotNull(targetAssetId, "targetAssetId");
    this.targetAssetId = Optional.ofNullable(targetAssetId);
    return this;
  }

  public OptionAdjustment withTargetAssetId(Optional<String> targetAssetId) {
    Utils.checkNotNull(targetAssetId, "targetAssetId");
    this.targetAssetId = targetAssetId;
    return this;
  }

  /** Symbol of the existing security before the option adjustment was processed */
  public OptionAdjustment withTargetSymbol(String targetSymbol) {
    Utils.checkNotNull(targetSymbol, "targetSymbol");
    this.targetSymbol = Optional.ofNullable(targetSymbol);
    return this;
  }

  /** Symbol of the existing security before the option adjustment was processed */
  public OptionAdjustment withTargetSymbol(Optional<String> targetSymbol) {
    Utils.checkNotNull(targetSymbol, "targetSymbol");
    this.targetSymbol = targetSymbol;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptionAdjustment other = (OptionAdjustment) o;
    return Utils.enhancedDeepEquals(this.disbursedAssetId, other.disbursedAssetId)
        && Utils.enhancedDeepEquals(this.disbursedSymbol, other.disbursedSymbol)
        && Utils.enhancedDeepEquals(this.targetAssetId, other.targetAssetId)
        && Utils.enhancedDeepEquals(this.targetSymbol, other.targetSymbol);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(disbursedAssetId, disbursedSymbol, targetAssetId, targetSymbol);
  }

  @Override
  public String toString() {
    return Utils.toString(
        OptionAdjustment.class,
        "disbursedAssetId",
        disbursedAssetId,
        "disbursedSymbol",
        disbursedSymbol,
        "targetAssetId",
        targetAssetId,
        "targetSymbol",
        targetSymbol);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<String> disbursedAssetId = Optional.empty();

    private Optional<String> disbursedSymbol = Optional.empty();

    private Optional<String> targetAssetId = Optional.empty();

    private Optional<String> targetSymbol = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Asset Id of the new security after the option adjustment was processed */
    public Builder disbursedAssetId(String disbursedAssetId) {
      Utils.checkNotNull(disbursedAssetId, "disbursedAssetId");
      this.disbursedAssetId = Optional.ofNullable(disbursedAssetId);
      return this;
    }

    /** Asset Id of the new security after the option adjustment was processed */
    public Builder disbursedAssetId(Optional<String> disbursedAssetId) {
      Utils.checkNotNull(disbursedAssetId, "disbursedAssetId");
      this.disbursedAssetId = disbursedAssetId;
      return this;
    }

    /** Symbol of the new security after the option adjustment was processed */
    public Builder disbursedSymbol(String disbursedSymbol) {
      Utils.checkNotNull(disbursedSymbol, "disbursedSymbol");
      this.disbursedSymbol = Optional.ofNullable(disbursedSymbol);
      return this;
    }

    /** Symbol of the new security after the option adjustment was processed */
    public Builder disbursedSymbol(Optional<String> disbursedSymbol) {
      Utils.checkNotNull(disbursedSymbol, "disbursedSymbol");
      this.disbursedSymbol = disbursedSymbol;
      return this;
    }

    public Builder targetAssetId(String targetAssetId) {
      Utils.checkNotNull(targetAssetId, "targetAssetId");
      this.targetAssetId = Optional.ofNullable(targetAssetId);
      return this;
    }

    public Builder targetAssetId(Optional<String> targetAssetId) {
      Utils.checkNotNull(targetAssetId, "targetAssetId");
      this.targetAssetId = targetAssetId;
      return this;
    }

    /** Symbol of the existing security before the option adjustment was processed */
    public Builder targetSymbol(String targetSymbol) {
      Utils.checkNotNull(targetSymbol, "targetSymbol");
      this.targetSymbol = Optional.ofNullable(targetSymbol);
      return this;
    }

    /** Symbol of the existing security before the option adjustment was processed */
    public Builder targetSymbol(Optional<String> targetSymbol) {
      Utils.checkNotNull(targetSymbol, "targetSymbol");
      this.targetSymbol = targetSymbol;
      return this;
    }

    public OptionAdjustment build() {

      return new OptionAdjustment(disbursedAssetId, disbursedSymbol, targetAssetId, targetSymbol);
    }
  }
}
