/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * OptionOrderLegDirection
 *
 * <p>The computed direction for this leg. When `side` is BUY, `direction` will be DEBIT. When
 * `side` is SELL, `direction` will be CREDIT.
 */
@JsonDeserialize(using = OptionOrderLegDirection._Deserializer.class)
@JsonSerialize(using = OptionOrderLegDirection._Serializer.class)
public class OptionOrderLegDirection {

  public static final OptionOrderLegDirection DEBIT_CREDIT_TYPE_UNSPECIFIED =
      new OptionOrderLegDirection("DEBIT_CREDIT_TYPE_UNSPECIFIED");
  public static final OptionOrderLegDirection DEBIT = new OptionOrderLegDirection("DEBIT");
  public static final OptionOrderLegDirection CREDIT = new OptionOrderLegDirection("CREDIT");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, OptionOrderLegDirection> values = createValuesMap();
  private static final Map<String, OptionOrderLegDirectionEnum> enums = createEnumsMap();

  private final String value;

  private OptionOrderLegDirection(String value) {
    this.value = value;
  }

  /**
   * Returns a OptionOrderLegDirection with the given value. For a specific value the returned
   * object will always be a singleton so reference equality is satisfied when the values are the
   * same.
   *
   * @param value value to be wrapped as OptionOrderLegDirection
   */
  public static OptionOrderLegDirection of(String value) {
    synchronized (OptionOrderLegDirection.class) {
      return values.computeIfAbsent(value, v -> new OptionOrderLegDirection(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<OptionOrderLegDirectionEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    OptionOrderLegDirection other = (OptionOrderLegDirection) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "OptionOrderLegDirection [value=" + value + "]";
  }

  // return an array just like an enum
  public static OptionOrderLegDirection[] values() {
    synchronized (OptionOrderLegDirection.class) {
      return values.values().toArray(new OptionOrderLegDirection[] {});
    }
  }

  private static final Map<String, OptionOrderLegDirection> createValuesMap() {
    Map<String, OptionOrderLegDirection> map = new LinkedHashMap<>();
    map.put("DEBIT_CREDIT_TYPE_UNSPECIFIED", DEBIT_CREDIT_TYPE_UNSPECIFIED);
    map.put("DEBIT", DEBIT);
    map.put("CREDIT", CREDIT);
    return map;
  }

  private static final Map<String, OptionOrderLegDirectionEnum> createEnumsMap() {
    Map<String, OptionOrderLegDirectionEnum> map = new HashMap<>();
    map.put(
        "DEBIT_CREDIT_TYPE_UNSPECIFIED", OptionOrderLegDirectionEnum.DEBIT_CREDIT_TYPE_UNSPECIFIED);
    map.put("DEBIT", OptionOrderLegDirectionEnum.DEBIT);
    map.put("CREDIT", OptionOrderLegDirectionEnum.CREDIT);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<OptionOrderLegDirection> {

    protected _Serializer() {
      super(OptionOrderLegDirection.class);
    }

    @Override
    public void serialize(
        OptionOrderLegDirection value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<OptionOrderLegDirection> {

    protected _Deserializer() {
      super(OptionOrderLegDirection.class);
    }

    @Override
    public OptionOrderLegDirection deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return OptionOrderLegDirection.of(v);
    }
  }

  public enum OptionOrderLegDirectionEnum {
    DEBIT_CREDIT_TYPE_UNSPECIFIED("DEBIT_CREDIT_TYPE_UNSPECIFIED"),
    DEBIT("DEBIT"),
    CREDIT("CREDIT"),
    ;

    private final String value;

    private OptionOrderLegDirectionEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
