/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * PositionJournalIdentifierType
 *
 * <p>Identifier type for the asset being moved
 */
@JsonDeserialize(using = PositionJournalIdentifierType._Deserializer.class)
@JsonSerialize(using = PositionJournalIdentifierType._Serializer.class)
public class PositionJournalIdentifierType {

  public static final PositionJournalIdentifierType IDENTIFIER_TYPE_UNSPECIFIED =
      new PositionJournalIdentifierType("IDENTIFIER_TYPE_UNSPECIFIED");
  public static final PositionJournalIdentifierType CUSIP =
      new PositionJournalIdentifierType("CUSIP");
  public static final PositionJournalIdentifierType SYMBOL =
      new PositionJournalIdentifierType("SYMBOL");
  public static final PositionJournalIdentifierType ASSET_ID =
      new PositionJournalIdentifierType("ASSET_ID");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, PositionJournalIdentifierType> values = createValuesMap();
  private static final Map<String, PositionJournalIdentifierTypeEnum> enums = createEnumsMap();

  private final String value;

  private PositionJournalIdentifierType(String value) {
    this.value = value;
  }

  /**
   * Returns a PositionJournalIdentifierType with the given value. For a specific value the returned
   * object will always be a singleton so reference equality is satisfied when the values are the
   * same.
   *
   * @param value value to be wrapped as PositionJournalIdentifierType
   */
  public static PositionJournalIdentifierType of(String value) {
    synchronized (PositionJournalIdentifierType.class) {
      return values.computeIfAbsent(value, v -> new PositionJournalIdentifierType(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<PositionJournalIdentifierTypeEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    PositionJournalIdentifierType other = (PositionJournalIdentifierType) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "PositionJournalIdentifierType [value=" + value + "]";
  }

  // return an array just like an enum
  public static PositionJournalIdentifierType[] values() {
    synchronized (PositionJournalIdentifierType.class) {
      return values.values().toArray(new PositionJournalIdentifierType[] {});
    }
  }

  private static final Map<String, PositionJournalIdentifierType> createValuesMap() {
    Map<String, PositionJournalIdentifierType> map = new LinkedHashMap<>();
    map.put("IDENTIFIER_TYPE_UNSPECIFIED", IDENTIFIER_TYPE_UNSPECIFIED);
    map.put("CUSIP", CUSIP);
    map.put("SYMBOL", SYMBOL);
    map.put("ASSET_ID", ASSET_ID);
    return map;
  }

  private static final Map<String, PositionJournalIdentifierTypeEnum> createEnumsMap() {
    Map<String, PositionJournalIdentifierTypeEnum> map = new HashMap<>();
    map.put(
        "IDENTIFIER_TYPE_UNSPECIFIED",
        PositionJournalIdentifierTypeEnum.IDENTIFIER_TYPE_UNSPECIFIED);
    map.put("CUSIP", PositionJournalIdentifierTypeEnum.CUSIP);
    map.put("SYMBOL", PositionJournalIdentifierTypeEnum.SYMBOL);
    map.put("ASSET_ID", PositionJournalIdentifierTypeEnum.ASSET_ID);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<PositionJournalIdentifierType> {

    protected _Serializer() {
      super(PositionJournalIdentifierType.class);
    }

    @Override
    public void serialize(
        PositionJournalIdentifierType value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<PositionJournalIdentifierType> {

    protected _Deserializer() {
      super(PositionJournalIdentifierType.class);
    }

    @Override
    public PositionJournalIdentifierType deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return PositionJournalIdentifierType.of(v);
    }
  }

  public enum PositionJournalIdentifierTypeEnum {
    IDENTIFIER_TYPE_UNSPECIFIED("IDENTIFIER_TYPE_UNSPECIFIED"),
    CUSIP("CUSIP"),
    SYMBOL("SYMBOL"),
    ASSET_ID("ASSET_ID"),
    ;

    private final String value;

    private PositionJournalIdentifierTypeEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
