/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * RebookTradeResponseSide
 *
 * <p>Denotes if the trade is a SELL or a BUY.
 */
@JsonDeserialize(using = RebookTradeResponseSide._Deserializer.class)
@JsonSerialize(using = RebookTradeResponseSide._Serializer.class)
public class RebookTradeResponseSide {

  public static final RebookTradeResponseSide SIDE_UNSPECIFIED =
      new RebookTradeResponseSide("SIDE_UNSPECIFIED");
  public static final RebookTradeResponseSide BUY = new RebookTradeResponseSide("BUY");
  public static final RebookTradeResponseSide SELL = new RebookTradeResponseSide("SELL");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, RebookTradeResponseSide> values = createValuesMap();
  private static final Map<String, RebookTradeResponseSideEnum> enums = createEnumsMap();

  private final String value;

  private RebookTradeResponseSide(String value) {
    this.value = value;
  }

  /**
   * Returns a RebookTradeResponseSide with the given value. For a specific value the returned
   * object will always be a singleton so reference equality is satisfied when the values are the
   * same.
   *
   * @param value value to be wrapped as RebookTradeResponseSide
   */
  public static RebookTradeResponseSide of(String value) {
    synchronized (RebookTradeResponseSide.class) {
      return values.computeIfAbsent(value, v -> new RebookTradeResponseSide(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<RebookTradeResponseSideEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    RebookTradeResponseSide other = (RebookTradeResponseSide) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "RebookTradeResponseSide [value=" + value + "]";
  }

  // return an array just like an enum
  public static RebookTradeResponseSide[] values() {
    synchronized (RebookTradeResponseSide.class) {
      return values.values().toArray(new RebookTradeResponseSide[] {});
    }
  }

  private static final Map<String, RebookTradeResponseSide> createValuesMap() {
    Map<String, RebookTradeResponseSide> map = new LinkedHashMap<>();
    map.put("SIDE_UNSPECIFIED", SIDE_UNSPECIFIED);
    map.put("BUY", BUY);
    map.put("SELL", SELL);
    return map;
  }

  private static final Map<String, RebookTradeResponseSideEnum> createEnumsMap() {
    Map<String, RebookTradeResponseSideEnum> map = new HashMap<>();
    map.put("SIDE_UNSPECIFIED", RebookTradeResponseSideEnum.SIDE_UNSPECIFIED);
    map.put("BUY", RebookTradeResponseSideEnum.BUY);
    map.put("SELL", RebookTradeResponseSideEnum.SELL);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<RebookTradeResponseSide> {

    protected _Serializer() {
      super(RebookTradeResponseSide.class);
    }

    @Override
    public void serialize(
        RebookTradeResponseSide value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<RebookTradeResponseSide> {

    protected _Deserializer() {
      super(RebookTradeResponseSide.class);
    }

    @Override
    public RebookTradeResponseSide deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return RebookTradeResponseSide.of(v);
    }
  }

  public enum RebookTradeResponseSideEnum {
    SIDE_UNSPECIFIED("SIDE_UNSPECIFIED"),
    BUY("BUY"),
    SELL("SELL"),
    ;

    private final String value;

    private RebookTradeResponseSideEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
