/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * RebookTradeAllocationResponsePriceAdjustment - Price adjustment that will be applied to the net
 * price of the security.
 */
public class RebookTradeAllocationResponsePriceAdjustment {

  /** Total monetary value of the price_adjustment */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("price_adjustment_amount")
  private JsonNullable<? extends RebookTradeAllocationResponsePriceAdjustmentAmount>
      priceAdjustmentAmount;

  /** The type of price adjustment being applied by the broker to the net price of the security. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("price_adjustment_type")
  private Optional<? extends RebookTradeAllocationResponsePriceAdjustmentType> priceAdjustmentType;

  @JsonCreator
  public RebookTradeAllocationResponsePriceAdjustment(
      @JsonProperty("price_adjustment_amount")
          JsonNullable<? extends RebookTradeAllocationResponsePriceAdjustmentAmount>
              priceAdjustmentAmount,
      @JsonProperty("price_adjustment_type")
          Optional<? extends RebookTradeAllocationResponsePriceAdjustmentType>
              priceAdjustmentType) {
    Utils.checkNotNull(priceAdjustmentAmount, "priceAdjustmentAmount");
    Utils.checkNotNull(priceAdjustmentType, "priceAdjustmentType");
    this.priceAdjustmentAmount = priceAdjustmentAmount;
    this.priceAdjustmentType = priceAdjustmentType;
  }

  public RebookTradeAllocationResponsePriceAdjustment() {
    this(JsonNullable.undefined(), Optional.empty());
  }

  /** Total monetary value of the price_adjustment */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public JsonNullable<RebookTradeAllocationResponsePriceAdjustmentAmount> priceAdjustmentAmount() {
    return (JsonNullable<RebookTradeAllocationResponsePriceAdjustmentAmount>) priceAdjustmentAmount;
  }

  /** The type of price adjustment being applied by the broker to the net price of the security. */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<RebookTradeAllocationResponsePriceAdjustmentType> priceAdjustmentType() {
    return (Optional<RebookTradeAllocationResponsePriceAdjustmentType>) priceAdjustmentType;
  }

  public static final Builder builder() {
    return new Builder();
  }

  /** Total monetary value of the price_adjustment */
  public RebookTradeAllocationResponsePriceAdjustment withPriceAdjustmentAmount(
      RebookTradeAllocationResponsePriceAdjustmentAmount priceAdjustmentAmount) {
    Utils.checkNotNull(priceAdjustmentAmount, "priceAdjustmentAmount");
    this.priceAdjustmentAmount = JsonNullable.of(priceAdjustmentAmount);
    return this;
  }

  /** Total monetary value of the price_adjustment */
  public RebookTradeAllocationResponsePriceAdjustment withPriceAdjustmentAmount(
      JsonNullable<? extends RebookTradeAllocationResponsePriceAdjustmentAmount>
          priceAdjustmentAmount) {
    Utils.checkNotNull(priceAdjustmentAmount, "priceAdjustmentAmount");
    this.priceAdjustmentAmount = priceAdjustmentAmount;
    return this;
  }

  /** The type of price adjustment being applied by the broker to the net price of the security. */
  public RebookTradeAllocationResponsePriceAdjustment withPriceAdjustmentType(
      RebookTradeAllocationResponsePriceAdjustmentType priceAdjustmentType) {
    Utils.checkNotNull(priceAdjustmentType, "priceAdjustmentType");
    this.priceAdjustmentType = Optional.ofNullable(priceAdjustmentType);
    return this;
  }

  /** The type of price adjustment being applied by the broker to the net price of the security. */
  public RebookTradeAllocationResponsePriceAdjustment withPriceAdjustmentType(
      Optional<? extends RebookTradeAllocationResponsePriceAdjustmentType> priceAdjustmentType) {
    Utils.checkNotNull(priceAdjustmentType, "priceAdjustmentType");
    this.priceAdjustmentType = priceAdjustmentType;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RebookTradeAllocationResponsePriceAdjustment other =
        (RebookTradeAllocationResponsePriceAdjustment) o;
    return Objects.deepEquals(this.priceAdjustmentAmount, other.priceAdjustmentAmount)
        && Objects.deepEquals(this.priceAdjustmentType, other.priceAdjustmentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priceAdjustmentAmount, priceAdjustmentType);
  }

  @Override
  public String toString() {
    return Utils.toString(
        RebookTradeAllocationResponsePriceAdjustment.class,
        "priceAdjustmentAmount",
        priceAdjustmentAmount,
        "priceAdjustmentType",
        priceAdjustmentType);
  }

  public static final class Builder {

    private JsonNullable<? extends RebookTradeAllocationResponsePriceAdjustmentAmount>
        priceAdjustmentAmount = JsonNullable.undefined();

    private Optional<? extends RebookTradeAllocationResponsePriceAdjustmentType>
        priceAdjustmentType = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** Total monetary value of the price_adjustment */
    public Builder priceAdjustmentAmount(
        RebookTradeAllocationResponsePriceAdjustmentAmount priceAdjustmentAmount) {
      Utils.checkNotNull(priceAdjustmentAmount, "priceAdjustmentAmount");
      this.priceAdjustmentAmount = JsonNullable.of(priceAdjustmentAmount);
      return this;
    }

    /** Total monetary value of the price_adjustment */
    public Builder priceAdjustmentAmount(
        JsonNullable<? extends RebookTradeAllocationResponsePriceAdjustmentAmount>
            priceAdjustmentAmount) {
      Utils.checkNotNull(priceAdjustmentAmount, "priceAdjustmentAmount");
      this.priceAdjustmentAmount = priceAdjustmentAmount;
      return this;
    }

    /**
     * The type of price adjustment being applied by the broker to the net price of the security.
     */
    public Builder priceAdjustmentType(
        RebookTradeAllocationResponsePriceAdjustmentType priceAdjustmentType) {
      Utils.checkNotNull(priceAdjustmentType, "priceAdjustmentType");
      this.priceAdjustmentType = Optional.ofNullable(priceAdjustmentType);
      return this;
    }

    /**
     * The type of price adjustment being applied by the broker to the net price of the security.
     */
    public Builder priceAdjustmentType(
        Optional<? extends RebookTradeAllocationResponsePriceAdjustmentType> priceAdjustmentType) {
      Utils.checkNotNull(priceAdjustmentType, "priceAdjustmentType");
      this.priceAdjustmentType = priceAdjustmentType;
      return this;
    }

    public RebookTradeAllocationResponsePriceAdjustment build() {
      return new RebookTradeAllocationResponsePriceAdjustment(
          priceAdjustmentAmount, priceAdjustmentType);
    }
  }
}
