/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Receive
 *
 * <p>Object containing metadata for receive events
 */
public class Receive {
  @JsonCreator
  public Receive() {}

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash();
  }

  @Override
  public String toString() {
    return Utils.toString(Receive.class);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Builder() {
      // force use of static builder() method
    }

    public Receive build() {

      return new Receive();
    }
  }
}
