/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * RetirementDistributionCreate
 *
 * <p>A distribution from a retirement account.
 */
public class RetirementDistributionCreate {
  /** A representation of a tax withholding. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("federal_tax_withholding")
  private Optional<? extends RetirementDistributionTaxWithholdingCreate> federalTaxWithholding;

  /**
   * The institution receiving retirement funds when performing a transfer to an identical
   * retirement account type at a different financial institution. This is required for check and
   * wire withdrawals because we can't always identify the institution using the transfer
   * instructions. For cash journals this value will default to "Apex Clearing", regardless of what
   * is passed in here
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("receiving_institution")
  private Optional<String> receivingInstitution;

  /** A representation of a tax withholding. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("state_tax_withholding")
  private Optional<? extends RetirementDistributionTaxWithholdingCreate> stateTaxWithholding;

  /** Whether or not this distribution has a state withholding waiver. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("state_withholding_waiver")
  private Optional<Boolean> stateWithholdingWaiver;

  /** The type of retirement distribution. */
  @JsonProperty("type")
  private RetirementDistributionCreateType type;

  @JsonCreator
  public RetirementDistributionCreate(
      @JsonProperty("federal_tax_withholding")
          Optional<? extends RetirementDistributionTaxWithholdingCreate> federalTaxWithholding,
      @JsonProperty("receiving_institution") Optional<String> receivingInstitution,
      @JsonProperty("state_tax_withholding")
          Optional<? extends RetirementDistributionTaxWithholdingCreate> stateTaxWithholding,
      @JsonProperty("state_withholding_waiver") Optional<Boolean> stateWithholdingWaiver,
      @JsonProperty("type") RetirementDistributionCreateType type) {
    Utils.checkNotNull(federalTaxWithholding, "federalTaxWithholding");
    Utils.checkNotNull(receivingInstitution, "receivingInstitution");
    Utils.checkNotNull(stateTaxWithholding, "stateTaxWithholding");
    Utils.checkNotNull(stateWithholdingWaiver, "stateWithholdingWaiver");
    Utils.checkNotNull(type, "type");
    this.federalTaxWithholding = federalTaxWithholding;
    this.receivingInstitution = receivingInstitution;
    this.stateTaxWithholding = stateTaxWithholding;
    this.stateWithholdingWaiver = stateWithholdingWaiver;
    this.type = type;
  }

  public RetirementDistributionCreate(RetirementDistributionCreateType type) {
    this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), type);
  }

  /** A representation of a tax withholding. */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<RetirementDistributionTaxWithholdingCreate> federalTaxWithholding() {
    return (Optional<RetirementDistributionTaxWithholdingCreate>) federalTaxWithholding;
  }

  /**
   * The institution receiving retirement funds when performing a transfer to an identical
   * retirement account type at a different financial institution. This is required for check and
   * wire withdrawals because we can't always identify the institution using the transfer
   * instructions. For cash journals this value will default to "Apex Clearing", regardless of what
   * is passed in here
   */
  @JsonIgnore
  public Optional<String> receivingInstitution() {
    return receivingInstitution;
  }

  /** A representation of a tax withholding. */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<RetirementDistributionTaxWithholdingCreate> stateTaxWithholding() {
    return (Optional<RetirementDistributionTaxWithholdingCreate>) stateTaxWithholding;
  }

  /** Whether or not this distribution has a state withholding waiver. */
  @JsonIgnore
  public Optional<Boolean> stateWithholdingWaiver() {
    return stateWithholdingWaiver;
  }

  /** The type of retirement distribution. */
  @JsonIgnore
  public RetirementDistributionCreateType type() {
    return type;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** A representation of a tax withholding. */
  public RetirementDistributionCreate withFederalTaxWithholding(
      RetirementDistributionTaxWithholdingCreate federalTaxWithholding) {
    Utils.checkNotNull(federalTaxWithholding, "federalTaxWithholding");
    this.federalTaxWithholding = Optional.ofNullable(federalTaxWithholding);
    return this;
  }

  /** A representation of a tax withholding. */
  public RetirementDistributionCreate withFederalTaxWithholding(
      Optional<? extends RetirementDistributionTaxWithholdingCreate> federalTaxWithholding) {
    Utils.checkNotNull(federalTaxWithholding, "federalTaxWithholding");
    this.federalTaxWithholding = federalTaxWithholding;
    return this;
  }

  /**
   * The institution receiving retirement funds when performing a transfer to an identical
   * retirement account type at a different financial institution. This is required for check and
   * wire withdrawals because we can't always identify the institution using the transfer
   * instructions. For cash journals this value will default to "Apex Clearing", regardless of what
   * is passed in here
   */
  public RetirementDistributionCreate withReceivingInstitution(String receivingInstitution) {
    Utils.checkNotNull(receivingInstitution, "receivingInstitution");
    this.receivingInstitution = Optional.ofNullable(receivingInstitution);
    return this;
  }

  /**
   * The institution receiving retirement funds when performing a transfer to an identical
   * retirement account type at a different financial institution. This is required for check and
   * wire withdrawals because we can't always identify the institution using the transfer
   * instructions. For cash journals this value will default to "Apex Clearing", regardless of what
   * is passed in here
   */
  public RetirementDistributionCreate withReceivingInstitution(
      Optional<String> receivingInstitution) {
    Utils.checkNotNull(receivingInstitution, "receivingInstitution");
    this.receivingInstitution = receivingInstitution;
    return this;
  }

  /** A representation of a tax withholding. */
  public RetirementDistributionCreate withStateTaxWithholding(
      RetirementDistributionTaxWithholdingCreate stateTaxWithholding) {
    Utils.checkNotNull(stateTaxWithholding, "stateTaxWithholding");
    this.stateTaxWithholding = Optional.ofNullable(stateTaxWithholding);
    return this;
  }

  /** A representation of a tax withholding. */
  public RetirementDistributionCreate withStateTaxWithholding(
      Optional<? extends RetirementDistributionTaxWithholdingCreate> stateTaxWithholding) {
    Utils.checkNotNull(stateTaxWithholding, "stateTaxWithholding");
    this.stateTaxWithholding = stateTaxWithholding;
    return this;
  }

  /** Whether or not this distribution has a state withholding waiver. */
  public RetirementDistributionCreate withStateWithholdingWaiver(boolean stateWithholdingWaiver) {
    Utils.checkNotNull(stateWithholdingWaiver, "stateWithholdingWaiver");
    this.stateWithholdingWaiver = Optional.ofNullable(stateWithholdingWaiver);
    return this;
  }

  /** Whether or not this distribution has a state withholding waiver. */
  public RetirementDistributionCreate withStateWithholdingWaiver(
      Optional<Boolean> stateWithholdingWaiver) {
    Utils.checkNotNull(stateWithholdingWaiver, "stateWithholdingWaiver");
    this.stateWithholdingWaiver = stateWithholdingWaiver;
    return this;
  }

  /** The type of retirement distribution. */
  public RetirementDistributionCreate withType(RetirementDistributionCreateType type) {
    Utils.checkNotNull(type, "type");
    this.type = type;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetirementDistributionCreate other = (RetirementDistributionCreate) o;
    return Utils.enhancedDeepEquals(this.federalTaxWithholding, other.federalTaxWithholding)
        && Utils.enhancedDeepEquals(this.receivingInstitution, other.receivingInstitution)
        && Utils.enhancedDeepEquals(this.stateTaxWithholding, other.stateTaxWithholding)
        && Utils.enhancedDeepEquals(this.stateWithholdingWaiver, other.stateWithholdingWaiver)
        && Utils.enhancedDeepEquals(this.type, other.type);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(
        federalTaxWithholding,
        receivingInstitution,
        stateTaxWithholding,
        stateWithholdingWaiver,
        type);
  }

  @Override
  public String toString() {
    return Utils.toString(
        RetirementDistributionCreate.class,
        "federalTaxWithholding",
        federalTaxWithholding,
        "receivingInstitution",
        receivingInstitution,
        "stateTaxWithholding",
        stateTaxWithholding,
        "stateWithholdingWaiver",
        stateWithholdingWaiver,
        "type",
        type);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<? extends RetirementDistributionTaxWithholdingCreate> federalTaxWithholding =
        Optional.empty();

    private Optional<String> receivingInstitution = Optional.empty();

    private Optional<? extends RetirementDistributionTaxWithholdingCreate> stateTaxWithholding =
        Optional.empty();

    private Optional<Boolean> stateWithholdingWaiver = Optional.empty();

    private RetirementDistributionCreateType type;

    private Builder() {
      // force use of static builder() method
    }

    /** A representation of a tax withholding. */
    public Builder federalTaxWithholding(
        RetirementDistributionTaxWithholdingCreate federalTaxWithholding) {
      Utils.checkNotNull(federalTaxWithholding, "federalTaxWithholding");
      this.federalTaxWithholding = Optional.ofNullable(federalTaxWithholding);
      return this;
    }

    /** A representation of a tax withholding. */
    public Builder federalTaxWithholding(
        Optional<? extends RetirementDistributionTaxWithholdingCreate> federalTaxWithholding) {
      Utils.checkNotNull(federalTaxWithholding, "federalTaxWithholding");
      this.federalTaxWithholding = federalTaxWithholding;
      return this;
    }

    /**
     * The institution receiving retirement funds when performing a transfer to an identical
     * retirement account type at a different financial institution. This is required for check and
     * wire withdrawals because we can't always identify the institution using the transfer
     * instructions. For cash journals this value will default to "Apex Clearing", regardless of
     * what is passed in here
     */
    public Builder receivingInstitution(String receivingInstitution) {
      Utils.checkNotNull(receivingInstitution, "receivingInstitution");
      this.receivingInstitution = Optional.ofNullable(receivingInstitution);
      return this;
    }

    /**
     * The institution receiving retirement funds when performing a transfer to an identical
     * retirement account type at a different financial institution. This is required for check and
     * wire withdrawals because we can't always identify the institution using the transfer
     * instructions. For cash journals this value will default to "Apex Clearing", regardless of
     * what is passed in here
     */
    public Builder receivingInstitution(Optional<String> receivingInstitution) {
      Utils.checkNotNull(receivingInstitution, "receivingInstitution");
      this.receivingInstitution = receivingInstitution;
      return this;
    }

    /** A representation of a tax withholding. */
    public Builder stateTaxWithholding(
        RetirementDistributionTaxWithholdingCreate stateTaxWithholding) {
      Utils.checkNotNull(stateTaxWithholding, "stateTaxWithholding");
      this.stateTaxWithholding = Optional.ofNullable(stateTaxWithholding);
      return this;
    }

    /** A representation of a tax withholding. */
    public Builder stateTaxWithholding(
        Optional<? extends RetirementDistributionTaxWithholdingCreate> stateTaxWithholding) {
      Utils.checkNotNull(stateTaxWithholding, "stateTaxWithholding");
      this.stateTaxWithholding = stateTaxWithholding;
      return this;
    }

    /** Whether or not this distribution has a state withholding waiver. */
    public Builder stateWithholdingWaiver(boolean stateWithholdingWaiver) {
      Utils.checkNotNull(stateWithholdingWaiver, "stateWithholdingWaiver");
      this.stateWithholdingWaiver = Optional.ofNullable(stateWithholdingWaiver);
      return this;
    }

    /** Whether or not this distribution has a state withholding waiver. */
    public Builder stateWithholdingWaiver(Optional<Boolean> stateWithholdingWaiver) {
      Utils.checkNotNull(stateWithholdingWaiver, "stateWithholdingWaiver");
      this.stateWithholdingWaiver = stateWithholdingWaiver;
      return this;
    }

    /** The type of retirement distribution. */
    public Builder type(RetirementDistributionCreateType type) {
      Utils.checkNotNull(type, "type");
      this.type = type;
      return this;
    }

    public RetirementDistributionCreate build() {

      return new RetirementDistributionCreate(
          federalTaxWithholding,
          receivingInstitution,
          stateTaxWithholding,
          stateWithholdingWaiver,
          type);
    }
  }
}
