/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * ScheduledRetirementContributionCreateType
 *
 * <p>The type of retirement contribution.
 */
@JsonDeserialize(using = ScheduledRetirementContributionCreateType._Deserializer.class)
@JsonSerialize(using = ScheduledRetirementContributionCreateType._Serializer.class)
public class ScheduledRetirementContributionCreateType {

  public static final ScheduledRetirementContributionCreateType TYPE_UNSPECIFIED =
      new ScheduledRetirementContributionCreateType("TYPE_UNSPECIFIED");
  public static final ScheduledRetirementContributionCreateType REGULAR =
      new ScheduledRetirementContributionCreateType("REGULAR");
  public static final ScheduledRetirementContributionCreateType EMPLOYEE =
      new ScheduledRetirementContributionCreateType("EMPLOYEE");
  public static final ScheduledRetirementContributionCreateType EMPLOYER =
      new ScheduledRetirementContributionCreateType("EMPLOYER");
  public static final ScheduledRetirementContributionCreateType RECHARACTERIZATION =
      new ScheduledRetirementContributionCreateType("RECHARACTERIZATION");
  public static final ScheduledRetirementContributionCreateType ROLLOVER60_DAY =
      new ScheduledRetirementContributionCreateType("ROLLOVER_60_DAY");
  public static final ScheduledRetirementContributionCreateType ROLLOVER_DIRECT =
      new ScheduledRetirementContributionCreateType("ROLLOVER_DIRECT");
  public static final ScheduledRetirementContributionCreateType TRANSFER =
      new ScheduledRetirementContributionCreateType("TRANSFER");
  public static final ScheduledRetirementContributionCreateType TRUSTEE_FEE =
      new ScheduledRetirementContributionCreateType("TRUSTEE_FEE");
  public static final ScheduledRetirementContributionCreateType CONVERSION =
      new ScheduledRetirementContributionCreateType("CONVERSION");
  public static final ScheduledRetirementContributionCreateType REPAYMENT =
      new ScheduledRetirementContributionCreateType("REPAYMENT");
  public static final ScheduledRetirementContributionCreateType CONTRIBUTION_NON_REPORTABLE =
      new ScheduledRetirementContributionCreateType("CONTRIBUTION_NON_REPORTABLE");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, ScheduledRetirementContributionCreateType> values =
      createValuesMap();
  private static final Map<String, ScheduledRetirementContributionCreateTypeEnum> enums =
      createEnumsMap();

  private final String value;

  private ScheduledRetirementContributionCreateType(String value) {
    this.value = value;
  }

  /**
   * Returns a ScheduledRetirementContributionCreateType with the given value. For a specific value
   * the returned object will always be a singleton so reference equality is satisfied when the
   * values are the same.
   *
   * @param value value to be wrapped as ScheduledRetirementContributionCreateType
   */
  public static ScheduledRetirementContributionCreateType of(String value) {
    synchronized (ScheduledRetirementContributionCreateType.class) {
      return values.computeIfAbsent(value, v -> new ScheduledRetirementContributionCreateType(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<ScheduledRetirementContributionCreateTypeEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    ScheduledRetirementContributionCreateType other =
        (ScheduledRetirementContributionCreateType) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "ScheduledRetirementContributionCreateType [value=" + value + "]";
  }

  // return an array just like an enum
  public static ScheduledRetirementContributionCreateType[] values() {
    synchronized (ScheduledRetirementContributionCreateType.class) {
      return values.values().toArray(new ScheduledRetirementContributionCreateType[] {});
    }
  }

  private static final Map<String, ScheduledRetirementContributionCreateType> createValuesMap() {
    Map<String, ScheduledRetirementContributionCreateType> map = new LinkedHashMap<>();
    map.put("TYPE_UNSPECIFIED", TYPE_UNSPECIFIED);
    map.put("REGULAR", REGULAR);
    map.put("EMPLOYEE", EMPLOYEE);
    map.put("EMPLOYER", EMPLOYER);
    map.put("RECHARACTERIZATION", RECHARACTERIZATION);
    map.put("ROLLOVER_60_DAY", ROLLOVER60_DAY);
    map.put("ROLLOVER_DIRECT", ROLLOVER_DIRECT);
    map.put("TRANSFER", TRANSFER);
    map.put("TRUSTEE_FEE", TRUSTEE_FEE);
    map.put("CONVERSION", CONVERSION);
    map.put("REPAYMENT", REPAYMENT);
    map.put("CONTRIBUTION_NON_REPORTABLE", CONTRIBUTION_NON_REPORTABLE);
    return map;
  }

  private static final Map<String, ScheduledRetirementContributionCreateTypeEnum> createEnumsMap() {
    Map<String, ScheduledRetirementContributionCreateTypeEnum> map = new HashMap<>();
    map.put("TYPE_UNSPECIFIED", ScheduledRetirementContributionCreateTypeEnum.TYPE_UNSPECIFIED);
    map.put("REGULAR", ScheduledRetirementContributionCreateTypeEnum.REGULAR);
    map.put("EMPLOYEE", ScheduledRetirementContributionCreateTypeEnum.EMPLOYEE);
    map.put("EMPLOYER", ScheduledRetirementContributionCreateTypeEnum.EMPLOYER);
    map.put("RECHARACTERIZATION", ScheduledRetirementContributionCreateTypeEnum.RECHARACTERIZATION);
    map.put("ROLLOVER_60_DAY", ScheduledRetirementContributionCreateTypeEnum.ROLLOVER60_DAY);
    map.put("ROLLOVER_DIRECT", ScheduledRetirementContributionCreateTypeEnum.ROLLOVER_DIRECT);
    map.put("TRANSFER", ScheduledRetirementContributionCreateTypeEnum.TRANSFER);
    map.put("TRUSTEE_FEE", ScheduledRetirementContributionCreateTypeEnum.TRUSTEE_FEE);
    map.put("CONVERSION", ScheduledRetirementContributionCreateTypeEnum.CONVERSION);
    map.put("REPAYMENT", ScheduledRetirementContributionCreateTypeEnum.REPAYMENT);
    map.put(
        "CONTRIBUTION_NON_REPORTABLE",
        ScheduledRetirementContributionCreateTypeEnum.CONTRIBUTION_NON_REPORTABLE);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer
      extends StdSerializer<ScheduledRetirementContributionCreateType> {

    protected _Serializer() {
      super(ScheduledRetirementContributionCreateType.class);
    }

    @Override
    public void serialize(
        ScheduledRetirementContributionCreateType value,
        JsonGenerator g,
        SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<ScheduledRetirementContributionCreateType> {

    protected _Deserializer() {
      super(ScheduledRetirementContributionCreateType.class);
    }

    @Override
    public ScheduledRetirementContributionCreateType deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return ScheduledRetirementContributionCreateType.of(v);
    }
  }

  public enum ScheduledRetirementContributionCreateTypeEnum {
    TYPE_UNSPECIFIED("TYPE_UNSPECIFIED"),
    REGULAR("REGULAR"),
    EMPLOYEE("EMPLOYEE"),
    EMPLOYER("EMPLOYER"),
    RECHARACTERIZATION("RECHARACTERIZATION"),
    ROLLOVER60_DAY("ROLLOVER_60_DAY"),
    ROLLOVER_DIRECT("ROLLOVER_DIRECT"),
    TRANSFER("TRANSFER"),
    TRUSTEE_FEE("TRUSTEE_FEE"),
    CONVERSION("CONVERSION"),
    REPAYMENT("REPAYMENT"),
    CONTRIBUTION_NON_REPORTABLE("CONTRIBUTION_NON_REPORTABLE"),
    ;

    private final String value;

    private ScheduledRetirementContributionCreateTypeEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
