/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apexfintechsolutions.ascendsdk.models.components;

import com.apexfintechsolutions.ascendsdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * SearchClosedLotsResponse
 *
 * <p>Response message containing a list of closed lots. Closed lots are sorted in the response
 * first by disposal_date ascending, then by asset_id ascending
 */
public class SearchClosedLotsResponse {
  /** The list of closed lots. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("closed_lots")
  private Optional<? extends List<ClosedLot>> closedLots;

  /**
   * A token, which can be sent as page_token to retrieve the next page results. Please note that
   * when the results size is less than the requested page_size in the last page, next_page_token
   * will be empty. But when results size is equal to the requested page_size in the last page, the
   * next_page_token won’t be empty; and user would have to make one more additional request to get
   * the end of the results set.
   */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("next_page_token")
  private Optional<String> nextPageToken;

  @JsonCreator
  public SearchClosedLotsResponse(
      @JsonProperty("closed_lots") Optional<? extends List<ClosedLot>> closedLots,
      @JsonProperty("next_page_token") Optional<String> nextPageToken) {
    Utils.checkNotNull(closedLots, "closedLots");
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.closedLots = closedLots;
    this.nextPageToken = nextPageToken;
  }

  public SearchClosedLotsResponse() {
    this(Optional.empty(), Optional.empty());
  }

  /** The list of closed lots. */
  @SuppressWarnings("unchecked")
  @JsonIgnore
  public Optional<List<ClosedLot>> closedLots() {
    return (Optional<List<ClosedLot>>) closedLots;
  }

  /**
   * A token, which can be sent as page_token to retrieve the next page results. Please note that
   * when the results size is less than the requested page_size in the last page, next_page_token
   * will be empty. But when results size is equal to the requested page_size in the last page, the
   * next_page_token won’t be empty; and user would have to make one more additional request to get
   * the end of the results set.
   */
  @JsonIgnore
  public Optional<String> nextPageToken() {
    return nextPageToken;
  }

  public static Builder builder() {
    return new Builder();
  }

  /** The list of closed lots. */
  public SearchClosedLotsResponse withClosedLots(List<ClosedLot> closedLots) {
    Utils.checkNotNull(closedLots, "closedLots");
    this.closedLots = Optional.ofNullable(closedLots);
    return this;
  }

  /** The list of closed lots. */
  public SearchClosedLotsResponse withClosedLots(Optional<? extends List<ClosedLot>> closedLots) {
    Utils.checkNotNull(closedLots, "closedLots");
    this.closedLots = closedLots;
    return this;
  }

  /**
   * A token, which can be sent as page_token to retrieve the next page results. Please note that
   * when the results size is less than the requested page_size in the last page, next_page_token
   * will be empty. But when results size is equal to the requested page_size in the last page, the
   * next_page_token won’t be empty; and user would have to make one more additional request to get
   * the end of the results set.
   */
  public SearchClosedLotsResponse withNextPageToken(String nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = Optional.ofNullable(nextPageToken);
    return this;
  }

  /**
   * A token, which can be sent as page_token to retrieve the next page results. Please note that
   * when the results size is less than the requested page_size in the last page, next_page_token
   * will be empty. But when results size is equal to the requested page_size in the last page, the
   * next_page_token won’t be empty; and user would have to make one more additional request to get
   * the end of the results set.
   */
  public SearchClosedLotsResponse withNextPageToken(Optional<String> nextPageToken) {
    Utils.checkNotNull(nextPageToken, "nextPageToken");
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchClosedLotsResponse other = (SearchClosedLotsResponse) o;
    return Utils.enhancedDeepEquals(this.closedLots, other.closedLots)
        && Utils.enhancedDeepEquals(this.nextPageToken, other.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(closedLots, nextPageToken);
  }

  @Override
  public String toString() {
    return Utils.toString(
        SearchClosedLotsResponse.class, "closedLots", closedLots, "nextPageToken", nextPageToken);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Optional<? extends List<ClosedLot>> closedLots = Optional.empty();

    private Optional<String> nextPageToken = Optional.empty();

    private Builder() {
      // force use of static builder() method
    }

    /** The list of closed lots. */
    public Builder closedLots(List<ClosedLot> closedLots) {
      Utils.checkNotNull(closedLots, "closedLots");
      this.closedLots = Optional.ofNullable(closedLots);
      return this;
    }

    /** The list of closed lots. */
    public Builder closedLots(Optional<? extends List<ClosedLot>> closedLots) {
      Utils.checkNotNull(closedLots, "closedLots");
      this.closedLots = closedLots;
      return this;
    }

    /**
     * A token, which can be sent as page_token to retrieve the next page results. Please note that
     * when the results size is less than the requested page_size in the last page, next_page_token
     * will be empty. But when results size is equal to the requested page_size in the last page,
     * the next_page_token won’t be empty; and user would have to make one more additional request
     * to get the end of the results set.
     */
    public Builder nextPageToken(String nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = Optional.ofNullable(nextPageToken);
      return this;
    }

    /**
     * A token, which can be sent as page_token to retrieve the next page results. Please note that
     * when the results size is less than the requested page_size in the last page, next_page_token
     * will be empty. But when results size is equal to the requested page_size in the last page,
     * the next_page_token won’t be empty; and user would have to make one more additional request
     * to get the end of the results set.
     */
    public Builder nextPageToken(Optional<String> nextPageToken) {
      Utils.checkNotNull(nextPageToken, "nextPageToken");
      this.nextPageToken = nextPageToken;
      return this;
    }

    public SearchClosedLotsResponse build() {

      return new SearchClosedLotsResponse(closedLots, nextPageToken);
    }
  }
}
