/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * TimeHorizon - TThe length of time an investor expects to hold an investment before selling it;
 * this can affect the appropriate asset allocation and risk level for the portfolio
 */
@JsonDeserialize(using = TimeHorizon._Deserializer.class)
@JsonSerialize(using = TimeHorizon._Serializer.class)
public class TimeHorizon {

  public static final TimeHorizon TIME_HORIZON_UNSPECIFIED =
      new TimeHorizon("TIME_HORIZON_UNSPECIFIED");
  public static final TimeHorizon SHORT = new TimeHorizon("SHORT");
  public static final TimeHorizon AVERAGE = new TimeHorizon("AVERAGE");
  public static final TimeHorizon LONG = new TimeHorizon("LONG");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, TimeHorizon> values = createValuesMap();
  private static final Map<String, TimeHorizonEnum> enums = createEnumsMap();

  private final String value;

  private TimeHorizon(String value) {
    this.value = value;
  }

  /**
   * Returns a TimeHorizon with the given value. For a specific value the returned object will
   * always be a singleton so reference equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as TimeHorizon
   */
  public static TimeHorizon of(String value) {
    synchronized (TimeHorizon.class) {
      return values.computeIfAbsent(value, v -> new TimeHorizon(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<TimeHorizonEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    TimeHorizon other = (TimeHorizon) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "TimeHorizon [value=" + value + "]";
  }

  // return an array just like an enum
  public static TimeHorizon[] values() {
    synchronized (TimeHorizon.class) {
      return values.values().toArray(new TimeHorizon[] {});
    }
  }

  private static final Map<String, TimeHorizon> createValuesMap() {
    Map<String, TimeHorizon> map = new LinkedHashMap<>();
    map.put("TIME_HORIZON_UNSPECIFIED", TIME_HORIZON_UNSPECIFIED);
    map.put("SHORT", SHORT);
    map.put("AVERAGE", AVERAGE);
    map.put("LONG", LONG);
    return map;
  }

  private static final Map<String, TimeHorizonEnum> createEnumsMap() {
    Map<String, TimeHorizonEnum> map = new HashMap<>();
    map.put("TIME_HORIZON_UNSPECIFIED", TimeHorizonEnum.TIME_HORIZON_UNSPECIFIED);
    map.put("SHORT", TimeHorizonEnum.SHORT);
    map.put("AVERAGE", TimeHorizonEnum.AVERAGE);
    map.put("LONG", TimeHorizonEnum.LONG);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<TimeHorizon> {

    protected _Serializer() {
      super(TimeHorizon.class);
    }

    @Override
    public void serialize(TimeHorizon value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<TimeHorizon> {

    protected _Deserializer() {
      super(TimeHorizon.class);
    }

    @Override
    public TimeHorizon deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return TimeHorizon.of(v);
    }
  }

  public enum TimeHorizonEnum {
    TIME_HORIZON_UNSPECIFIED("TIME_HORIZON_UNSPECIFIED"),
    SHORT("SHORT"),
    AVERAGE("AVERAGE"),
    LONG("LONG"),
    ;

    private final String value;

    private TimeHorizonEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
