/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * TradeConfirmationDeliveryPreference - Delivery method instruction for trade confirmations for a
 * given Interested Party record; Can be `DIGITAL`, `PHYSICAL`, `SUPPRESS`; Defaults to `PHYSICAL`
 * on party creation
 */
@JsonDeserialize(using = TradeConfirmationDeliveryPreference._Deserializer.class)
@JsonSerialize(using = TradeConfirmationDeliveryPreference._Serializer.class)
public class TradeConfirmationDeliveryPreference {

  public static final TradeConfirmationDeliveryPreference DELIVERY_PREFERENCE_UNSPECIFIED =
      new TradeConfirmationDeliveryPreference("DELIVERY_PREFERENCE_UNSPECIFIED");
  public static final TradeConfirmationDeliveryPreference DIGITAL =
      new TradeConfirmationDeliveryPreference("DIGITAL");
  public static final TradeConfirmationDeliveryPreference PHYSICAL =
      new TradeConfirmationDeliveryPreference("PHYSICAL");
  public static final TradeConfirmationDeliveryPreference SUPPRESS =
      new TradeConfirmationDeliveryPreference("SUPPRESS");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, TradeConfirmationDeliveryPreference> values = createValuesMap();
  private static final Map<String, TradeConfirmationDeliveryPreferenceEnum> enums =
      createEnumsMap();

  private final String value;

  private TradeConfirmationDeliveryPreference(String value) {
    this.value = value;
  }

  /**
   * Returns a TradeConfirmationDeliveryPreference with the given value. For a specific value the
   * returned object will always be a singleton so reference equality is satisfied when the values
   * are the same.
   *
   * @param value value to be wrapped as TradeConfirmationDeliveryPreference
   */
  public static TradeConfirmationDeliveryPreference of(String value) {
    synchronized (TradeConfirmationDeliveryPreference.class) {
      return values.computeIfAbsent(value, v -> new TradeConfirmationDeliveryPreference(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<TradeConfirmationDeliveryPreferenceEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    TradeConfirmationDeliveryPreference other = (TradeConfirmationDeliveryPreference) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "TradeConfirmationDeliveryPreference [value=" + value + "]";
  }

  // return an array just like an enum
  public static TradeConfirmationDeliveryPreference[] values() {
    synchronized (TradeConfirmationDeliveryPreference.class) {
      return values.values().toArray(new TradeConfirmationDeliveryPreference[] {});
    }
  }

  private static final Map<String, TradeConfirmationDeliveryPreference> createValuesMap() {
    Map<String, TradeConfirmationDeliveryPreference> map = new LinkedHashMap<>();
    map.put("DELIVERY_PREFERENCE_UNSPECIFIED", DELIVERY_PREFERENCE_UNSPECIFIED);
    map.put("DIGITAL", DIGITAL);
    map.put("PHYSICAL", PHYSICAL);
    map.put("SUPPRESS", SUPPRESS);
    return map;
  }

  private static final Map<String, TradeConfirmationDeliveryPreferenceEnum> createEnumsMap() {
    Map<String, TradeConfirmationDeliveryPreferenceEnum> map = new HashMap<>();
    map.put(
        "DELIVERY_PREFERENCE_UNSPECIFIED",
        TradeConfirmationDeliveryPreferenceEnum.DELIVERY_PREFERENCE_UNSPECIFIED);
    map.put("DIGITAL", TradeConfirmationDeliveryPreferenceEnum.DIGITAL);
    map.put("PHYSICAL", TradeConfirmationDeliveryPreferenceEnum.PHYSICAL);
    map.put("SUPPRESS", TradeConfirmationDeliveryPreferenceEnum.SUPPRESS);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<TradeConfirmationDeliveryPreference> {

    protected _Serializer() {
      super(TradeConfirmationDeliveryPreference.class);
    }

    @Override
    public void serialize(
        TradeConfirmationDeliveryPreference value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<TradeConfirmationDeliveryPreference> {

    protected _Deserializer() {
      super(TradeConfirmationDeliveryPreference.class);
    }

    @Override
    public TradeConfirmationDeliveryPreference deserialize(
        JsonParser p, DeserializationContext ctxt) throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return TradeConfirmationDeliveryPreference.of(v);
    }
  }

  public enum TradeConfirmationDeliveryPreferenceEnum {
    DELIVERY_PREFERENCE_UNSPECIFIED("DELIVERY_PREFERENCE_UNSPECIFIED"),
    DIGITAL("DIGITAL"),
    PHYSICAL("PHYSICAL"),
    SUPPRESS("SUPPRESS"),
    ;

    private final String value;

    private TradeConfirmationDeliveryPreferenceEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
