/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/**
 * TransferScheduleSummaryDirection - Flag indicating whether this is a deposit or withdrawal
 * transfer
 */
@JsonDeserialize(using = TransferScheduleSummaryDirection._Deserializer.class)
@JsonSerialize(using = TransferScheduleSummaryDirection._Serializer.class)
public class TransferScheduleSummaryDirection {

  public static final TransferScheduleSummaryDirection DIRECTION_UNSPECIFIED =
      new TransferScheduleSummaryDirection("DIRECTION_UNSPECIFIED");
  public static final TransferScheduleSummaryDirection DEPOSIT =
      new TransferScheduleSummaryDirection("DEPOSIT");
  public static final TransferScheduleSummaryDirection WITHDRAWAL =
      new TransferScheduleSummaryDirection("WITHDRAWAL");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, TransferScheduleSummaryDirection> values = createValuesMap();
  private static final Map<String, TransferScheduleSummaryDirectionEnum> enums = createEnumsMap();

  private final String value;

  private TransferScheduleSummaryDirection(String value) {
    this.value = value;
  }

  /**
   * Returns a TransferScheduleSummaryDirection with the given value. For a specific value the
   * returned object will always be a singleton so reference equality is satisfied when the values
   * are the same.
   *
   * @param value value to be wrapped as TransferScheduleSummaryDirection
   */
  public static TransferScheduleSummaryDirection of(String value) {
    synchronized (TransferScheduleSummaryDirection.class) {
      return values.computeIfAbsent(value, v -> new TransferScheduleSummaryDirection(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<TransferScheduleSummaryDirectionEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    TransferScheduleSummaryDirection other = (TransferScheduleSummaryDirection) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "TransferScheduleSummaryDirection [value=" + value + "]";
  }

  // return an array just like an enum
  public static TransferScheduleSummaryDirection[] values() {
    synchronized (TransferScheduleSummaryDirection.class) {
      return values.values().toArray(new TransferScheduleSummaryDirection[] {});
    }
  }

  private static final Map<String, TransferScheduleSummaryDirection> createValuesMap() {
    Map<String, TransferScheduleSummaryDirection> map = new LinkedHashMap<>();
    map.put("DIRECTION_UNSPECIFIED", DIRECTION_UNSPECIFIED);
    map.put("DEPOSIT", DEPOSIT);
    map.put("WITHDRAWAL", WITHDRAWAL);
    return map;
  }

  private static final Map<String, TransferScheduleSummaryDirectionEnum> createEnumsMap() {
    Map<String, TransferScheduleSummaryDirectionEnum> map = new HashMap<>();
    map.put("DIRECTION_UNSPECIFIED", TransferScheduleSummaryDirectionEnum.DIRECTION_UNSPECIFIED);
    map.put("DEPOSIT", TransferScheduleSummaryDirectionEnum.DEPOSIT);
    map.put("WITHDRAWAL", TransferScheduleSummaryDirectionEnum.WITHDRAWAL);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<TransferScheduleSummaryDirection> {

    protected _Serializer() {
      super(TransferScheduleSummaryDirection.class);
    }

    @Override
    public void serialize(
        TransferScheduleSummaryDirection value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer
      extends StdDeserializer<TransferScheduleSummaryDirection> {

    protected _Deserializer() {
      super(TransferScheduleSummaryDirection.class);
    }

    @Override
    public TransferScheduleSummaryDirection deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return TransferScheduleSummaryDirection.of(v);
    }
  }

  public enum TransferScheduleSummaryDirectionEnum {
    DIRECTION_UNSPECIFIED("DIRECTION_UNSPECIFIED"),
    DEPOSIT("DEPOSIT"),
    WITHDRAWAL("WITHDRAWAL"),
    ;

    private final String value;

    private TransferScheduleSummaryDirectionEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
