/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apexfintechsolutions.ascendsdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper class for an "open" enum. "Open" enums are those that are expected to evolve
 * (particularly with the addition of enum members over time). If an open enum is used then the
 * appearance of unexpected enum values (say in a response from an updated an API) will not bring
 * about a runtime error thus ensuring that non-updated client versions can continue to work without
 * error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe cache is
 * maintained to ensure that). As a consequence instances created with the same value will satisfy
 * reference equality (via {@code ==}).
 *
 * <p>This class is intended to emulate an enum (in terms of common usage and with reference
 * equality) but with the ability to carry unknown values. Unfortunately Java does not permit the
 * use of an instance in a switch expression but you can use the {@code asEnum()} method (after
 * dealing with the `Optional` appropriately).
 */
/** YieldType - Characterization of a yield percentage */
@JsonDeserialize(using = YieldType._Deserializer.class)
@JsonSerialize(using = YieldType._Serializer.class)
public class YieldType {

  public static final YieldType YIELD_TYPE_UNSPECIFIED = new YieldType("YIELD_TYPE_UNSPECIFIED");
  public static final YieldType YIELD_TO_CALL = new YieldType("YIELD_TO_CALL");
  public static final YieldType YIELD_TO_MATURITY = new YieldType("YIELD_TO_MATURITY");
  public static final YieldType YIELD_TO_PUT = new YieldType("YIELD_TO_PUT");
  public static final YieldType YIELD_TO_WORST = new YieldType("YIELD_TO_WORST");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, YieldType> values = createValuesMap();
  private static final Map<String, YieldTypeEnum> enums = createEnumsMap();

  private final String value;

  private YieldType(String value) {
    this.value = value;
  }

  /**
   * Returns a YieldType with the given value. For a specific value the returned object will always
   * be a singleton so reference equality is satisfied when the values are the same.
   *
   * @param value value to be wrapped as YieldType
   */
  public static YieldType of(String value) {
    synchronized (YieldType.class) {
      return values.computeIfAbsent(value, v -> new YieldType(v));
    }
  }

  public String value() {
    return value;
  }

  public Optional<YieldTypeEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    YieldType other = (YieldType) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "YieldType [value=" + value + "]";
  }

  // return an array just like an enum
  public static YieldType[] values() {
    synchronized (YieldType.class) {
      return values.values().toArray(new YieldType[] {});
    }
  }

  private static final Map<String, YieldType> createValuesMap() {
    Map<String, YieldType> map = new LinkedHashMap<>();
    map.put("YIELD_TYPE_UNSPECIFIED", YIELD_TYPE_UNSPECIFIED);
    map.put("YIELD_TO_CALL", YIELD_TO_CALL);
    map.put("YIELD_TO_MATURITY", YIELD_TO_MATURITY);
    map.put("YIELD_TO_PUT", YIELD_TO_PUT);
    map.put("YIELD_TO_WORST", YIELD_TO_WORST);
    return map;
  }

  private static final Map<String, YieldTypeEnum> createEnumsMap() {
    Map<String, YieldTypeEnum> map = new HashMap<>();
    map.put("YIELD_TYPE_UNSPECIFIED", YieldTypeEnum.YIELD_TYPE_UNSPECIFIED);
    map.put("YIELD_TO_CALL", YieldTypeEnum.YIELD_TO_CALL);
    map.put("YIELD_TO_MATURITY", YieldTypeEnum.YIELD_TO_MATURITY);
    map.put("YIELD_TO_PUT", YieldTypeEnum.YIELD_TO_PUT);
    map.put("YIELD_TO_WORST", YieldTypeEnum.YIELD_TO_WORST);
    return map;
  }

  @SuppressWarnings("serial")
  public static final class _Serializer extends StdSerializer<YieldType> {

    protected _Serializer() {
      super(YieldType.class);
    }

    @Override
    public void serialize(YieldType value, JsonGenerator g, SerializerProvider provider)
        throws IOException, JsonProcessingException {
      g.writeObject(value.value);
    }
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends StdDeserializer<YieldType> {

    protected _Deserializer() {
      super(YieldType.class);
    }

    @Override
    public YieldType deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JacksonException {
      String v = p.readValueAs(new TypeReference<String>() {});
      // use the factory method to ensure we get singletons
      return YieldType.of(v);
    }
  }

  public enum YieldTypeEnum {
    YIELD_TYPE_UNSPECIFIED("YIELD_TYPE_UNSPECIFIED"),
    YIELD_TO_CALL("YIELD_TO_CALL"),
    YIELD_TO_MATURITY("YIELD_TO_MATURITY"),
    YIELD_TO_PUT("YIELD_TO_PUT"),
    YIELD_TO_WORST("YIELD_TO_WORST"),
    ;

    private final String value;

    private YieldTypeEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
